/*
 * Generated by: Sergey.Shpakovskiy
 * Generated at: 1.0.0.3
 * Copyright © JSC NAT Kazakhstan 2011
 */
#pragma warning disable
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Linq;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Security.Principal;
using System.Text;
using System.Web;
using System.Web.Caching;
using System.Web.Compilation;
using System.Web.Script.Serialization;
using System.Web.UI;
using System.Web.UI.WebControls;
using JS.LinqToJavaScript;

using Nat.Tools.Specific;
using Nat.Web.Controls;
using Nat.Web.Controls.GenerationClasses;
using Nat.Web.Controls.GenerationClasses.Data;
using Nat.Web.Controls.GenerationClasses.Filter;
using Nat.Web.Controls.GenerationClasses.Navigator;
using Nat.Web.Controls.HistoryFilters;
using Nat.Web.Controls.Preview;
using Nat.Web.Tools;
using Nat.Web.Tools.Security;
using Nat.Web.Tools.WorkFlow;
using SampleDictionaries.UserControls;
using SampleDictionaries.Properties;
using SampleDictionaries.Security;
using AccessOptions = SampleDictionaries.MyProductsAccessOptions;


using Nat.Web.Tools.ExtNet.Data;
using Nat.Web.Tools.ExtNet.Extenders;
using Nat.Web.Tools.ExtNet.ExtNetConfig;

namespace SampleDictionaries
{
    #region MyProductsJournalDataSourceView

    public partial class MyProductsJournalDataSourceView : BaseDataSourceView<long, MyProduct, DBDataContext, MyProductsJournalDataSourceView.Row>, IDataSourceView2, IDataSourceView3, IHeaderControl, IDataSourceViewExtNet
    {
        private readonly BaseDataSource<long> owner;
        private SelectModeMyProducts? _select;
        private MyProductsFilter _filterSelect;
        private bool? _showHistory;
        private IEnumerable<Row> _cache;
        private MainPageUrlBuilder _url;

        public MyProductsJournalDataSourceView(BaseDataSource<long> owner, string viewName)
            : base(owner, viewName)
        {
            this.owner = owner;
            this.Lookup = new LookupExpressions { GetUrl = () => _url };
        }

        public MyProductsJournalDataSourceView()
            : base(new MyProductsJournalDataSource(), string.Empty)
        {
            this.Lookup = new LookupExpressions { GetUrl = () => _url };
        }
                
        public override bool LookupValuesHidden
        {
            set 
            {
                base.LookupValuesHidden = value;
                Lookup.DefaultHidden = value;
            }
        }
        
        public LookupExpressions Lookup { get; private set; }

        public SelectModeMyProducts SelectMode
        {
            get 
            {
                try
                {
                    if (_url != null)
                        _select = (SelectModeMyProducts?)Enum.Parse(typeof(SelectModeMyProducts), _url.SelectMode, true);
                    if (owner == null && _select == null) _select = SelectModeMyProducts.none;
                    if (_select == null) _select = (SelectModeMyProducts?)Enum.Parse(typeof(SelectModeMyProducts), MainPageUrlBuilder.GetSelectMode(owner.Page), true);
                }
                catch
                {
                    _select = SelectModeMyProducts.none;
                }
                
                return _select.Value;
            }
            
            set
            {
                _select = value;
            }
        }

        public override string TableName
        {
            get { return "MyProducts"; }
        }

        public override bool CanSort
        {
            get { return true; }
        }

        public override bool CanPage
        {
            get { return true; }
        }

        public override bool CanRetrieveTotalRowCount
        {
            get { return true; }
        }

        public string Header
        {
            get { return MyProductsResources.Header; }
        }

        public string HeaderRu
        {
            get { return MyProductsResources.ResourceManager.GetString("Header", new CultureInfo("ru-ru")); }
        }

        public string HeaderKz
        {
            get { return MyProductsResources.ResourceManager.GetString("Header", new CultureInfo("kk-kz")); }
        }

        partial void InitDefaultSort(ref string sortValue);
        
        protected override string DefaultSort
        {
            get
            {
                var sortValue = "Name,id";
                InitDefaultSort(ref sortValue);
                return sortValue;
            }
        }

        protected override string RequiredSort
        {
            get { return "id"; }
        }
        
        public override bool SupportGlobalCache { get { return false; } }

        public override bool SupportSelectICodeRow
        {
            get { return false; }
        }

        [Conditional("DEBUG")]
        private void WriteTrace(string value)
        {
            if (owner != null && owner.Page != null)
                owner.Page.Trace.Write(value);
        }

        protected override DBDataContext CreateDataContext()
        {
            var db = InitConnection == null ? new DBDataContext(SpecificInstances.DbFactory.CreateConnection()) : new DBDataContext(InitConnection);
            return db;
        }

        protected override IWorkFlow[] CreateWorkFlows()
        {
            return new IWorkFlow[] {};
        }

        private IEnumerable<Row> EnsureExistRow(IQueryable<Row> rows)
        {
            if (!AllowCreateSelectedRow || _selectedID == null) return rows;
            var list = rows.ToList();
            foreach (var item in list)
                if (item.id == _selectedID.Value)
                    return list;
            list.Add(new Row
            {
                id = _selectedID.Value,
                Value = _selectedID.Value.ToString(),
                nameRu = Nat.Web.Controls.Properties.Resources.SNotExistRow,
                nameKz = Nat.Web.Controls.Properties.Resources.SNotExistRow,
            });
            return list;
        }

        public override string GetStringID(MyProduct row)
        {
            return GetID(row).ToString();
        }

        public override long? GetID(MyProduct row)
        {
            return row.id;
        }

        public override long? GetIDByRefParent(MyProduct row)
        {
            return null;
        }

        protected override bool UseTreeFilter { get { return false; } }

        public IQueryable<Row> GetSelect(long id)
        {
            return GetSelect(id, string.Empty);
        }

        public IQueryable<Row> GetSelect(long id, bool isKz)
        {
            return GetSelect(id, string.Empty, isKz);
        }

        public IQueryable<Row> GetSelect(long id, string selectColumnName)
        {
            return GetSelect(selectColumnName).Where(p => p.Item.id == id);
        }

        public IQueryable<Row> GetSelect(long id, string selectColumnName, bool isKz)
        {
            return GetSelect(selectColumnName, isKz).Where(p => p.Item.id == id);
        }

        public IQueryable<Row> GetSelect(long id, string selectColumnName, bool isKz, bool isTreeFilter)
        {
            return GetSelect(null, selectColumnName, isKz, isTreeFilter).Where(p => p.Item.id == id);
        }

        public override IQueryable<IRow> GetSelectIRow(long id)
        {
            return GetSelect(id).Cast<IRow>();
        }

        public override IQueryable<ICodeRow> GetSelectICodeRow(long id)
        {
            throw new NotImplementedException();
        }

        public override IQueryable<IRow> GetSelectIRow()
        {
            return GetSelect().Cast<IRow>();
        }

        public override IQueryable<ICodeRow> GetSelectICodeRow()
        {
            throw new NotImplementedException();
        }

        public IQueryable<Row> GetSelectWithoutFilters(long id)
        {
            return GetSelectWithoutFilters(id, string.Empty);
        }

        public IQueryable<Row> GetSelectWithoutFilters(long id, string selectColumnName)
        {
            return GetSelectWithoutFilters(selectColumnName).Where(p => p.Item.id == id);
        }

        public override Expression<Func<MyProduct, long, bool>> GetWhereByKey()
        {
            return (p, id) => p.id == id;
        }

        public override object GetKey(string key)
        {
            return Convert.ToInt64(key);
        }

        public override string GetName(long id, string selectColumnName, bool isKz)
        {
            if (isKz)
                return GetSelectWithoutFilters(id, selectColumnName).Select(p => p.nameKz).FirstOrDefault();
            return GetSelectWithoutFilters(id, selectColumnName).Select(p => p.nameRu).FirstOrDefault();
        }

        public override IQueryable<BaseRow> GetSelectRow(long value, string selectColumnName)
        {
            return GetSelect(value, selectColumnName).Cast<BaseRow>();
        }

        public override IQueryable<IRow> GetSelectIRow(string queryParameters)
        {
            DB.ObjectTrackingEnabled = false;
            DB.DeferredLoadingEnabled = false;
            _filterSelect = new MyProductsFilter();
            var urlBuilder = new MainPageUrlBuilder("/MainPage.aspx/data/MyProductsJournal/Select?" + queryParameters);
            _filterSelect.SetUrl(urlBuilder);
            _filterSelect.SetDB(DB);
            _url = urlBuilder;
            SelectForAddType = urlBuilder.SelectForAddType;
            SelectParameters = urlBuilder.SelectParameters;
            AddSearchInFilter(urlBuilder, _filterSelect);
            if (!string.IsNullOrEmpty(urlBuilder.SelectNameColumn))
                return GetSelect(urlBuilder.SelectNameColumn).Cast<IRow>().Select(r => r);
            return GetSelect().Cast<IRow>().Select(r => r);
        }

        IQueryable<IDataRow> IDataSourceView2.GetSelectIRow(string queryParameters)
        {
            DB.ObjectTrackingEnabled = false;
            DB.DeferredLoadingEnabled = false;
            _filterSelect = new MyProductsFilter();
            var urlBuilder = new MainPageUrlBuilder("/MainPage.aspx/data/MyProductsJournal/Select?" + queryParameters);
            _filterSelect.SetUrl(urlBuilder);
            _filterSelect.SetDB(DB);
            _url = urlBuilder;
            SelectForAddType = urlBuilder.SelectForAddType;
            SelectParameters = urlBuilder.SelectParameters;
            AddSearchInFilter(urlBuilder, _filterSelect);
            if (!string.IsNullOrEmpty(urlBuilder.SelectNameColumn))
                return GetSelect(urlBuilder.SelectNameColumn).Cast<IDataRow>().Select(r => r);
            return GetSelect().Cast<IDataRow>().Select(r => r);
        }

        IQueryable<IDataRow> IDataSourceViewExtNet.GetFullModelData(string queryParameters)
        {
            DB.ObjectTrackingEnabled = false;
            DB.DeferredLoadingEnabled = false;
            _filterSelect = new MyProductsFilter();
            var url = "/MainPage.aspx/data/MyProductsJournal/Select"
                      + (!string.IsNullOrEmpty(queryParameters) && queryParameters[0] == '/'
                          ? queryParameters
                          : "?" + queryParameters);
            var urlBuilder = new MainPageUrlBuilder(url);
            _filterSelect.SetUrl(urlBuilder);
            _filterSelect.SetDB(DB);
            _filterSelect.ShowHistory = urlBuilder.ShowHistory;
            _url = urlBuilder;
            AddSearchInFilter(urlBuilder, _filterSelect);
            SelectForAddType = urlBuilder.SelectForAddType;
            SelectParameters = urlBuilder.SelectParameters;
            IQueryable<Row> data;
            if (!string.IsNullOrEmpty(urlBuilder.SelectNameColumn))
                data = GetSelect(urlBuilder.SelectNameColumn);
            else
                data = GetSelect();

            return data.Select(GetFullModelDataExpression).Cast<IDataRow>();
        }

        IQueryable<IDataRow> IDataSourceViewExtNet.GetFullModelData(string queryParameters, string refParent)
        {
            throw new NotSupportedException();
        }

        public Expression<Func<Row, IDataRow>> GetFullModelDataExpression
        {
            get
            {
                return row => new ModelData
                    {
                        CanEdit = row.CanEdit,
                        CanDelete = row.CanDelete,
                        id = row.Item.id,
                        Name = row.Item.Name,
                        CreationDate = row.Item.CreationDate,
                        Price = row.Item.Price,
                        Amount = row.Item.Amount,
                        RowVersion = row.Item.RowVersion,
                        nameRu = row.nameRu,
                        nameKz = row.nameKz,
                    };
            }
        }

        public override IQueryable<ICodeRow> GetSelectICodeRow(string queryParameters)
        {
            throw new NotImplementedException();
        }

        IQueryable<IDataCodeRow> IDataSourceView2.GetSelectICodeRow(string queryParameters)
        {
            throw new NotImplementedException();
        }

        public override BaseInformationValues Validate(long value, CancelEventArgs args)
        {
            var row = GetCacheSelect(value);
            if (row == null)
            {
                args.Cancel = true;
                return null;
            }
            if (row.Information != null)
                row.Information.Validate();
            return row.Information;
        }

        public override Row[] ValidateAll(long[] values, CancelEventArgs args)
        {
            var rememberShowHistory = _showHistory;
            var recArgs = args as RecordValidateArgs;
            if (recArgs != null && recArgs.IgnoreHistoryFilter)
                _showHistory = true;
            var rows = GetSelect().Where(r => values.Contains(r.id)).ToArray();
            _showHistory = rememberShowHistory;

            if (rows.Length == 0)
            {
                args.Cancel = true;
                return new Row[0];
            }
            foreach (var row in rows.Where(row => row.Information != null))
                row.Information.Validate();
            return rows;
        }

        public override BaseInformationValues Validate(long value, RecordValidateArgs args)
        {
            var rememberShowHistory = _showHistory;
            if (args.IgnoreHistoryFilter)
                _showHistory = true;
            var row = GetCacheSelect(value);
            _showHistory = rememberShowHistory;
            if (row == null || (!row.CanAddChild && args.SelectForAddChild))
            {
                args.Cancel = true;
                return null;
            }
            if (row.Information != null)
                row.Information.Validate();
            return row.Information;
        }

        public override bool CheckPermit()
        {
            return AccessOptions.CheckPermit();
        }

        public override BaseFilterControl<long> CreateDefaultFilter(MainPageUrlBuilder urlBuilder)
        {
            var control = new MyProductsFilter();
            urlBuilder.UserControl = MyProductsFilter.ConstOfColumnNames.JournalName;
            return control;
        }

        protected override Expression GetFilteredExpression(Expression query, QueryParameters qParams, out BaseFilterControl<long, MyProduct, DBDataContext> outFilterControl)
        {
            MyProductsFilter filterControl = _filterSelect;
            if (_filterSelect == null)
            {
                var args = new DataSourceSelectingEventArgs { DB = DB };
                if (owner != null) owner.OnSelecting(args);
                filterControl = (MyProductsFilter)args.FilterControl;
            }
            if(filterControl == null)
            {
                var fc = new MyProductsFilter();
                filterControl = fc;
                fc.SetUrl(new MainPageUrlBuilder { SelectMode = "none", UserControl = MyProductsFilter.ConstOfColumnNames.JournalName, });
                fc.SetDB(DB);
            }
            if (_showHistory == null)
                _showHistory = filterControl.ShowHistory;
            else
                filterControl.ShowHistory = _showHistory.Value;
            _selectedID = filterControl.SelectedID;
            _url = filterControl.Url;
            outFilterControl = filterControl;
            return filterControl.GetFilteredExpression(query, qParams);
        }

        protected IQueryable<MyProduct> SetFilter(IQueryable<MyProduct> queryable)
        {
            MyProductsFilter filterControl = _filterSelect;
            if (_filterSelect == null)
            {
                var args = new DataSourceSelectingEventArgs { DB = DB };
                owner.OnSelecting(args);
                filterControl = (MyProductsFilter)args.FilterControl;
            }
            if (filterControl == null)
            {
                var fc = new MyProductsFilter();
                filterControl = fc;
                fc.SetUrl(new MainPageUrlBuilder { SelectMode = "none", UserControl = MyProductsFilter.ConstOfColumnNames.JournalName });
                fc.SetDB(DB);
                if (!string.IsNullOrEmpty(SelectedRowKey))
                    filterControl.SelectedID = Convert.ToInt64(SelectedRowKey);
            }
            if (_showHistory == null)
                _showHistory = filterControl.ShowHistory;
            else
                filterControl.ShowHistory = _showHistory.Value;
            _selectedID = filterControl.SelectedID;
            _url = filterControl.Url;
            return (IQueryable<MyProduct>)filterControl.SetFilters(queryable);
        }

        public partial class TotalInfo
        {
        }

        partial void GetTotalInfo(DataSourceSelectArguments arguments, ref IEnumerable<TotalInfo> result);

        public IEnumerable<TotalInfo> GetTotalInfo(DataSourceSelectArguments arguments)
        {
            IEnumerable<TotalInfo> result = null;
            GetTotalInfo(arguments, ref result);
            return result;
        }

        partial void ChangeSelect(ref Expression<Func<MyProduct, LookupValues, InformationValues>> informationExpression);
        partial void ChangeSelectDB(ref Expression<Func<DBDataContext, MyProduct, LookupValues, InformationValues>> informationExpression);
        
        private static ConstructorInfo rowCtr = typeof(Row).GetConstructor(new [] { typeof(MyProduct), typeof(LookupValues), typeof(InformationValues), typeof(string), typeof(string), typeof(bool), typeof(bool), typeof(bool), typeof(Int64) });
        private static ConstructorInfo lookupCtr = typeof(LookupValues).GetConstructor(new[] { typeof(int), typeof(object[]) });
        
        private IQueryable<Row> ChangeSelect(IQueryable<MyProduct> query, string selectColumnName)
        {
            var isKz = System.Globalization.CultureInfo.CurrentUICulture.Name.Equals("kk-kz", StringComparison.OrdinalIgnoreCase);
            return ChangeSelect(query, selectColumnName, isKz);
        }
        
        private IQueryable<Row> ChangeSelect(IQueryable<MyProduct> query, string selectColumnName, bool isKz)
        {
            Expression exp = GetSelectedRowExpression(query.Expression, selectColumnName, isKz, null);
            return query.Provider.CreateQuery<Row>(exp);
        }
        
        protected override Expression GetSelectedRowExpression(Expression query, string selectColumnName, bool isKz, QueryParameters qParams)
        {
            WriteTrace("MyProductsJournalDataSourceView.ChangeSelect.Begin");
            if (qParams != null)
                qParams.SelectColumnName = selectColumnName;
            var showHistory = _showHistory == null || _showHistory.Value;
            var time = DateTime.Now;
            IQueryable<Row> result;
        
            var param = Expression.Parameter(typeof(MyProduct), "c");
            Lookup.IsKz = isKz;
            Lookup.DB = DB;
            Lookup.ShowHistory = showHistory;
            Lookup.QueryParameters = qParams;
            if (qParams != null)
            {
                qParams.AddUniqueParameter("IsKz=" + isKz);
                qParams.AddUniqueParameter("ShowHistory=" + showHistory);
            }
            
            var MyProductActions_refProductExp = Lookup.GetExpressionFK_MyProductActions_MyProducts_refProduct(param);
            var selectedAdditionalValuesExp = GetSelectedAdditionalValuesExpression(DB, param);
            Expression lookupExp = Expression.New(lookupCtr, 
                new Expression[] { MyProductActions_refProductExp, selectedAdditionalValuesExp }, 
                new MemberInfo[] {typeof(LookupValues).GetMember("CountOfMyProductActions_refProduct")[0], typeof(LookupValues).GetMember("SelectedAdditionalValues")[0]});
            Expression lookupPred = Expression.Lambda(lookupExp, param);
            Expression<Func<MyProduct, LookupValues, InformationValues>> informationExpression = null;
            Expression<Func<DBDataContext, MyProduct, LookupValues, InformationValues>> informationExpressionDB = null;
            ChangeSelect(ref informationExpression);
            ChangeSelectDB(ref informationExpressionDB);
            Expression informationExp;
            Type selectType = typeof(MyProduct);
        
            if (informationExpressionDB != null)
                informationExp = Expression.Invoke(informationExpressionDB, qParams.GetDBExpression(DB), param, lookupExp);
            else if (informationExpression != null)
                informationExp = Expression.Invoke(informationExpression, param, lookupExp);
            else
                informationExp = Expression.Constant(null, typeof(InformationValues)); 
        
            Expression<Func<MyProduct, string>> nameRuExp;
            Expression<Func<MyProduct, string>> nameKzExp;
            GetNameExpressions(selectColumnName, out nameRuExp, out nameKzExp);
            Expression<Func<MyProduct, Int64>> idKeyExp = p => p.id;
            Expression expItem = param;
        
            Expression canEditExp;
            Expression canDeleteExp;
            GetEditAndDeleteExpressions(expItem, informationExp, out canEditExp, out canDeleteExp);
            
            Expression canAddChildExp = null;
            Type selectForAddType = string.IsNullOrEmpty(SelectForAddType) ? null : BuildManager.GetType(SelectForAddType, true, true);
            if (selectForAddType != null)
                canAddChildExp = GetAddChildExpression(null, selectForAddType, expItem, param, new Expression[0]);
            if (canAddChildExp == null)
                canAddChildExp = Expression.Constant(true);
            
            var rowExp = Expression.New(rowCtr, 
                new Expression[] { expItem, lookupExp, informationExp, Expression.Invoke(nameRuExp, expItem), Expression.Invoke(nameKzExp, expItem), canEditExp, canDeleteExp, canAddChildExp, Expression.Invoke(idKeyExp, expItem) },
                new MemberInfo[] { typeof(Row).GetMember("Item")[0], typeof(Row).GetMember("Lookup")[0], typeof(Row).GetMember("Information")[0], typeof(Row).GetMember("nameRu")[0], typeof(Row).GetMember("nameKz")[0], typeof(Row).GetMember("CanEdit")[0], typeof(Row).GetMember("CanDelete")[0], typeof(Row).GetMember("CanAddChild")[0], typeof(Row).GetMember("id")[0] });
            Expression pred = Expression.Lambda(rowExp, param);
            Expression expr = Expression.Call(typeof(Queryable), "Select", new[] { selectType, typeof(Row) }, query, pred);
            WriteTrace("MyProductsJournalDataSourceView.ChangeSelect.End");
            return expr;
        }
        
        partial void GetNameExpressionPartial(string selectColumnName, ref Expression<Func<MyProduct, string>> nameRuExp, ref Expression<Func<MyProduct, string>> nameKzExp);
        
        private void GetNameExpressions(string selectColumnName, out Expression<Func<MyProduct, string>> nameRuExp, out Expression<Func<MyProduct, string>> nameKzExp)
        {
            nameRuExp = nameKzExp = null;
            GetNameExpressionPartial(selectColumnName, ref nameRuExp, ref nameKzExp);
            if (nameRuExp != null && nameKzExp != null)
                return;
        
            if (string.IsNullOrEmpty(selectColumnName))
            {
                nameKzExp = nameRuExp = p => p.Name;
            }
            else
            {
                switch(selectColumnName)
                {
                    case "Name":
                        nameKzExp = nameRuExp = r => r.Name.ToString();
                        break;
                    case "CreationDate":
                        nameKzExp = nameRuExp = r => string.Format("{0:d}", r.CreationDate.ToString());
                        break;
                    case "Price":
                        nameKzExp = nameRuExp = r => r.Price.ToString();
                        break;
                    case "Amount":
                        nameKzExp = nameRuExp = r => r.Amount.ToString();
                        break;
                    default:
                        throw new ArgumentException("Не найдена соответствующая колонка", "selectColumnName");
                }
            }
        }
        
        
        
        bool _canEditAndDeleteExpressionInitialized = false;
        Expression _canEditAndDeleteExpCache;
        Expression _canEditExpCache;
        Expression _canDeleteExpCache;
        partial void SetCanEditAndDeleteExpression(BaseFilterEventArgs<MyProduct> filterArgs);
        partial void SetCanEditExpression(BaseFilterEventArgs<MyProduct> filterArgs);
        partial void SetCanDeleteExpression(BaseFilterEventArgs<MyProduct> filterArgs);
        partial void SetCanEditAndDeleteExpression(BaseFilterEventArgs<MyProduct, DBDataContext> filterArgs);
        partial void SetCanEditExpression(BaseFilterEventArgs<MyProduct, DBDataContext> filterArgs);
        partial void SetCanDeleteExpression(BaseFilterEventArgs<MyProduct, DBDataContext> filterArgs);
        
        private void GetEditAndDeleteExpressions(Expression expItem, Expression informationExp, out Expression canEditExp, out Expression canDeleteExp)
        {
            if (AllowSelectOnlyNames)
            {
                canEditExp = Expression.Constant(false);
                canDeleteExp = Expression.Constant(false);
                return;
            }
            Expression canEditExpression = null;
            Expression canDeleteExpression = null;
            Expression canEditAndDeleteExpression = null;
        
            if (_canEditAndDeleteExpressionInitialized)
            {
                canEditAndDeleteExpression = _canEditAndDeleteExpCache;
                canEditExpression = _canEditExpCache;
                canDeleteExpression = _canDeleteExpCache;
            }
            else
            {
                _canEditAndDeleteExpCache = canEditAndDeleteExpression = GetEditAndDeleteExpression(canEditAndDeleteExpression);
                _canEditExpCache = canEditExpression = GetEditExpression(canEditExpression);
                _canDeleteExpCache = canDeleteExpression = GetDeleteExpression(canDeleteExpression);
            }
            canEditExp = canEditExpression == null ? (Expression)Expression.Constant(true) : Expression.Invoke(canEditExpression, expItem);
            canDeleteExp = canDeleteExpression == null ? (Expression)Expression.Constant(true) : Expression.Invoke(canDeleteExpression, expItem);
            if (canEditAndDeleteExpression != null)
            {
                Expression canEditAndDeleteExp = Expression.Invoke(canEditAndDeleteExpression, expItem);
                canEditExp = Expression.And(canEditAndDeleteExp, canEditExp);
                canDeleteExp = Expression.And(canEditAndDeleteExp, canDeleteExp);
            }
        }
        
        public override BaseFilterEventArgs<MyProduct> GetEditAndDeleteFilter(Type typeOfData)
        {
            var filterArgs = base.GetEditAndDeleteFilter(typeOfData);
        
            SetCanEditAndDeleteExpression(filterArgs);
            SetCanEditAndDeleteExpression((BaseFilterEventArgs<MyProduct, DBDataContext>)filterArgs);
            return filterArgs;
        }
        /*
        public override Expression GetEditAndDeleteByParents<T>(Expression source, ParameterExpression param, Expression upToTable, IEnumerable<Expression> fieldsToCheckReference)
        {
        
            return source;
        }*/
        
        public override BaseFilterEventArgs<MyProduct> GetEditFilter(Type typeOfData)
        {
            var filterArgs = base.GetEditFilter(typeOfData);
        
            SetCanEditExpression(filterArgs);
            SetCanEditExpression((BaseFilterEventArgs<MyProduct, DBDataContext>)filterArgs);
            return filterArgs;
        }
        /*
        public override Expression GetEditByParents<T>(Expression source, ParameterExpression param, Expression upToTable, IEnumerable<Expression> fieldsToCheckReference)
        {
        
            return source;
        }*/
        
        public override BaseFilterEventArgs<MyProduct> GetDeleteFilter(Type typeOfData)
        {
            var filterArgs = base.GetDeleteFilter(typeOfData);
        
            SetCanDeleteExpression(filterArgs);
            SetCanDeleteExpression((BaseFilterEventArgs<MyProduct, DBDataContext>)filterArgs);
            return filterArgs;
        }
        /*
        public override Expression GetDeleteByParents<T>(Expression source, ParameterExpression param, Expression upToTable, IEnumerable<Expression> fieldsToCheckReference)
        {
        
            return source;
        }*/
        
        private List<ParentDataSourceViewInfo> _parentDataSources = null;
        partial void InitializeParentCollection(ICollection<ParentDataSourceViewInfo> parentDataSources);
        
        public override IEnumerable<ParentDataSourceViewInfo> GetParentCollection()
        {
            if (_parentDataSources != null) return _parentDataSources;
             _parentDataSources = new List<ParentDataSourceViewInfo>();
        
            InitializeParentCollection(_parentDataSources);
            return _parentDataSources;
        }
        
        Expression _canAddExpCache;
        
        partial void SetCanAddChildsExpression(BaseFilterEventArgs<MyProduct> filterArgs);
        
        protected override BaseFilterEventArgs<MyProduct> GetAddRule(Type typeOfData)
        {
            var filterArgs = base.GetAddRule(typeOfData);
        
            SetCanAddChildsExpression(filterArgs);
            return filterArgs;
        }
        
        public override IEnumerable<IQueryable> AllowAddRowGetSources(BaseNavigatorValues valuesT)
        {
            if (InitConnection != null) DB.Transaction = InitTransaction;
            var values = (MyProductsNavigatorValues)valuesT;
            var sources = new List<IQueryable>();
            return sources;
        }
        
        public override IQueryable<MyProduct> GetSelectItems(long id)
        {
            if (InitConnection != null) DB.Transaction = InitTransaction;
            return DB.MyProducts.Where(row => row.id == id);
        }
        
        public override IQueryable<MyProduct> GetSelectItems()
        {
            if (InitConnection != null) DB.Transaction = InitTransaction;
            return DB.MyProducts;
        }
        
        /*
        private IQueryable<Row> ChangeSelect(IQueryable<MyProduct> query, string selectColumnName)
        {
            WriteTrace("MyProductsJournalDataSourceView.ChangeSelect.Begin");
            var isKz = System.Globalization.CultureInfo.CurrentUICulture.Name.Equals("kk-kz", StringComparison.OrdinalIgnoreCase);
            var time = DateTime.Now;
            IQueryable<Row> result;
            if (_showHistory == null || _showHistory.Value)
                result = from p in query
                    select new Row
                               {
                                   id = p.id,
                                   Value = p.id.ToString(),
                                   Item = p,
                                   Lookup = new LookupValues
                                                {
                                                    CountOfMyProductActions_refProduct = p.MyProductActions_refProduct.Count(),
                                                 },
                                   nameRu = p.Name.ToString(),
                                   nameKz = p.Name.ToString(),
                               };
            else
                result = from p in query
                    select new Row
                               {
                                   id = p.id,
                                   Value = p.id.ToString(),
                                   Item = p,
                                   Lookup = new LookupValues
                                                {
                                                    CountOfMyProductActions_refProduct = p.MyProductActions_refProduct.Count(),
                                                 },
                                   nameRu = p.Name.ToString(),
                                   nameKz = p.Name.ToString(),
                               };
            if (!string.IsNullOrEmpty(selectColumnName))
            {
                switch(selectColumnName)
                {
                    case "id":
                        result = result.Select(r => 
                           new Row 
                           {
                               id = r.id,
                               Value = r.Value,
                               Item = r.Item,
                               Lookup = r.Lookup,
                               Information = r.Information,
                               nameRu = r.Item.id.ToString(),
                               nameKz = r.Item.id.ToString(),
                           });
                        break;
                    case "Name":
                        result = result.Select(r => 
                           new Row 
                           {
                               id = r.id,
                               Value = r.Value,
                               Item = r.Item,
                               Lookup = r.Lookup,
                               Information = r.Information,
                               nameRu = r.Item.Name.ToString(),
                               nameKz = r.Item.Name.ToString(),
                           });
                        break;
                    case "CreationDate":
                        result = result.Select(r => 
                           new Row 
                           {
                               id = r.id,
                               Value = r.Value,
                               Item = r.Item,
                               Lookup = r.Lookup,
                               Information = r.Information,
                               nameRu = string.Format("{0:d}", r.Item.CreationDate.ToString()),
                               nameKz = string.Format("{0:d}", r.Item.CreationDate.ToString()),
                           });
                        break;
                    case "Price":
                        result = result.Select(r => 
                           new Row 
                           {
                               id = r.id,
                               Value = r.Value,
                               Item = r.Item,
                               Lookup = r.Lookup,
                               Information = r.Information,
                               nameRu = r.Item.Price.ToString(),
                               nameKz = r.Item.Price.ToString(),
                           });
                        break;
                    case "Amount":
                        result = result.Select(r => 
                           new Row 
                           {
                               id = r.id,
                               Value = r.Value,
                               Item = r.Item,
                               Lookup = r.Lookup,
                               Information = r.Information,
                               nameRu = r.Item.Amount.ToString(),
                               nameKz = r.Item.Amount.ToString(),
                           });
                        break;
                    case "RowVersion":
                        result = result.Select(r => 
                           new Row 
                           {
                               id = r.id,
                               Value = r.Value,
                               Item = r.Item,
                               Lookup = r.Lookup,
                               Information = r.Information,
                               nameRu = r.Item.RowVersion.ToString(),
                               nameKz = r.Item.RowVersion.ToString(),
                           });
                        break;
                    default:
                        throw new ArgumentException("Не найдена соответствующая колонка", "selectColumnName");
                }
            }
            WriteTrace("MyProductsJournalDataSourceView.ChangeSelect.End");
            return result;
        }*/

        public Row GetRecord(long id)
        {
            WriteTrace("MyProductsJournalDataSourceView.ChangeSelect.Begin");
            var query = DB.MyProducts.AsQueryable();
            var resQuery = ChangeSelect(query, string.Empty);
            IQueryable<Row> result = null;
            //ChangeSelect(resQuery, ref result, DB);
            Row returnValue;
            if (result != null)
                returnValue = result.FirstOrDefault(p => p.Item.id == id);
            else
                returnValue = resQuery.FirstOrDefault(p => p.Item.id == id);
            WriteTrace("MyProductsJournalDataSourceView.ChangeSelect.End");
            return returnValue;
        }

        partial void InitializeStoreModelPartial(Ext.Net.Model model);

        public virtual void InitializeStoreModel(Ext.Net.Model model)
        {
            // todo: Add full store model scheme
            InitializeStoreModelPartial(model);
        }

        public virtual void InitializeStoreModelAdditional(Ext.Net.Model model)
        {
            InitializeStoreModelPartial(model);
        }



        public class Row : BaseRow
        {
            public Row()
            {
            }
        
            public Row(MyProduct item, LookupValues lookup, InformationValues information, string nameRu, string nameKz, bool canEdit, bool canDelete, bool canAddChild, Int64 id)
            {
                Item = item;
                Lookup = lookup;
                Information = information;
                this.id = id;
                Value = id.ToString();
                this.nameRu = nameRu;
                this.nameKz = nameKz;
                CanEdit = canEdit;
                CanDelete = canDelete;
                CanAddChild = canAddChild;
            }
        
            public override string nameRu 
            { 
                get { return base.nameRu; }
                set { base.nameRu = value; } 
            }
        
            public override string nameKz
            {
                get { return base.nameKz; }
                set { base.nameKz = value; }
            }
        
            public override bool CanEdit
            {
                get { return base.CanEdit; }
                set { base.CanEdit = value; }
            }
        
            public override bool CanDelete
            {
                get { return base.CanDelete; }
                set { base.CanDelete = value; }
            }
        
            public override bool CanAddChild
            {
                get { return base.CanAddChild; }
                set { base.CanAddChild = value; }
            }
        
            public override long id
            {
                get { return base.id; }
                set { base.id = value; }
            }
        
            private LookupValues _lookup;
            public LookupValues Lookup
            {
                get { return _lookup; }
                set 
                { 
                    _lookup = value;
                    if (Item != null)
                    {
                        // Если нет полей с заполнением из БД, то избавляемся от дублирования объекта у строк
                        // Т.е. LinqToSql передает один объект всем строкам, а тут мы меняем поведение.
                        if (_lookup.Item != null)
                            _lookup = new LookupValues { SelectedAdditionalValues = new object[0] };
                        _lookup.Item = Item;
                    }
                    if (Information != null)
                        Information.Lookup = _lookup;
                    _lookup.Row = this;
                }
            }
        
            private InformationValues _information;
            public InformationValues Information
            {
                get { return _information; }
                set 
                { 
                    _information = value;
                    if (Item != null && _information != null)
                        _information.Item = Item;
                    if (Lookup != null && _information != null)
                        _information.Lookup = Lookup;
                }
            }
        
            [NonSerialized]
            MyProduct _item;
            public MyProduct Item 
            {
                get { return _item; }
                set 
                { 
                    _item = value;
                    if (Lookup != null)
                        Lookup.Item = value;
                    if (Information != null)
                        Information.Item = value;
                }
            }
        
            public string AdditionalValues
            {
                get { return Lookup == null ? null : Ext.Net.JSON.Serialize(Lookup.SelectedAdditionalValues); }
            }
        
            public override string[] GetAdditionalValues(SelectParameters selectParameters)
            {
                return Lookup == null ? null : Lookup.SelectedAdditionalValues.Select((r, i) => string.Format(selectParameters.SelectValues[i].Format, r)).ToArray();
            }
        
            public override object[] GetAdditionalValues()
            {
                return Lookup == null ? null : Lookup.SelectedAdditionalValues;
            }
        
            public virtual void SetValue(string strValue)
            {
                Value = strValue;
        
            }
        }

        [Serializable]
        public partial class LookupValues
        {
            public LookupValues()
            {
            }
        
            public LookupValues(int countOfMyProductActions_refProduct,
        object[] selectedAdditionalValues)
            {        
                CountOfMyProductActions_refProduct = countOfMyProductActions_refProduct;
                this.SelectedAdditionalValues = selectedAdditionalValues;
            }
            
            public int CountOfMyProductActions_refProduct { get; set; }
        
            [NonSerialized]
            MyProduct _item;
        
            [ScriptIgnore]
            public MyProduct Item 
            {
                get { return _item; }
                set { _item = value; }
            }
        
            [NonSerialized]
            Row _row;
        
            [ScriptIgnore]
            public Row Row
            {
                get { return _row; }
                set { _row = value; }
            }
        
            public object [] SelectedAdditionalValues { get; set; }
        }
        
        public partial class InformationValues : BaseInformationValues
        {
            public InformationValues()
            {
            }
        
            [NonSerialized]
            private LookupValues _lookup;
        
            [ScriptIgnore]
            public LookupValues Lookup
            {
                get { return _lookup; }
                set 
                { 
                    _lookup = value;
                    if (Item != null)
                        _lookup.Item = Item;
                }
            }
        
            [NonSerialized]
            private MyProduct _item;
        
            [ScriptIgnore]
            public MyProduct Item
            {
                get { return _item; }
                set 
                { 
                    _item = value;
                    if (Lookup != null)
                        Lookup.Item = value;
                }
            }
        }
        
        public partial class ModelData : BaseRow
        {
            public ModelData()
            {
            }
        
            public System.Int64 id { get; set; }
        
            public System.String Name { get; set; }
        
            public System.DateTime CreationDate { get; set; }
        
            public System.Decimal Price { get; set; }
        
            public System.Decimal Amount { get; set; }
        
            public System.Data.Linq.Binary RowVersion { get; set; }
        }
        
        
        
        public class LookupExpressions
        {
            private static readonly Expression NullExpression = Expression.Constant(null, typeof(string));
            private static readonly Expression NullIntExpression = Expression.Constant(0, typeof(int));
        
            private bool isKz { get; set; }
        
            public bool IsKz
            {
                get { return isKz; } 
                set { isKz = value; }
            }
        
            private bool showHistory { get; set; }
        
            public bool ShowHistory
            {
                get { return showHistory; } 
                set { showHistory = value; }
            }
        
            private QueryParameters qParams { get; set; }
        
            public QueryParameters QueryParameters
            {
                get { return qParams; } 
                set { qParams = value; }
            }
            
            public Func<MainPageUrlBuilder> GetUrl { get; set; }
        
            public DBDataContext DB { get; set; }
            public bool DefaultHidden { get; set; }
        
        
            private bool? _FK_MyProductActions_MyProducts_refProductHidden;
        
            public bool FK_MyProductActions_MyProducts_refProductHidden
            {
                get { return _FK_MyProductActions_MyProducts_refProductHidden ?? DefaultHidden; }
                set { _FK_MyProductActions_MyProducts_refProductHidden = value; }
            }
        
            public Expression GetExpressionFK_MyProductActions_MyProducts_refProduct(ParameterExpression param)
            {
                if (FK_MyProductActions_MyProducts_refProductHidden)
                    return NullIntExpression;
        
        Expression MyProductActions_refProductChildExp = Expression.Convert(Expression.Property(param, "MyProductActions_refProduct"), typeof(IQueryable<MyProductAction>));
        var MyProductActions_refProductF = MyProductActionsFilter.CreateDefault(null, DB, showHistory);
        MyProductActions_refProductF.UseHistoryFilter = true;
        MyProductActions_refProductChildExp = MyProductActions_refProductF.FilterData(MyProductActions_refProductChildExp, qParams, false);
        MyProductActions_refProductChildExp = Expression.Call(typeof(Queryable), "Count", new[] { typeof(MyProductAction) }, MyProductActions_refProductChildExp);
        Expression MyProductActions_refProductExp = MyProductActions_refProductChildExp;
                return MyProductActions_refProductExp;
            }
        }

        protected static IQueryable<MyProduct> SetSortExpression(string sortExpression, IQueryable source)
        {
            Expression expression = source.Expression;
            string str = "OrderBy";
            string str2 = "OrderByDescending";
            foreach (string orderBy in sortExpression.Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries))
            {
                var split = orderBy.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
                bool ascending = true;
                if (split.Length == 2)
                    ascending = split[1].Equals("Asc", StringComparison.OrdinalIgnoreCase);

                string orderByColumn = split[0];
                ParameterExpression param = Expression.Parameter(typeof(MyProduct), "c");
                Type fieldType;
                var property = LinqFilterGenerator.GetProperty(typeof(MyProduct), orderByColumn, param, out fieldType);
                expression = Expression.Call(typeof(Queryable), ascending ? str : str2,
                                             new[] { typeof(MyProduct), fieldType },
                                             expression,
                                             Expression.Lambda(property, param));
                str = "ThenBy";
                str2 = "ThenByDescending";
            }
            return (IQueryable<MyProduct>)source.Provider.CreateQuery(expression);
        }
    }

    #endregion

    #region MyProductsJournalDataSource

    public class MyProductsJournalDataSource : BaseDataSource<long, MyProduct, DBDataContext, MyProductsJournalDataSourceView.Row>, IDataSource
    {
        private MyProductsJournalDataSourceView view;

        public MyProductsJournalDataSourceView View
        {
            get
            {
                if(view == null)
                    view = new MyProductsJournalDataSourceView(this, "default");
                return view;
            }
        }

        public override BaseDataSourceView<long, MyProduct, DBDataContext, MyProductsJournalDataSourceView.Row> BaseView2
        {
            get { return View; }
        }

        public MyProductsJournalDataSourceView.Row GetRecord(long id)
        {
            return View.GetRecord(id);
        }
    }

    #endregion

    #region FileManager

    

    #endregion

    #region AccessOptions

    public static partial class MyProductsAccessOptions
    {
        /// <summary>
        /// Изменение проверки прав, 
        /// если replace = true, то праверка прав возвращает isPermit, 
        /// иначе стандартная проверка прав и isPermit
        /// </summary>
        static partial void ChangeCheckPermit(ref bool replace, ref bool isPermit);
        
        public static bool CheckPermit()
        {
            bool replace = false;
            bool isPermit = true;
            ChangeCheckPermit(ref replace, ref isPermit);
            return isPermit;
        }
    
        /// <summary>
        /// Изменение проверки прав, 
        /// если replace = true, то праверка прав возвращает isPermit, 
        /// иначе стандартная проверка прав и isPermit
        /// </summary>
        static partial void ChangeCheckPermitAdd(ref bool replace, ref bool isPermit);
        
        public static bool CheckPermitAdd()
        {
            bool replace = false;
            bool isPermit = true;
            ChangeCheckPermitAdd(ref replace, ref isPermit);
            return isPermit;
        }
    
        /// <summary>
        /// Изменение проверки прав, 
        /// если replace = true, то праверка прав возвращает isPermit, 
        /// иначе стандартная проверка прав и isPermit
        /// </summary>
        static partial void ChangeCheckPermitEdit(ref bool replace, ref bool isPermit);
        
        public static bool CheckPermitEdit()
        {
            bool replace = false;
            bool isPermit = true;
            ChangeCheckPermitEdit(ref replace, ref isPermit);
            return isPermit;
        }
    
        /// <summary>
        /// Изменение проверки прав, 
        /// если replace = true, то праверка прав возвращает isPermit, 
        /// иначе стандартная проверка прав и isPermit
        /// </summary>
        static partial void ChangeCheckPermitDelete(ref bool replace, ref bool isPermit);
        
        public static bool CheckPermitDelete()
        {
            bool replace = false;
            bool isPermit = true;
            ChangeCheckPermitDelete(ref replace, ref isPermit);
            return isPermit;
        }
    }

    #endregion

    #region MyProductsItemNavigatorsInitializer

    public partial class MyProductsItemNavigatorsInitializer
    {
        protected MainPageUrlBuilder Url { get; set; }

        private DBDataContext _db;
        public DBDataContext DB
        {
            get
            {
                if (_db == null)
                {
                    _db = new DBDataContext(SpecificInstances.DbFactory.CreateConnection()) {ObjectTrackingEnabled = false};
                }

                return _db;
            }
            set { _db = value; }
        }

        partial void Initialize(IDictionary<Type, SelectedParameterNavigator.ItemNavigator> itemNavigators);

        public static void InitializeDic(IDictionary<Type, SelectedParameterNavigator.ItemNavigator> itemNavigators, MainPageUrlBuilder url)
        {
            var item = new MyProductsItemNavigatorsInitializer();
            item.Url = url;
            item.Initialize(itemNavigators);
            var i = item as IItemNavigatorsInitializer;
            if (i != null) i.Initialize(itemNavigators);
        }
    }

    #endregion
   
    #region MultipleKeyClass
    
    

    #endregion

    #region ActivityController

    namespace UserControls
    {
        using JS.LinqToJavaScript.Attributes;
    
        [SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1121:UseBuiltInTypeAlias", Justification = "Reviewed. Suppression is OK here.")]
        [JavaScriptClass(ClassName = "MyProductsActivityController", Namespace = "SampleDictionaries", BaseClassName = "JS.Web.ActivityController")]
        internal partial class MyProductsActivityController : ActivityController
        {
            List<string> _activityControls;
            
            MyProductsEdit.ControlInfo Info { get; set; }
            
            /// <summary>
            /// Наименование.
            /// </summary>
            [JavaScriptProperty]
            public ActivityControlName NameControl { get; set; }
            
            /// <summary>
            /// Дата создания.
            /// </summary>
            [JavaScriptProperty]
            public ActivityControlCreationDate CreationDateControl { get; set; }
            
            /// <summary>
            /// Цена.
            /// </summary>
            [JavaScriptProperty]
            public ActivityControlPrice PriceControl { get; set; }
            
            /// <summary>
            /// Доступно.
            /// </summary>
            [JavaScriptProperty]
            public ActivityControlAmount AmountControl { get; set; }
            
            
            
            public override IEnumerable<string> ActivityControls
            {
                get 
                {
                    InitializeActivityControls();
                    return _activityControls;
                }
            }
    
            partial void InitializeActivity();
            partial void InitializeActivityControls(List<string> activityControls);
    
            public void Initialize(Control form, Dictionary<string, object> values, MyProductsEdit.ControlInfo info)
            {
                Info = info;
                ReadOnly = info.IsRead;
                IsNew = info.IsNew;
                Control control;
                string controlID;
                string clientID;
                control = info.NameControl;
                controlID = control == null ? null : control.ID;
                clientID = control == null ? null : control.ClientID;
                NameControl = new ActivityControlName(this, "Name", controlID);
                NameControl.ClientID = clientID;
                NameControl.Control = info.NameControl;
                NameControl.ReadOnlyChanged += (sender, args) =>
                    {
                        if (info.NameControl != null)
                            info.NameControl.ReadOnly = args.Value;
                    };
                NameControl.DefaultAllowRequiredValidate = true;
                NameControl.AllowRequiredValidateChanged += Nat.Web.Controls.ExtNet.Generation.ActivityControlExtensions.AllowRequiredValidateChanged(info.NameControl);
                NameControl.DefaultReadOnly = false;
                NameControl.VisibleChanged += (sender, args) =>
                    {
                        if (info.NameControl != null)
                        {
                            info.NameControl.Hidden = !args.Value;
                            AbstractContainerExtender.SetHiddenControlContainer(info.NameControl);
                        }
                    };
                NameControl.EnabledChanged += (sender, args) =>
                    {
                        if (info.NameControl != null)
                            info.NameControl.Disabled = !args.Value;
                    };
                NameControl.AllowValidateChanged += delegate(object sender, ActivityChangedEventArgs args)
                    {
                        if (info.NameControl != null)
                            SetEnabledToValidators(form.Page, ValidationGroup, info.NameControl.ID, args.Value);
                    };
                NameControl.GetControlValueHandler = () => info.Name;
            
                control = info.CreationDateControl;
                controlID = control == null ? null : control.ID;
                clientID = control == null ? null : control.ClientID;
                CreationDateControl = new ActivityControlCreationDate(this, "CreationDate", controlID);
                CreationDateControl.ClientID = clientID;
                CreationDateControl.Control = info.CreationDateControl;
                CreationDateControl.ReadOnlyChanged += (sender, args) =>
                    {
                        if (info.CreationDateControl != null)
                            info.CreationDateControl.ReadOnly = args.Value;
                    };
                CreationDateControl.DefaultAllowRequiredValidate = true;
                CreationDateControl.AllowRequiredValidateChanged += Nat.Web.Controls.ExtNet.Generation.ActivityControlExtensions.AllowRequiredValidateChanged(info.CreationDateControl);
                CreationDateControl.DefaultReadOnly = false;
                CreationDateControl.VisibleChanged += (sender, args) =>
                    {
                        if (info.CreationDateControl != null)
                        {
                            info.CreationDateControl.Hidden = !args.Value;
                            AbstractContainerExtender.SetHiddenControlContainer(info.CreationDateControl);
                        }
                    };
                CreationDateControl.EnabledChanged += (sender, args) =>
                    {
                        if (info.CreationDateControl != null)
                            info.CreationDateControl.Disabled = !args.Value;
                    };
                CreationDateControl.AllowValidateChanged += delegate(object sender, ActivityChangedEventArgs args)
                    {
                        if (info.CreationDateControl != null)
                            SetEnabledToValidators(form.Page, ValidationGroup, info.CreationDateControl.ID, args.Value);
                    };
                CreationDateControl.GetControlValueHandler = () => info.CreationDate;
            
                control = info.PriceControl;
                controlID = control == null ? null : control.ID;
                clientID = control == null ? null : control.ClientID;
                PriceControl = new ActivityControlPrice(this, "Price", controlID);
                PriceControl.ClientID = clientID;
                PriceControl.Control = info.PriceControl;
                PriceControl.ReadOnlyChanged += (sender, args) =>
                    {
                        if (info.PriceControl != null)
                            info.PriceControl.ReadOnly = args.Value;
                    };
                PriceControl.DefaultAllowRequiredValidate = true;
                PriceControl.AllowRequiredValidateChanged += Nat.Web.Controls.ExtNet.Generation.ActivityControlExtensions.AllowRequiredValidateChanged(info.PriceControl);
                PriceControl.DefaultReadOnly = false;
                PriceControl.VisibleChanged += (sender, args) =>
                    {
                        if (info.PriceControl != null)
                        {
                            info.PriceControl.Hidden = !args.Value;
                            AbstractContainerExtender.SetHiddenControlContainer(info.PriceControl);
                        }
                    };
                PriceControl.EnabledChanged += (sender, args) =>
                    {
                        if (info.PriceControl != null)
                            info.PriceControl.Disabled = !args.Value;
                    };
                PriceControl.AllowValidateChanged += delegate(object sender, ActivityChangedEventArgs args)
                    {
                        if (info.PriceControl != null)
                            SetEnabledToValidators(form.Page, ValidationGroup, info.PriceControl.ID, args.Value);
                    };
                PriceControl.GetControlValueHandler = () => info.Price;
            
                control = info.AmountControl;
                controlID = control == null ? null : control.ID;
                clientID = control == null ? null : control.ClientID;
                AmountControl = new ActivityControlAmount(this, "Amount", controlID);
                AmountControl.ClientID = clientID;
                AmountControl.Control = info.AmountControl;
                AmountControl.ReadOnlyChanged += (sender, args) =>
                    {
                        if (info.AmountControl != null)
                            info.AmountControl.ReadOnly = args.Value;
                    };
                AmountControl.DefaultAllowRequiredValidate = true;
                AmountControl.AllowRequiredValidateChanged += Nat.Web.Controls.ExtNet.Generation.ActivityControlExtensions.AllowRequiredValidateChanged(info.AmountControl);
                AmountControl.DefaultReadOnly = true;
                AmountControl.VisibleChanged += (sender, args) =>
                    {
                        if (info.AmountControl != null)
                        {
                            info.AmountControl.Hidden = !args.Value;
                            AbstractContainerExtender.SetHiddenControlContainer(info.AmountControl);
                        }
                    };
                AmountControl.EnabledChanged += (sender, args) =>
                    {
                        if (info.AmountControl != null)
                            info.AmountControl.Disabled = !args.Value;
                    };
                AmountControl.AllowValidateChanged += delegate(object sender, ActivityChangedEventArgs args)
                    {
                        if (info.AmountControl != null)
                            SetEnabledToValidators(form.Page, ValidationGroup, info.AmountControl.ID, args.Value);
                    };
                AmountControl.GetControlValueHandler = () => info.Amount;
            
                InitializeControls(
                    NameControl,
                    CreationDateControl,
                    PriceControl,
                    AmountControl);
            
                Initialize(form, values);
                FormID = Info.FormControl.ClientID;
            
                InitializeActivity();
            }
            
            public override void Initialize(Control form, Dictionary<string, object> values)
            {
                if (form == null)
                {
                    NameControl = new ActivityControlName(this, "Name", null);
                    CreationDateControl = new ActivityControlCreationDate(this, "CreationDate", null);
                    PriceControl = new ActivityControlPrice(this, "Price", null);
                    AmountControl = new ActivityControlAmount(this, "Amount", null);
            
                    InitializeActivity();
                }
            
                base.Initialize(form, values);
            }
            
            protected void InitializeActivityControls()
            {
                if (_activityControls != null) return;
            
                _activityControls = new List<string>
                    {
                        "nameControl",
                        "creationDateControl",
                        "priceControl",
                        "amountControl",
                    };
                InitializeActivityControls(_activityControls);
            }
            
            
            
            /// <summary>
            /// Наименование.
            /// </summary>
            [JavaScriptClass(ClassName = "MyProductsActivityController_ActivityControlName", Namespace = "SampleDictionaries", BaseClassName = "JS.Web.ActivityController")]
            public class ActivityControlName : ActivityControlClassValue<MyProductsActivityController, String>
            {
                public ActivityControlName(MyProductsActivityController activityController, string controlID, string controlName)
                    : base(activityController, controlID, controlName)
                {
                }
            }
            
            /// <summary>
            /// Дата создания.
            /// </summary>
            [JavaScriptClass(ClassName = "MyProductsActivityController_ActivityControlCreationDate", Namespace = "SampleDictionaries", BaseClassName = "JS.Web.ActivityController")]
            public class ActivityControlCreationDate : ActivityControl<MyProductsActivityController, DateTime>
            {
                public ActivityControlCreationDate(MyProductsActivityController activityController, string controlID, string controlName)
                    : base(activityController, controlID, controlName)
                {
                }
            }
            
            /// <summary>
            /// Цена.
            /// </summary>
            [JavaScriptClass(ClassName = "MyProductsActivityController_ActivityControlPrice", Namespace = "SampleDictionaries", BaseClassName = "JS.Web.ActivityController")]
            public class ActivityControlPrice : ActivityControl<MyProductsActivityController, Decimal>
            {
                public ActivityControlPrice(MyProductsActivityController activityController, string controlID, string controlName)
                    : base(activityController, controlID, controlName)
                {
                }
            }
            
            /// <summary>
            /// Доступно.
            /// </summary>
            [JavaScriptClass(ClassName = "MyProductsActivityController_ActivityControlAmount", Namespace = "SampleDictionaries", BaseClassName = "JS.Web.ActivityController")]
            public class ActivityControlAmount : ActivityControl<MyProductsActivityController, Decimal>
            {
                public ActivityControlAmount(MyProductsActivityController activityController, string controlID, string controlName)
                    : base(activityController, controlID, controlName)
                {
                }
            }
        }
    }

    #endregion

    #region ValidateInformationForm

    namespace UserControls
    {
        [SuppressMessage("StyleCop.CSharp.NamingRules", "SA1306:FieldNamesMustBeginWithLowerCaseLetter", Justification = "Reviewed. Suppression is OK here.")]
        internal class MyProductsValidateInformationForm : Nat.Web.Controls.ExtNet.Validators.ValidateInformationForm
        {
            private ValidateInformation _Name;
            private ValidateInformation _CreationDate;
            private ValidateInformation _Price;
            private ValidateInformation _Amount;
    
            public MyProductsValidateInformationForm(Control form)
                : base(form)
            {
            }
    
            public ValidateInformation Name
            {
                get
                {
                    if (_Name == null)
                    {
                        _Name = new ValidateInformation();
                        Validators["Name"] = _Name;
                    }
            
                    return _Name;
                }
            }
            
            public ValidateInformation CreationDate
            {
                get
                {
                    if (_CreationDate == null)
                    {
                        _CreationDate = new ValidateInformation();
                        Validators["CreationDate"] = _CreationDate;
                    }
            
                    return _CreationDate;
                }
            }
            
            public ValidateInformation Price
            {
                get
                {
                    if (_Price == null)
                    {
                        _Price = new ValidateInformation();
                        Validators["Price"] = _Price;
                    }
            
                    return _Price;
                }
            }
            
            public ValidateInformation Amount
            {
                get
                {
                    if (_Amount == null)
                    {
                        _Amount = new ValidateInformation();
                        Validators["Amount"] = _Amount;
                    }
            
                    return _Amount;
                }
            }
    
            public void AddDefaultValidatorsForName(MyProductsEdit.ControlInfo info)
            {
                Name.RequiredValidatorPropertieses.Add(new RequiredValidatorProperties { InitialValue = "" });
                if (Validators.ContainsKey("Name"))
                {
                    var validator = Name.RequiredValidatorPropertieses.FirstOrDefault();
                    if (validator != null && string.IsNullOrEmpty(validator.ErrorMessageInSummary))
                        validator.ErrorMessageInSummary = MyProductsEdit.GetRequiredMessage_Name();
                    if (validator != null && validator.InitialValue == null)
                        validator.InitialValue = "";
                }
            }
            
            public void AddDefaultValidatorsForCreationDate(MyProductsEdit.ControlInfo info)
            {
                CreationDate.RequiredValidatorPropertieses.Add(new RequiredValidatorProperties { InitialValue = "" });
                if (Validators.ContainsKey("CreationDate"))
                {
                    var validator = CreationDate.RequiredValidatorPropertieses.FirstOrDefault();
                    if (validator != null && string.IsNullOrEmpty(validator.ErrorMessageInSummary))
                        validator.ErrorMessageInSummary = MyProductsEdit.GetRequiredMessage_CreationDate();
                    if (validator != null && validator.InitialValue == null)
                        validator.InitialValue = "";
                }
            }
            
            public void AddDefaultValidatorsForPrice(MyProductsEdit.ControlInfo info)
            {
                Price.RequiredValidatorPropertieses.Add(new RequiredValidatorProperties { InitialValue = "" });
                Price.RegexValidatorPropertieses.Add(
                    new RegexValidatorProperties 
                        {
                            ErrorMessage = Nat.Web.Controls.Properties.Resources.SNotCorrectNumber,
                            ErrorMessageInSummary = MyProductsEdit.GetNotCorrectNumberMessage_Price(),
                            RegularExpression = @"\-?\d{0,5}((\.|,)\d{0,2})?",
                        });
                if (Validators.ContainsKey("Price"))
                {
                    var validator = Price.RequiredValidatorPropertieses.FirstOrDefault();
                    if (validator != null && string.IsNullOrEmpty(validator.ErrorMessageInSummary))
                        validator.ErrorMessageInSummary = MyProductsEdit.GetRequiredMessage_Price();
                    if (validator != null && validator.InitialValue == null)
                        validator.InitialValue = "";
                }
            }
            
            public void AddDefaultValidatorsForAmount(MyProductsEdit.ControlInfo info)
            {
                if (Validators.ContainsKey("Amount"))
                {
                    var validator = Amount.RequiredValidatorPropertieses.FirstOrDefault();
                    if (validator != null && string.IsNullOrEmpty(validator.ErrorMessageInSummary))
                        validator.ErrorMessageInSummary = MyProductsEdit.GetRequiredMessage_Amount();
                    if (validator != null && validator.InitialValue == null)
                        validator.InitialValue = "";
                }
            }
        }
    }

    #endregion

    #region TableRowsConsts

    public static class MyProductsRowsConsts
    {
    
    }

    #endregion

    #region NavigatorControl

    public partial class MyProductsNavigatorControl : BaseNavigatorControl<MyProductsNavigatorValues>
    {
        public override Type NavigatorType { get { return typeof(MyProductsNavigatorInfo); } }
    }

    #endregion

    #region NavigatorValues

    public partial class MyProductsNavigatorValues : BaseNavigatorValues
    {
        public long? MyProducts
        {
            get
            {
                if (!Values.ContainsKey(typeof(MyProduct))) return null;
                return (long?)Values[typeof(MyProduct)];
            }
            set
            {
                Values[typeof(MyProduct)] = value;
            }
        }
    
        protected override string TableName { get { return "MyProducts"; } }
    }

    #endregion

    #region NavigatorInfoAllClasses

    public partial class MyProductsNavigatorInfo : BaseNavigatorInfo
    {
        public override Type TableType { get { return typeof(MyProduct); } }
        public override Type DataSourceViewType { get { return typeof(MyProductsJournalDataSourceView); } }
        public override string TableName { get { return "MyProducts"; } }
        public override string Header { get { return MyProductsResources.Header; } }
        public override string HeaderToChilds { get { return ""; } }
        public override string HeaderToParent { get { return ""; } }
        public override string ReferenceName { get { return ""; } }
        
        public override void Initialize()
        {
            BaseInitialize();
            
        }
        
        
    }

    #endregion

    #region ViewModeClass

    public enum ViewModeMyProducts
    {
        none,
    }

    #endregion

    #region AdditionalRowInfoClasses

    

    #endregion

    #region TableParametersClasses

    

    #endregion

    #region TableInterface

    

    #endregion

    #region GetCacheNamesClass

    public static class MyProductsCacheNames
    {
    
        public static string GetNameRu(DataContext db, long? rowValue)
        {
            return CacheQueries.GetNameCached<MyProduct, long?, string>(
                        db, rowValue, (r, id) => r.id == id, r => r.Name);
        }
    
        public static string GetName(DataContext db, long? rowValue)
        {
            return CacheQueries.GetNameCached<MyProduct, long?, string>(
                        db, 
                        rowValue, 
                        (r, id) => r.id == id, 
                        r => r.Name, 
                        new ExpressionCulture<Func<MyProduct, string>>("kk-kz", r => r.Name));
        }
        
        public static void ClearCache(DataContext db, long? rowValue)
        {
            if (rowValue == null)
                return;
            CacheQueries.ClearCache<MyProduct, long?, string>(
                db,
                rowValue.Value, 
                (r, id) => r.id == id, 
                r => r.Name, 
                new ExpressionCulture<Func<MyProduct, string>>("kk-kz", r => r.Name));
        }
    }

    #endregion

    #region ComboBoxViews

    

    #endregion
}
#pragma warning restore