/*
 * Generated by: Sergey.Shpakovskiy
 * Generated at: 1.0.0.2
 * Copyright © JSC NAT Kazakhstan 2011
 */
#pragma warning disable
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data.Linq;
using System.Data.SqlClient;
using System.Drawing.Design;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Net.Mail;
using System.Net;
using System.Security.Principal;
using System.Text;
using System.Xml.Linq;
using System.Web;
using System.Web.Compilation;
using System.Web.Configuration;
using System.Web.Script.Serialization;
using System.Web.UI;
using System.Web.UI.WebControls;
using SampleDictionaries.Properties;


using Nat.Tools.Specific;
using Nat.Web.Controls;
using Nat.Web.Controls.BaseLogic;
using Nat.Web.Controls.GenerationClasses;
using Nat.Web.Controls.GenerationClasses.Data;
using Nat.Web.Controls.GenerationClasses.Filter;
using Nat.Web.Controls.GenerationClasses.Navigator;
using Nat.Web.Controls.HistoryFilters;
using Nat.Web.Controls.Preview;
using Nat.Web.Tools;
using Nat.Web.Tools.Security;
using Nat.Web.Tools.WorkFlow;
using Nat.Web.Tools.Export;
using Nat.Web.WorkFlow;
using InformationValues = SampleDictionaries.MyProductsJournalDataSourceView.InformationValues;
using LookupValues = SampleDictionaries.MyProductsJournalDataSourceView.LookupValues;
using AccessOptions = SampleDictionaries.MyProductsAccessOptions;
using TotalInfo = SampleDictionaries.MyProductsJournalDataSourceView.TotalInfo;
using TableResources = SampleDictionaries.Properties.TableResources;

using Nat.Web.Tools.MailMessageContent;
using SampleDictionaries.Security;
using Nat.Web.Tools.ExtNet;
using Nat.Web.Tools.ExtNet.Extenders;
using Nat.Web.Tools.ExtNet.ExtNetConfig;
using Ext.Net;
using GridColumn = Nat.Web.Tools.ExtNet.GridColumn;
using GridButtonsColumn = Nat.Web.Tools.ExtNet.GridButtonsColumn;
using AdditionalButtons = Nat.Web.Controls.ExtNet.AdditionalButtons;
using BrowseFilterParameters = Nat.Web.Tools.ExtNet.ExtNetBrowseFilterParameters;

namespace SampleDictionaries.UserControls
{
    /// <summary>
    /// Контрол для отображения таблицы "Мои товары" (MyProducts)
    /// </summary>
    [DefaultEvent("SelectedIndexChanged")]
    [ControlValueProperty("SelectedValue")]
    public partial class MyProductsJournal : Nat.Web.Controls.ExtNet.Generation.AbstractUserControl<long>, IFilterSupport, IAccessControl, IPostBackEventHandler
    {
        public MyProductsJournal()
        {
            FilterControl = string.Empty;
            DefaultFilter = string.Empty;
            NeedMultipleSelect = false;
        }

        #region Fields
        
        private IFilterControl filterControl;
        private MyProductsFilter internalfilterControl;
        private bool isFilterSeted;
        private ISelectedValue parentControl;
        private bool inited;
        private long? selectedID = new long?();
        private DBDataContext _db;
        protected GridColumns _gridColumns;
        private List<IJournalLogic> _logics;
        private bool _selectedIndexChanged;
        private Dictionary<string, List<FilterItem>> _filterValues;
        private SelectModeMyProducts? select = null;
        private ViewModeMyProducts? viewMode = null;
        
        private bool storeLoadExecuted;
        
        #endregion
        
        #region Properties
        
        public bool NeedMultipleSelect { get; set; }
        public Type ParentControlTableType { get; set; }
        
        [DefaultValue("")]
        public string DefaultFilter { get; set; }
        
        [DefaultValue(null)]
        public string FilterByParentControl { get; set; }
        
        [DefaultValue(false)]
        public bool FilterByParentControlIfExistsValue { get; set; }
        
        [DefaultValue(null)]
        public string ParemeterNameParentControl { get; set; }
        
        [DefaultValue("")]
        [IDReferenceProperty]
        [TypeConverter(typeof(FilterConverter))]
        [Themeable(false)]
        public string FilterControl { get; set; }
        
        public override string Header
        {
            get { return ProjectHeader + " -&gt; " + TableHeader; }
        }
        
        public override string HeaderRu
        {
            get { return ProjectHeaderRu + " -&gt; " + TableHeaderRu; }
        }
        
        public override string HeaderKz
        {
            get { return ProjectHeaderKz + " -&gt; " + TableHeaderKz; }
        }
        
        partial void GetTableHeader(ref string header);
        
        public override string TableHeader
        {
            get
            {
                var header = MyProductsResources.Header;
                GetTableHeader(ref header);
                return header;
            }
        }
        
        public override string TableHeaderRu
        {
            get { return MyProductsResources.ResourceManager.GetString("Header", new CultureInfo("ru-ru")); }
        }
        
        public override string TableHeaderKz
        {
            get { return MyProductsResources.ResourceManager.GetString("Header", new CultureInfo("kk-kz")); }
        }
        
        public override string ProjectHeader
        {
            get { return MyProductsResources.ProjectHeader; }
        }
        
        public override string ProjectHeaderRu
        {
            get { return MyProductsResources.ResourceManager.GetString("ProjectHeader", new CultureInfo("ru-ru")); }
        }
        
        public override string ProjectHeaderKz
        {
            get { return MyProductsResources.ResourceManager.GetString("ProjectHeader", new CultureInfo("kk-kz")); }
        }
        
        public DBDataContext DB
        {
            get 
            {
                if (_db == null)
                {
                    _db = new DBDataContext(SpecificInstances.DbFactory.CreateConnection());
                }
        
                return _db;
            }
        }
        
        public override string TableName
        {
            get { return "MyProducts"; }
        }
        
        protected Dictionary<string, List<FilterItem>> FilterValues
        {
            get
            {
                if (_filterValues == null)
                    _filterValues = Url.GetFilterItemsDic("MyProducts");
                return _filterValues;
            }
        }
        
        
        internal IFilterControl FilterControlInternal
        {
            get 
            {
                if (Parent != null && filterControl == null)
                {
                    filterControl = (IFilterControl)Parent.FindControl(FilterControl);
                }
                return filterControl;
            }
        }
        
        [Browsable(false)]
        protected bool HasParentControl
        {
            get { return ParentControlInternal != null; }
        }
        
        internal ISelectedValue ParentControlInternal
        {
            get
            {
                if (Parent != null && parentControl == null)
                {
                    parentControl = (ISelectedValue)Parent.FindControl(ParentControl) ?? (ISelectedValue)this.FindControl(ParentControl);
                    GetParentControl(ref parentControl);
                }
                return parentControl;
            }
            set
            {
                parentControl = value;
            }
        }
        
        
        
        protected SelectModeMyProducts Select
        {
            get 
            {
                try
                {
                    if (select == null) select = (SelectModeMyProducts?)Enum.Parse(typeof(SelectModeMyProducts), Url.SelectMode ?? "none", true);
                }
                catch
                {
                    select = SelectModeMyProducts.none;
                }
                return select.Value;
            }
        }
        
        protected ViewModeMyProducts ViewMode
        {
            get 
            {
                try
                {
                    if (viewMode == null) viewMode = (ViewModeMyProducts?)Enum.Parse(typeof(ViewModeMyProducts), Url.ViewMode ?? "none", true);
                }
                catch
                {
                    viewMode = ViewModeMyProducts.none;
                }
                return viewMode.Value;
            }
        }
        private LogMonitor _logMonitor;
        protected LogMonitor LogMonitor
        {
            get
            {
                if(_logMonitor == null)
                {
                    _logMonitor = new LogMonitor();
                    _logMonitor.Init();
                }
                return _logMonitor;
            }
        }
        
        protected string StoreLoadHandler { get; set; }
        
        [Browsable(false)]
        public override long? SelectedValueKey
        {
            get 
            {
                throw new NotImplementedException();
            }
        }
        
        internal GridPanel Grid
        {
            get { return grid; }
        }
        
        public string DataSessionKey
        {
            get { return (string)ViewState["DataSessionKey"]; }
            set { ViewState["DataSessionKey"] = value; }
        }
        
        #region ISelectedValue Members
        
        [Browsable(false)]
        public override long SelectedValueLong
        {
            get 
            { 
                throw new NotImplementedException();
            }
        }
        
        public long? ParentID { get; set; }
        public bool IsSelectParentRows { get; set; }
        
        [Browsable(false)]
        public long? SelectedValueOrParentValue
        {
            get 
            {
                return SelectedValueKey;
            }
        }
        
        [Browsable(false)]
        public override object SelectedValue
        {
            get { return SelectedValueKey; }
        }
        
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden), Browsable(false)]
        public override DataKey SelectedDataKey
        {
            get 
            {
                throw new NotImplementedException();
            }
        }
        
        [DefaultValue("ID")]
        [Editor(
            "System.Web.UI.Design.WebControls.DataFieldEditor, System.Design, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
            , typeof(UITypeEditor))]
        [TypeConverter(typeof(StringArrayConverter))]
        [Category("Data")]
        public override string[] DataKeyNames
        {
            get 
            { 
                throw new NotImplementedException();
            }
        
            set
            { 
                throw new NotImplementedException();
            }
        }
        
        public override Type TableType
        {
            get { return typeof(MyProduct); }
        }
        
        #endregion
        
        #endregion
        
        #region Methods
        
        private List<IJournalLogic> GetLogics()
        {
            if (_logics == null)
                _logics = new List<IJournalLogic>(new IJournalLogic[] { new LocalizationColumnVisible() });
            return _logics;
        }
        
        protected IFilterControl GetFilterControl(DBDataContext db)
        {
            SetFilterText(string.Empty, FilterHidden.Text);
            InitializeSelectedValues();
            var filterControlInternal = (MyProductsFilter)FilterControlInternal ?? internalfilterControl;
            MainPageUrlBuilder pageUrlBuilder;
            if (filterControlInternal == null)
            {
                filterControlInternal = (MyProductsFilter)BaseMainPage.LoadControl(Page, GetDefaultFilterControl());
                pageUrlBuilder = Url.Clone();
                filterControlInternal.SetUrl(pageUrlBuilder);
                internalfilterControl = filterControlInternal;
            }
            else
                pageUrlBuilder = Url;
            filterControlInternal.SetDB(db);
            if (!FilterByParentControlIfExistsValue || ParentControlInternal.SelectedValue != null)
            {
                filterControlInternal.FilterByParentControl = FilterByParentControl;
                filterControlInternal.ParentControl = ParentControlInternal;
            }
            else
            {
                filterControlInternal.FilterByParentControl = null;
                filterControlInternal.ParentControl = null;
            }
            filterControlInternal.SelectedID = selectedID;
            filterControlInternal.ShowHistory = Url.ShowHistory;
            filterControlInternal.SelectedValues = SelectedValues;
            if (Url.GetFilter("MyProducts") == null && NavigatorControl.Values.MyProducts == null)
            {
                var defFilter = filterControlInternal.GetDefaultFilter();
                FilterHidden.Text = defFilter;
                Url.SetFilter("MyProducts", defFilter);
                pageUrlBuilder.SetFilter("MyProducts", defFilter);
                Url.CreateUrl();
                pageUrlBuilder.CreateUrl();
                filterControlInternal.SetUrl(pageUrlBuilder);
            }
            InitializeFilterControl(filterControlInternal);
            if (filterPlaceHolder.ContentControls.Count == 0 && Url.ShowFilter)
            {
                filterPlaceHolder.Visible = true;
                filterPlaceHolder.ContentControls.Add(filterControlInternal);
            }
        
            return filterControlInternal;
        }
        
        public string GetDefaultFilterControl()
        {
            return "MyProductsFilter";
        }
        
        private void InitColumnsInternal()
        {
            var isKZ = LocalizationHelper.IsCultureKZ;
            var columns = new List<GridColumn>();
            
            columns.Add(new GridColumn()
                            {
                                ColumnName = "__icons",
                                Visible = false,
                                
                                CanEdit = false,
                            });
            columns.Add(new GridButtonsColumn()
                            {
                                ColumnName = "__buttons",
                                EditUrl = "/EmptyPage.aspx/data/MyProductsEdit?refMyProducts={0}",
                                LookUrl = "/EmptyPage.aspx/data/MyProductsEdit/read?refMyProducts={0}",
                                EditVisible = AccessOptions.CheckPermitEdit(),
                                DeleteVisible = AccessOptions.CheckPermitDelete(),
                                CanEdit = false,
                                Width = "84px",
                            });
            
            var column_Name =
                new GridColumn()
                         {
                             Header = MyProductsResources.Name__Header,
                             Sort = "Name",
                             Group = MyProductsResources.Name__GridGroup,
                             ColumnName = "Name",
                         };
            column_Name.Width = string.Empty;
            column_Name.ModelFieldType = ModelFieldType.String;
            column_Name.DefaultHidden = false;
            column_Name.ServerMapping = "Item.Name";
            column_Name.HasFilter = true;
            columns.Add(column_Name);
            var column_CreationDate =
                new GridColumn()
                         {
                             Header = MyProductsResources.CreationDate__Header,
                             Sort = "CreationDate",
                             Group = MyProductsResources.CreationDate__GridGroup,
                             ColumnName = "CreationDate",
                             Format = "{0:d}",
                         };
            column_CreationDate.Width = string.Empty;
            column_CreationDate.ModelFieldType = ModelFieldType.Date;
            column_CreationDate.DefaultHidden = false;
            column_CreationDate.ServerMapping = "Item.CreationDate";
            column_CreationDate.HasFilter = true;
            columns.Add(column_CreationDate);
            var column_Price =
                new GridColumn()
                         {
                             Header = MyProductsResources.Price__Header,
                             Sort = "Price",
                             Group = MyProductsResources.Price__GridGroup,
                             ColumnName = "Price",
                         };
            column_Price.Width = string.Empty;
            column_Price.ModelFieldType = ModelFieldType.Float;
            column_Price.DefaultHidden = false;
            column_Price.ServerMapping = "Item.Price";
            column_Price.DecimalPrecision = 2;
            column_Price.HasFilter = true;
            columns.Add(column_Price);
            var column_Amount =
                new GridColumn()
                         {
                             Header = MyProductsResources.Amount__Header,
                             Sort = "Amount",
                             Group = MyProductsResources.Amount__GridGroup,
                             ColumnName = "Amount",
                         };
            column_Amount.Width = string.Empty;
            column_Amount.ModelFieldType = ModelFieldType.Float;
            column_Amount.DefaultHidden = false;
            column_Amount.ServerMapping = "Item.Amount";
            column_Amount.DecimalPrecision = 2;
            column_Amount.HasFilter = true;
            columns.Add(column_Amount);
            columns.Add(new GridColumn()
                            {
                                Header = TableResources.messages__Header,
                                ColumnName = "__messages",
                                Visible = false,
                                
                                CanEdit = false,
                            });
            InitColumns(columns);
        }
        
        
        partial void InitColumns(GridColumns gridColumns);
        
        protected void InitColumns(IEnumerable<GridColumn> columns)
        {
            _gridColumns = new GridColumns(columns);
            var baseGridColumns = (BaseGridColumns)_gridColumns;
            baseGridColumns.Page = Page;
            baseGridColumns.Control = this;
            _gridColumns.GenerateWithoutRow = false;
            
        
            foreach (var logic in GetLogics())
                logic.InitColumns(_gridColumns);
            InitColumns(_gridColumns);
            grid.InitializeColumns(_gridColumns, gridFilter);
            source.View.InitializeStoreModelAdditional(store.Model[0]);
            
        }
        
        private void DeleteRow(long id, MyProductsEdit.RecordEvents recordEvents, bool loadRoot)
        {
            var item = source.GetRecord(id);
            if (item != null)
            {
                var args = new RecordEventArgs();
                recordEvents.RecordDeleting(args, id);
        
                if (args.Cancel)
                {
                    AddErrorMessage(args.GetFullErrorMessage());
                    return;
                }
        
                if (!AccessOptions.CheckPermitDelete()
                    || (item.Information != null && !item.Information.CanDelete))
                {
                    AddErrorMessage(Nat.Web.Controls.Properties.Resources.ENoPermitToDeleteRecord);
                    return;
                }
        
                if (!item.CanDelete)
                {
                    var messages = source.View.GetDeleteErrors(id, MyProductsResources.Header);
                    if (messages.All(string.IsNullOrEmpty))
                        AddErrorMessage(Nat.Web.Controls.Properties.Resources.ENoPermitToDeleteRecord);
                    else
                        AddErrorMessage(messages.Where(r => !string.IsNullOrEmpty(r)));
                    return;
                }
        
        
                BeforeDelete(item);
                var contextInfo = new DeleteRowContext<MyProduct, DBDataContext, MyProductsJournalDataSourceView.Row, long>
                    {
                        Row = item,
                        Key = item.id,
                        TableItem = item.Item,
                        DB = source.View.DB,
                    };
                BeforeDelete(contextInfo);
                if (contextInfo.Cancel)
                {
                    AfterDelete(false, item);
                    AddErrorMessage(contextInfo.CancelMessage);
                    return;
                }
        
                try
                {
                    var delArgs = new DeleteEventArgs<long>();
                    contextInfo.DeleteEventArgs = delArgs;
                    if (contextInfo.SuccessfullRowDeleted != null && !contextInfo.SuccessfullRowDeleted.Value)
                    {
                        AfterDelete(false, item);
                        AddErrorMessage(contextInfo.FailedRowDeletedMessage);
                        return;
                    }
                    
                    if (!delArgs.IsDeleted)
                        DeleteRow(item, delArgs);
        
                    if (!delArgs.IsDeleted)
                    {
                        source.View.DB.MyProducts.DeleteOnSubmit(item.Item);
                        source.View.DB.SubmitChanges();
                    }
        
                    contextInfo.SuccessfullRowDeleted = true;
                    AfterDelete(true, item);          
                    if (delArgs.IsDeleted)
                    {
                        if (delArgs.NewSelectedValue != null)
                        {
                            ResetSelectedIndex(delArgs.NewSelectedValue.Value);
                        }
                        else
                            EmptySelectedIndex();
                    }
                }
                catch (SqlException exception)
                {
                    
                    contextInfo.SuccessfullRowDeleted = false;
                    AfterDelete(false, item);
                    if (exception.Number != 547)
                        AddErrorMessage(exception.ToString());
                    else
                        AddErrorMessage(Nat.Web.Controls.Properties.Resources.ECanNotDeleteUseInSystem);
                }
        
                store.Reload();
                OnSelectedIndexChanged(EventArgs.Empty);
            }
        }
        
        public static MainPageUrlBuilder FromUrl(string url)
        {
            var builder = MainPageUrlBuilder.FromUrlToOtherControl(url);
            builder.UserControl = "MyProductsJournal";
            return builder;
        }
        
        public static string GetUserControlName()
        {
            return "MyProductsJournal";
        }
        
        bool IAccessControl.CheckPermit(Page page)
        {
            return AccessOptions.CheckPermit();
        }
        
        private void InitializeSelectedValues()
        {
        }
        
        private void EmptySelectedIndex()
        {
        }
        
        private void ResetSelectedIndex(long id)
        {
        }
        
        private void GenerateHtmlAdditionalButtonsInternal()
        {
            var toolbar = grid.BottomBar.First();
            Action<AbstractComponent> addButton = commponent => toolbar.Items.Add(commponent);
            Action<AbstractComponent, AbstractComponent> insertAfterButton = (commponent, after) => toolbar.Items.Insert(toolbar.Items.IndexOf(after) + 1, commponent);
            var buttons = new AdditionalButtons(addButton, insertAfterButton);
            GenerateAdditionalButtons(buttons);
        }
        
        protected List<long> GetGridSelectedValues()
        {
            var sm = (RowSelectionModel)grid.GetSelectionModel();
            return sm.SelectedRows.Where(r => !string.IsNullOrEmpty(r.RecordID)).Select(r => Convert.ToInt64(r.RecordID)).ToList();
        }
        
        void IPostBackEventHandler.RaisePostBackEvent(string eventArgument)
        {
            AdditionalButton_Click(eventArgument);
        }
        
        private void InitGetBrowseFilterParameters()
        {
            ExtNetBrowseFilterParameters param;
        }
        
        private void InitSelectionMode()
        {
            topGridToolBar.Visible = Url.IsMultipleSelect;
            SelectionOK.Visible = Url.IsMultipleSelect;
            SelectionCancel.Visible = Url.IsMultipleSelect;
            selectedUserValues.Visible = Url.IsMultipleSelect;
        }
        
        protected string GetUpdateFilterSctiptFunctionName()
        {
            return "UpdateFilter_" + ClientID.Replace(".", "_");
        }
        
        protected string GetValueFilterSctiptFunctionName()
        {
            return "GetFilter_" + ClientID.Replace(".", "_");
        }
        
        #endregion
        
        #region Direct Methods
        
        [DirectMethod]
        public void DeleteRow(string strKey)
        {
            long id = Convert.ToInt64(strKey);
            var recordEvents = new MyProductsEdit.RecordEvents { Page = Page, Control = this, };
            recordEvents.InitializeValues(NavigatorControl.Values);
        
            DeleteRow(id, recordEvents, false);
        }
        
        
        
        [DirectMethod]
        public long GetPageNumber(string strKey, DataSorter[] sorts, int pageSize)
        {
            long id = Convert.ToInt64(strKey);
            var sort = BaseDataSourceViewExtender.GetSortExpression(_gridColumns, sorts);
            if (string.IsNullOrEmpty(sort))
                sort = "Name,id";
            var where = "id=" + id;
        
            var rowIndex = GetRowIndex(source.View.GetSelect(null, null, LocalizationHelper.IsCultureKZ, true), source.View.DB, sort, @where);
            if (rowIndex == null)
                return 0;
        
            return (rowIndex.Value / pageSize) + 1;
        }
        
        #endregion
        
        #region Overrides
        
        protected override IWorkFlow[] CreateWorkFlows()
        {
            return new IWorkFlow[] {};
        }
        
        public override Expression GetExpression(string reference, Expression param)
        {
            if (_selectedIndexChanged) store.Reload();
            if (SelectedValueOrParentValue == null) return Expression.Constant(false);
            foreach (var property in reference.Split('.'))
                if (!property.Equals("id", StringComparison.OrdinalIgnoreCase))
                    param = Expression.Property(param, property);
            return Expression.Equal(Expression.Property(param, "id"), Expression.Constant(SelectedValueOrParentValue, typeof(long)));
        }
        
        public override Expression GetExpression(string reference, Expression param, QueryParameters qParams)
        {
            if (qParams == null) return GetExpression(reference, param);
            if (_selectedIndexChanged) store.Reload();
            if (SelectedValueOrParentValue == null) return qParams.GetExpression("Empty", false);
            foreach (var property in reference.Split('.'))
                if (!property.Equals("id", StringComparison.OrdinalIgnoreCase))
                    param = Expression.Property(param, property);
            return Expression.Equal(Expression.Property(param, "id"), qParams.GetExpression(reference, (long)SelectedValueOrParentValue));
        }
        
        protected override void OnLoad(EventArgs e)
        {
            GetFilterControl(DB);//Initialize
            this.Page.LoadComplete += new EventHandler(Page_LoadComplete);
            if (!IsPostBack && Url.QueryParameters.ContainsKey(MyProductsFilter.ConstOfColumnNames.RefTable))
                SelectIDHidden.Value = Url.QueryParameters[MyProductsFilter.ConstOfColumnNames.RefTable];
        
            var filter = (MyProductsFilter)FilterControlInternal ?? internalfilterControl;
            if (filter != null)
            {
                GridFilterHidden.Text = GridFiltersExtender.GetFilterValuesFromRequest(gridFilter.ParamPrefix, GridFilterHidden.Text);
                filter.InitializeFilterFunction(GetUpdateFilterSctiptFunctionName(), GetValueFilterSctiptFunctionName());
                gridFilter.SetGridFilters<long, MyProduct, DBDataContext, MyProductsJournalDataSourceView.Row>(GridFilterHidden.Text, filter, _gridColumns);
            }
        
            
        
            OnLoad();
            base.OnLoad(e);
        }
        
        protected override void OnInit(EventArgs e)
        {
            base.OnInit(e);
            OnInit();
            InitColumnsInternal();
            inited = true;
        
            grid.InitializeSelectMode(Url, StoreLoadHandler);
            GenerateHtmlAdditionalButtonsInternal();
        }
        
        protected override void OnPreRender(EventArgs e)
        {
            var visibleAddLink = AccessOptions.CheckPermitAdd();
            if (NavigatorControl != null)
                visibleAddLink = visibleAddLink && source.View.AllowAddRowForTableTypes(NavigatorControl.Values, MyProductsResources.Header).Where(r => string.IsNullOrEmpty(r)).Count() == 0;
            if (visibleAddLink)
                SetVisibleAddLink(ref visibleAddLink);
        
            AddButton.Visible = visibleAddLink;
            DeleteSelectedButton.Visible = AccessOptions.CheckPermitDelete();
            if (visibleAddLink)
            {
                var addUrl = Url.Clone("MyProductsEdit", true, string.Empty, false).CreateUrl();
                GetAddUrl(ref addUrl);
                AddButton.Listeners.Click.Handler = GridButtonsColumn.AddButtonHandler(addUrl);
            }
        
            InitGetBrowseFilterParameters();
            InitSelectionMode();
        
            OnPreRender();
            base.OnPreRender(e);
        }
        
        #endregion
        
        #region Events
        
        public event EventHandler CurrentEditing;
        public event EventHandler NewRecordAdding;
        
        protected virtual void OnCurrentEditing(EventArgs args)
        {
            if (CurrentEditing != null) CurrentEditing(this, args);
        }
        
        protected virtual void OnNewRecordAdding(EventArgs args)
        {
            if (NewRecordAdding != null) NewRecordAdding(this, args);
        }
        
        protected void FilterControl_OnFilterApply(object sender, EventArgs e)
        {
            isFilterSeted = false;
            EmptySelectedIndex();
            ((MyProductsFilter)FilterControlInternal).SelectedValues = SelectedValues;
            store.Reload();
            OnSelectedIndexChanged(EventArgs.Empty);
        }
        
        private void ParentControl_OnSelectedIndexChanged(object sender, EventArgs e)
        {
            isFilterSeted = false;
            if (!Url.QueryParameters.ContainsKey("refMyProducts") || string.IsNullOrEmpty(Url.QueryParameters["refMyProducts"]))
                EmptySelectedIndex();
            else
            {
                var value = Url.QueryParameters["refMyProducts"];
                ResetSelectedIndex(Convert.ToInt64(value));
            }
            store.Reload();
        }
        
        protected void Source_Selecting(object sender, DataSourceSelectingEventArgs e)
        {
            e.FilterControl = GetFilterControl((DBDataContext)e.DB);
        }
        
        protected void NavigatorControl_ValuesInitialized(object sender, EventArgs e)
        {
            if (HasParentControl && ParentControlTableType != null)
            {
                if (ParentControlInternal.SelectedValue != null)
                {
                    NavigatorControl.Values[ParentControlTableType] = ParentControlInternal.SelectedValue;
                    //Url.QueryParameters[FilterByParentControl] = ParentControlInternal.SelectedValue.ToString();
                }
            }
            NavigatorControl.Url = Url;
        }
        
        partial void OnReadData(StoreReadDataEventArgs e, ref bool cancel);
        
        protected void OnReadData(object sender, StoreReadDataEventArgs e)
        {
            bool cancel = false;
            OnReadData(e, ref cancel);
            if (cancel) return;
            if (string.IsNullOrEmpty(DataSessionKey))
                grid.ReadData(source.View, e, (MyProductsFilter)this.GetFilterControl(DB), gridFilter, _gridColumns);
            else
            {
                if (!string.IsNullOrEmpty(store.DataSourceID))
                    store.DataSourceID = null;
                store.DataSource = Session[DataSessionKey];
            }
        }
        
        private void Page_LoadComplete(object sender, EventArgs e)
        {
        }
        
        protected void DeleteSelected(object sender, DirectEventArgs e)
        {
            var sm = (RowSelectionModel)grid.GetSelectionModel();
            foreach (var item in sm.SelectedRows.Where(r => string.IsNullOrEmpty(r.RecordID)).Reverse())
                store.RemoveAt(item.RowIndex);
        
            foreach (var id in GetGridSelectedValues())
            {
                var recordEvents = new MyProductsEdit.RecordEvents { Page = Page, Control = this, };
                recordEvents.InitializeValues(NavigatorControl.Values);
        
                DeleteRow(id, recordEvents, true);
            }
        }
        
        #endregion
        
        #region Partials
        
        partial void GetParentControl(ref ISelectedValue control);
        partial void GenerateAdditionalButtons(AdditionalButtons buttons);
        partial void SetVisibleAddLink(ref bool visible);
        partial void InitializeFilterControl(IFilterControl filterControl);
        partial void OnPreRender();
        partial void OnLoad();
        partial void Render();
        partial void BeforeDelete(MyProductsJournalDataSourceView.Row row);
        partial void BeforeDelete(DeleteRowContext<MyProduct, DBDataContext, MyProductsJournalDataSourceView.Row, long> context);
        partial void DeleteRow(MyProductsJournalDataSourceView.Row item, DeleteEventArgs<long> delArgs);
        partial void AfterDelete(bool isDeleted, MyProductsJournalDataSourceView.Row row);
        partial void ChangeLogTypeDelete(ref LogMessageType logType);
        partial void ChangeLogTypeLookJournal(ref LogMessageType logType);
        partial void ChangeLogTypeDelete(ref long logType);
        partial void ChangeLogTypeLookJournal(ref long logType);
        partial void ChangeLogContent(ref string content, MyProductsJournalDataSourceView.Row deleteRow);
        partial void ChangeLogContentDelete(ref string content, MyProductsJournalDataSourceView.Row deleteRow);
        partial void ChangeLogContentLookJournal(ref string content);
        
        partial void OnInit();
        partial void GetAddUrl(ref string url);
        partial void AdditionalButton_Click(string argument);
        partial void AfterSave(IEnumerable<long> keys);
        partial void BeforeSaveValidate(List<MyProduct> modifiedAgreementers, ref bool isValid);
        
        #endregion
        
        #region Inner Classes
        
        public class GridColumns : BaseGridColumns
        {
            public GridColumns(IEnumerable<GridColumn> columns) : base(columns)
            {
            }
        
            public GridColumn __messages
            {
                get { return (GridColumn)this["__messages"]; }
            }
        
            public GridButtonsColumn __buttons
            {
                get { return (GridButtonsColumn)this["__buttons"]; }
            }
        
            public GridColumn __icons
            {
                get { return (GridColumn)this["__icons"]; }
            }
        
            /// <summary>
            /// Колонка "Наименование".
            /// </summary>
            public GridColumn Name
            {
                get { return (GridColumn)this["Name"]; }
            }
        
            /// <summary>
            /// Индекс колонки "Наименование".
            /// </summary>
            public int IndexOfName()
            {
                return Columns.IndexOf(this["Name"]);
            }
        
            /// <summary>
            /// Колонка "Дата создания".
            /// </summary>
            public GridColumn CreationDate
            {
                get { return (GridColumn)this["CreationDate"]; }
            }
        
            /// <summary>
            /// Индекс колонки "Дата создания".
            /// </summary>
            public int IndexOfCreationDate()
            {
                return Columns.IndexOf(this["CreationDate"]);
            }
        
            /// <summary>
            /// Колонка "Цена".
            /// </summary>
            public GridColumn Price
            {
                get { return (GridColumn)this["Price"]; }
            }
        
            /// <summary>
            /// Индекс колонки "Цена".
            /// </summary>
            public int IndexOfPrice()
            {
                return Columns.IndexOf(this["Price"]);
            }
        
            /// <summary>
            /// Колонка "Доступно".
            /// </summary>
            public GridColumn Amount
            {
                get { return (GridColumn)this["Amount"]; }
            }
        
            /// <summary>
            /// Индекс колонки "Доступно".
            /// </summary>
            public int IndexOfAmount()
            {
                return Columns.IndexOf(this["Amount"]);
            }
        }
        
        #endregion
    }
}
#pragma warning restore