/*
 * Generated by: Sergey.Shpakovskiy
 * Generated at: 1.0.0.2
 * Copyright © JSC NAT Kazakhstan 2011
 */
#pragma warning disable
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Linq;
using System.Linq;
using System.Linq.Expressions;
using System.Security.Principal;
using System.Text;
using System.Xml.Linq;
using System.Web;
using System.Web.Compilation;
using System.Web.Script.Serialization;
using System.Web.UI;
using System.Web.UI.WebControls;
using SampleDictionaries.Properties;

using Microsoft.JScript;

using Nat.Tools.Specific;
using Nat.Web.Controls;
using Nat.Web.Controls.GenerationClasses;
using Nat.Web.Controls.GenerationClasses.BaseJournal;
using Nat.Web.Controls.GenerationClasses.Data;
using Nat.Web.Controls.GenerationClasses.Filter;
using Nat.Web.Controls.GenerationClasses.Navigator;
using Nat.Web.Controls.HistoryFilters;
using Nat.Web.Controls.Preview;
using Nat.Web.Tools;
using Nat.Web.Tools.Security;
using Nat.Web.Tools.WorkFlow;
using Nat.Web.WorkFlow.Data;
using Filter = Nat.Web.Controls.GenerationClasses.FilterHtmlGenerator.Filter;
using AccessOptions = SampleDictionaries.MyProductActionsAccessOptions;
using TableResources = SampleDictionaries.Properties.TableResources;
using Convert=System.Convert;
using SampleDictionaries.Security;
using SampleDictionaries;
using SampleDictionaries.UserControls;
using SampleDictionaries.Properties;
using Nat.Web.Controls.ExtNet.Generation.Filter;
using Nat.Web.Tools.ExtNet.ExtNetConfig;
using BrowseFilterParameters = Nat.Web.Tools.ExtNet.ExtNetBrowseFilterParameters;

namespace SampleDictionaries.UserControls
{
    public enum SelectModeMyProductActions
    {
        none,    }

    /// <summary>
    /// Класс для работы с фильтрами таблицы "Поступления/продажи товаров" (MyProductActions)
    /// </summary>
    public partial class MyProductActionsFilter : BaseFilterControl<long, MyProductAction, DBDataContext>, IAccessControl, IPostBackEventHandler
    {
        private readonly IEnumerable<IFilterProvider> filterProviders = new IFilterProvider[]{};
        private Dictionary<string, List<FilterItem>> filterValues;
        private IList<Filter> _filters;
        private IDictionary<string, Filter> _filterHandlers;
        private DBDataContext _db;
        private SelectModeMyProductActions? _select;
        private bool _filterInitialized;
        private bool _customFiltersInitialized;
        private string setFilterToGrid;
        private string getFilterFromGrid;
        
        protected bool FilterPanelCollapsed { get; set; }

        private BaseFilterEventArgs<MyProductAction> _cachedFilterArgs;
        private BaseFilterEventArgs<MyProductAction, DBDataContext> _cachedFilterOfParentsArgs;
        private BaseFilterEventArgs<MyProductAction, DBDataContext> _cachedFilterOfChildsArgs;
        private MyProductsFilter _cachedMyProductsFilterControl;
        

        public MyProductActionsFilter()
        {
            Header = TableResources.Project__Header + " -&gt; " + MyProductActionsResources.Header;

        }

        public static MyProductActionsFilter CreateDefault(MainPageUrlBuilder url, DBDataContext db)
        {
            var filter = new MyProductActionsFilter();
            var newUrl = url ?? new MainPageUrlBuilder();
            newUrl.SelectMode = "none";
            newUrl.ViewMode = "none";
            filter.SetUrl(newUrl);
            filter.SetDB(db);
            return filter;
        }

        public static MyProductActionsFilter CreateDefault(MainPageUrlBuilder url, DBDataContext db, bool showHistory)
        {
            var filter = new MyProductActionsFilter();
            var newUrl = url != null ? url.Clone() : new MainPageUrlBuilder();
            newUrl.ShowHistory = showHistory;
            newUrl.SelectMode = "none";
            newUrl.ViewMode = "none";
            filter.SetUrl(newUrl);
            filter.SetDB(db);
            filter.ShowHistory = showHistory;
            return filter;
        }

        public static MyProductActionsFilter CreateDefault(MainPageUrlBuilder url, DBDataContext db, bool showHistory, List<MainPageUrlBuilder.FilterParameter> controlFilterParameters)
        {
            var filter = new MyProductActionsFilter();
            var newUrl = url != null ? url.Clone() : new MainPageUrlBuilder();
            newUrl.ShowHistory = showHistory;
            newUrl.SelectMode = "none";
            newUrl.ViewMode = "none";
            foreach (var item in controlFilterParameters)
                newUrl.ControlFilterParameters.Add(item.Clone());
            filter.SetUrl(newUrl);
            filter.SetDB(db);
            filter.ShowHistory = showHistory;
            return filter;
        }

        protected DBDataContext DB
        {
            get 
            {
                if (_db == null)
                {
                    _db = new DBDataContext(SpecificInstances.DbFactory.CreateConnection());
                }

                return _db;
            }
        }

        protected SelectModeMyProductActions Select
        {
            get 
            {
                try
                {
                    if (_select == null) _select = (SelectModeMyProductActions?)Enum.Parse(typeof(SelectModeMyProductActions), Url.SelectMode, true);
                }
                catch
                {
                    _select = SelectModeMyProductActions.none;
                }
                return _select.Value;
            }
        }

        protected string FilterClick
        {
            get
            {
                if (Url.IsFilterWindow)
                    return HttpUtility.HtmlAttributeEncode("ApplyFilter($get('filterMyProductActions')); return false;");

                var getArgumentsScript = string.IsNullOrEmpty(PostBackFilterArguments)
                                             ? string.Empty
                                             : "'" + PostBackFilterArguments + "' + ";
                getArgumentsScript += "GetSerializedFilters($get('filterMyProductActions'))";
                var postback = Page.ClientScript.GetPostBackEventReference(PostBackFilterControl, "{0}")
                                   .Replace("'{0}'", getArgumentsScript);
                var onclick = postback + "; return false;";
                return HttpUtility.HtmlAttributeEncode(onclick);
            }
        }

        public override BaseFilter<long, MyProductAction> CustomFilter
        {
            get { return base.CustomFilter; }

            set
            {
                base.CustomFilter = value;
                if (value != null && _filterInitialized && !_customFiltersInitialized)
                {
                    _customFiltersInitialized = true;
                    InitializeCustomFilters(_filters);
                    
                    _filterHandlers = _filters
                        .Union(_filters.SelectMany(r => r.AllChildren))
                        .Where(p => p.FilterHandler != null)
                        .ToDictionary(p => LinqFilterGenerator.GetFilterName(p.FilterName));
                }
            }
        }

        public override string GetTableName()
        {
            return "MyProductActions";
        }

        public override long? SelectedID { get; set; }

        //partial void SetFilters(ref IQueryable<MyProductAction> data);
        partial void SetFilter(BaseFilterEventArgs<MyProductAction> filterArgs);
        partial void SetFilter(BaseFilterEventArgs<MyProductAction, DBDataContext> filterArgs);
        partial void SetDefaultFilter(DefaultFilters defaultFilters);
        partial void FilterInitialize(IList<Filter> filters);
        partial void GetBrowseFilterParameters(string fieldName, BrowseFilterParameters parameters);
        partial void GetBrowseFilterParameters_refProduct(BrowseFilterParameters parameters);


        public override BaseFilterEventArgs<MyProductAction> GetFilter(Type typeOfData)
        {
            var filterArgs = _cachedFilterArgs;
            if (filterArgs == null || _cachedFilterArgs.QueryParameters != QueryParameters)
            {
                filterArgs = base.GetFilter(typeOfData);
                var filterArgs2 = (BaseFilterEventArgs<MyProductAction, DBDataContext>)filterArgs;
                SetFilter(filterArgs2);
                SetFilter(filterArgs);
                if (!filterArgs.DenyCache)
                    _cachedFilterArgs = filterArgs;
            }
            return filterArgs;
        }

        partial void FilterDataByParentExtend<T>(
            ref Expression source,
            ParameterExpression param,
            Expression upToTable,
            IEnumerable<Expression> fieldsToCheckReference);

        public override Expression FilterDataByParents<T>(Expression source, ParameterExpression param, Expression upToTable, IEnumerable<Expression> fieldsToCheckReference)
        {
            var refProductControl = _cachedMyProductsFilterControl;
            if (refProductControl == null)
                refProductControl = _cachedMyProductsFilterControl = MyProductsFilter.CreateDefault(null, DB, ShowHistory || SelectedID != null, Url.ControlFilterParameters);
            var refProductToTable = Expression.Property(upToTable, "MyProduct_refProduct");
            var refProductToCheckReference = new List<Expression>(fieldsToCheckReference);
            refProductControl.SetUrl(Url);
            source = refProductControl.FilterData<T>(source, QueryParameters, refProductToTable, param, refProductToCheckReference, true);
            FilterDataByParentExtend<T>(ref source, param, upToTable, fieldsToCheckReference);
            return source;
        }


        protected override IDictionary<string, Filter> GetFilterHandlers()
        {
            if (_filterHandlers == null)
                FilterInitialize();
            return _filterHandlers;
        }
        
        internal ICollection<Filter> GetFiltersInternal()
        {
            return GetFilterHandlers().Values;
        }

        protected override Dictionary<string, string[]> GetFilterValues()
        {
            return null;
        }

        protected override Dictionary<string, List<FilterItem>> GetFilterItems()
        {
            ParseFilterParameters();
            return filterValues;
        }

        protected override BaseNavigatorControl GetNavigatorControl()
        {
            if (NavigatorControl == null)
                NavigatorControl = new MyProductActionsNavigatorControl { Url = Url };
            return NavigatorControl;
        }

        public override IQueryable SetFilters(IQueryable query)
        {
            FilterInitialize();
            foreach (var provider in filterProviders)
            {
                provider.IsSelect = true;
                provider.Url = Url;
                provider.ProjectName = "SampleDictionaries";
                provider.Init(typeof(MyProductAction));
                provider.SetFilters(ref query);
            }
            var filter = (IQueryable<MyProductAction>)query;
            //SetFilters(ref filter);
            query = filter;
            var enumerable = FilterByCustomExpressions((IQueryable<MyProductAction>)query);
            enumerable = FilterData(enumerable);

            if (ParentControl != null)
            {
                var param = Expression.Parameter(typeof(MyProductAction), "r");
                var filterExp = ParentControl.GetExpression(FilterByParentControl, param);
                if (filterExp != null)
                {
                    Expression pred = Expression.Lambda(filterExp, param);
                    Expression expr = Expression.Call(typeof(Queryable), "Where", new[] { typeof(MyProductAction) }, enumerable.Expression, pred);
                    enumerable = (IQueryable<MyProductAction>)enumerable.Provider.CreateQuery(expr);
                }
                else
                {
                    string filterValue;
                    filterValue = ParentControl.SelectedValue == null
                                      ? "0"
                                      : ParentControl.SelectedValueLong.ToString();
                    enumerable = (IQueryable<MyProductAction>)
                                 LinqFilterGenerator.GenerateFilter(enumerable,
                                                                    typeof (MyProductAction),
                                                                    "Equal",
                                                                    FilterByParentControl,
                                                                    filterValue,
                                                                    null);
                }
            }

            IQueryable queryable = enumerable;
            if (ParentControl == null)
            {
                if (NavigatorControl == null)
                    NavigatorControl = new MyProductActionsNavigatorControl { Url = Url };
                queryable = NavigatorControl.FilterData(queryable);
                if (Url.UserControl != null && Url.UserControl.StartsWith("MyProductActions"))
                {
                    foreach (var queryParameter in Url.QueryParameters)
                    {
                        if (queryParameter.Key.Contains(".") && !string.IsNullOrEmpty(queryParameter.Value) && !queryParameter.Key.EndsWith(".id"))
                        {
                            queryable = LinqFilterGenerator.GenerateFilter(queryable, typeof (MyProductAction), "Equal",
                                                                           queryParameter.Key, queryParameter.Value, null);
                        }
                    }
                }
            }
            return (IQueryable<MyProductAction>)queryable;
        }
        
        public override void SetUrl(MainPageUrlBuilder url)
        {
            base.SetUrl(url);
            ParseFilterParameters();
        }

        private void ParseFilterParameters()
        {
            filterValues = Url.GetFilterItemsDic(GetFilterTableName());
        }
        
        public override void ReParseFilterParameters()
        {
            ParseFilterParameters();
        }

        protected override void SetDefaultFilterIntranal(DefaultFilters defaultFilters)
        {
            SetDefaultFilter(defaultFilters);
            base.SetDefaultFilterIntranal(defaultFilters);
        }

        public override void SetDB(DataContext db)
        {
            this._db = (DBDataContext)db;
        }

        protected override void OnInit(EventArgs e)
        {
            base.OnInit(e);
            FilterInitialize();
        }
        
        protected override void OnLoad(EventArgs e)
        {
            base.OnLoad(e);
            if (Url.IsFilterWindow && !Page.IsPostBack)
                ParseFilterParameters();
        }

        protected override void OnPreRender(EventArgs e)
        {
            FilterControlGenerator.PackingFilter(this, _filters, getFilterFromGrid, setFilterToGrid, FilterPanelCollapsed);
        
            base.OnPreRender(e);
        }
        
        internal void InitializeFilterFunction(string setFilterToGrid, string getFilterFromGrid)
        {
            this.setFilterToGrid = setFilterToGrid;
            this.getFilterFromGrid = getFilterFromGrid;
        }

        public void RaisePostBackEvent(string eventArgument)
        {
            string component = GlobalObject.decodeURIComponent(eventArgument);
            Url.SetFilter(GetFilterTableName(), component);
            if (Url != MainPageUrlBuilder.Current)
                MainPageUrlBuilder.Current.SetFilter(component, GetFilterTableName());
            MainPageUrlBuilder.ChangedUrl();
            filterValues = MainPageUrlBuilder.GetFilterItemsDicByFilterContent(component);
            OnFilterApply(EventArgs.Empty);
            var updatePanel = ControlHelper.FindControl<UpdatePanel>(this);
            if (updatePanel != null) updatePanel.Update();
        }
        
        protected override IWorkFlow[] CreateWorkFlows()
        {
            return new IWorkFlow[] {};
        }

        protected override void FilterInitialize()
        {
            if (_filterInitialized) return;
            _filterInitialized = true;
            
            _filters = (IList<Filter>)HttpContext.Current.Items["MyProductActions.FiltersCache"];
            if (Page == null && _filters != null)
            {
                _filterHandlers = _filters.
                    Union(_filters.SelectMany(r => r.AllChildren)).
                    Where(p => p.FilterHandler != null).
                    ToDictionary(p => LinqFilterGenerator.GetFilterName(p.FilterName));
                return;
            }
            
            BrowseFilterParameters parameters;
            IList<Filter> filters = new List<Filter>();
            var stack = new Stack<IList<Filter>>();
            _filters = filters;
            Filter current;
            BaseFilterParameter currentBF = null;
            
            
            
            
            parameters = new BrowseFilterParameters();
            GetBrowseFilterParameters_refProduct(parameters);
            //колонка 'Мой товар'
            current = currentBF = new BaseFilterParameter<MyProductAction, Int64>(r => r.refProduct,
                                      r => r.MyProduct_refProduct.Name,
                                      r => r.MyProduct_refProduct.Name)
                {
                    FilterName = "refProduct", 
                    Header = MyProductActionsResources.refProduct__Header,
                    IsJournalFilter = true,
                    Mandatory = true,
                    Type = FilterHtmlGenerator.FilterType.Reference,
                    ProjectName = "SampleDictionaries",
                    TableName = "MyProducts",
                    Lookup = true, 
                    MinimumPrefixLength = 1, 
                    Width = "98%", 
                    SelectMode = "none",
                    IsMultipleSelect = true,
                    BrowseFilterParameters = parameters,
                };
            currentBF.AddFilter(filters);
            //filters.Add(current);
            
            
            
            
            
            //колонка 'Дата/время действия'
            current = currentBF = new BaseFilterParameter<MyProductAction, DateTime>(r => r.DateTimeAction)
                {
                    FilterName = "DateTimeAction", 
                    Header = MyProductActionsResources.DateTimeAction__Header,
                    IsJournalFilter = true,
                    Mandatory = true,
                    Type = FilterHtmlGenerator.FilterType.Numeric, 
                    IsDateTime = true,
                };
            currentBF.AddFilter(filters);
            //filters.Add(current);
            
            
            
            
            
            //колонка 'Изменение кол-ва'
            current = currentBF = new BaseFilterParameter<MyProductAction, Decimal>(r => r.AmountChange)
                {
                    FilterName = "AmountChange", 
                    Header = MyProductActionsResources.AmountChange__Header,
                    IsJournalFilter = true,
                    Mandatory = true,
                    Type = FilterHtmlGenerator.FilterType.Numeric, 
                    DecimalPrecision = 2,
                    MaxLength = 8,
                            Columns = 8,
                };
            currentBF.AddFilter(filters);
            //filters.Add(current);
            
            
            
            
            
            //колонка 'Примечание'
            current = currentBF = new BaseFilterParameterString<MyProductAction>(r => r.Note)
                {
                    FilterName = "Note", 
                    Header = MyProductActionsResources.Note__Header,
                    IsJournalFilter = true,
                    Mandatory = false,
                    Type = FilterHtmlGenerator.FilterType.Text, 
                    MaxLength = 500,
                            Width = "98%",
                };
            currentBF.AddFilter(filters);
            //filters.Add(current);
            
            
            
            
            if(Url.IsMultipleSelect)
            {
                current = new Filter
                              {
                                  FilterName = MultipleSelectedValues,
                                  Header = TableResources.MultipleSelectedFilterHeader,
                                  Type = FilterHtmlGenerator.FilterType.Boolean,
                                  TrueBooleanText = TableResources.MultipleSelectedFilterSelected,
                                  FalseBooleanText = TableResources.MultipleSelectedFilterNotSelected,
                                  Mandatory = true,
                                  FilterHandler =
                                      delegate(IQueryable enumerable, Enum type, string value1, string value2)
                                          {
                                              throw new Exception("Is not actual delegate");
                                          },
                              };
                filters.Add(current);
            }
            
            AddSearchFilter(filters);
            SetDefaultFilterType(filters);
            FilterInitialize(filters);
            if (CustomFilter != null && !_customFiltersInitialized)
            {
                _customFiltersInitialized = true;
                InitializeCustomFilters(filters);
            }
            
            _filterHandlers = filters.
                Union(filters.SelectMany(r => r.AllChildren)).
                Where(p => p.FilterHandler != null).
                ToDictionary(p => LinqFilterGenerator.GetFilterName(p.FilterName));
            HttpContext.Current.Items["MyProductActions.FiltersCache"] = filters;
        }
        
        private void AddSearchFilter(IList<Filter> filters)
        {
        }

        protected override object SaveViewState()
        {
            return new Pair(filterValues, base.SaveViewState());
        }

        protected override void LoadViewState(object savedState)
        {
            Pair pair = savedState as Pair;
            if (pair != null)
            {
                filterValues = (Dictionary<string, List<FilterItem>>)pair.First;
                base.LoadViewState(pair.Second);
            }
            else
                base.LoadViewState(null);
        }
 
        
        
        public class ConstOfColumnNames
        {
            /// <summary>
            /// Наименование группы валидации
            /// </summary>
            public const string VALIDATION_GROUP = "MyProductActions";
        
            /// <summary>
            /// Наименование таблицы
            /// </summary>
            public const string TABLE_NAME = "MyProductActions";
        
            /// <summary>
            /// Наименование формы журнала
            /// </summary>
            public const string JournalName = "MyProductActionsJournal";
        
            /// <summary>
            /// Наименование формы редактирования
            /// </summary>
            public const string EditName = "MyProductActionsEdit";
        
            /// <summary>
            /// Наименование формы фильтра
            /// </summary>
            public const string FilterName = "MyProductActionsFilter";
        
            /// <summary>
            /// Параметр текущей позиции
            /// </summary>
            public const string RefTable = "refMyProductActions";
        
            /// <summary>
            /// Идентификатор.
            /// </summary>
            public const string id = "id";
        
            /// <summary>
            /// Идентификатор, наименование фильтра.
            /// </summary>
            public const string idFilterName = "id";
        
            /// <summary>
            /// Мой товар.
            /// </summary>
            public const string refProduct = "refProduct";
        
            /// <summary>
            /// Мой товар, наименование фильтра.
            /// </summary>
            public const string refProductFilterName = "refProduct";
        
            /// <summary>
            /// Наименование связи поля "Мой товар".
            /// </summary>
            public const string MyProduct_refProduct = "MyProduct_refProduct";
        
            /// <summary>
            /// Наименование связи поля "Мой товар", с именем ключа.
            /// </summary>
            public const string MyProduct_refProduct_id = "MyProduct_refProduct.id";
        
            /// <summary>
            /// Дата/время действия.
            /// </summary>
            public const string DateTimeAction = "DateTimeAction";
        
            /// <summary>
            /// Дата/время действия, наименование фильтра.
            /// </summary>
            public const string DateTimeActionFilterName = "DateTimeAction";
        
            /// <summary>
            /// Изменение кол-ва.
            /// </summary>
            public const string AmountChange = "AmountChange";
        
            /// <summary>
            /// Изменение кол-ва, наименование фильтра.
            /// </summary>
            public const string AmountChangeFilterName = "AmountChange";
        
            /// <summary>
            /// Примечание.
            /// </summary>
            public const string Note = "Note";
        
            /// <summary>
            /// Примечание, наименование фильтра.
            /// </summary>
            public const string NoteFilterName = "Note";
        
            /// <summary>
            /// .
            /// </summary>
            public const string RowVersion = "RowVersion";
        
            /// <summary>
            /// , наименование фильтра.
            /// </summary>
            public const string RowVersionFilterName = "RowVersion";
        }
        
        bool IAccessControl.CheckPermit(Page page)
        {
            return AccessOptions.CheckPermit();
        }

        private LogMonitor _logMonitor;
        protected LogMonitor LogMonitor
        {
            get
            {
                if(_logMonitor == null)
                {
                    _logMonitor = new LogMonitor();
                    _logMonitor.Init();
                }
                return _logMonitor;
            }
        }

        public static MainPageUrlBuilder FromUrl(string url)
        {
            var builder = MainPageUrlBuilder.FromUrlToOtherControl(url);
            builder.UserControl = "MyProductActionsFilter";
            builder.IsFilterWindow = true;
            return builder;
        }

        public static string GetUserControlName()
        {
            return "MyProductActionsFilter";
        }
    }
}
#pragma warning restore