//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleDictionaries.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyProductActionsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyProductActionsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleDictionaries.UserControls.MyProductActions.Resources", typeof(MyProductActionsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to MyProductActions(Поступления/продажи товаров).
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SampleDictionaries.
        /// </summary>
        public static string ProjectHeader {
            get {
                return ResourceManager.GetString("ProjectHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Просмотр.
        /// </summary>
        public static string LookMessage {
            get {
                return ResourceManager.GetString("LookMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string EditMessage {
            get {
                return ResourceManager.GetString("EditMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Вы действительно хотите удалить?.
        /// </summary>
        public static string DeleteQuestionMessage {
            get {
                return ResourceManager.GetString("DeleteQuestionMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Идентификатор.
        /// </summary>
        public static string id__Header {
            get {
                return ResourceManager.GetString("id__Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string id__ShortName {
            get {
                return ResourceManager.GetString("id__ShortName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string id__GridGroup {
            get {
                return ResourceManager.GetString("id__GridGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string id__Group {
            get {
                return ResourceManager.GetString("id__Group", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Мой товар.
        /// </summary>
        public static string refProduct__Header {
            get {
                return ResourceManager.GetString("refProduct__Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string refProduct__ShortName {
            get {
                return ResourceManager.GetString("refProduct__ShortName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string refProduct__GridGroup {
            get {
                return ResourceManager.GetString("refProduct__GridGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string refProduct__Group {
            get {
                return ResourceManager.GetString("refProduct__Group", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Дата/время действия.
        /// </summary>
        public static string DateTimeAction__Header {
            get {
                return ResourceManager.GetString("DateTimeAction__Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DateTimeAction__ShortName {
            get {
                return ResourceManager.GetString("DateTimeAction__ShortName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DateTimeAction__GridGroup {
            get {
                return ResourceManager.GetString("DateTimeAction__GridGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DateTimeAction__Group {
            get {
                return ResourceManager.GetString("DateTimeAction__Group", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Изменение кол-ва.
        /// </summary>
        public static string AmountChange__Header {
            get {
                return ResourceManager.GetString("AmountChange__Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AmountChange__ShortName {
            get {
                return ResourceManager.GetString("AmountChange__ShortName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AmountChange__GridGroup {
            get {
                return ResourceManager.GetString("AmountChange__GridGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AmountChange__Group {
            get {
                return ResourceManager.GetString("AmountChange__Group", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Примечание.
        /// </summary>
        public static string Note__Header {
            get {
                return ResourceManager.GetString("Note__Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Note__ShortName {
            get {
                return ResourceManager.GetString("Note__ShortName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Note__GridGroup {
            get {
                return ResourceManager.GetString("Note__GridGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Note__Group {
            get {
                return ResourceManager.GetString("Note__Group", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RowVersion__Header {
            get {
                return ResourceManager.GetString("RowVersion__Header", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RowVersion__ShortName {
            get {
                return ResourceManager.GetString("RowVersion__ShortName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RowVersion__GridGroup {
            get {
                return ResourceManager.GetString("RowVersion__GridGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RowVersion__Group {
            get {
                return ResourceManager.GetString("RowVersion__Group", resourceCulture);
            }
        }
    }
}