<?xml version="1.0" encoding="utf-8"?>
<Database Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sqlexpress2014;Initial Catalog=Sample;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DefaultConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DIC_MyFirstDictionary" Member="DIC_MyFirstDictionaries">
    <Type Name="DIC_MyFirstDictionary">
      <Column Name="id" Type="System.Int64" DbType="bigint" CanBeNull="false" IsDbGenerated="true" IsPrimaryKey="true" />
      <Column Name="Code" Type="System.String" DbType="nvarchar(4)" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="nvarchar(255)" CanBeNull="false" />
      <Column Name="DateStart" Type="System.DateTime" DbType="datetime" CanBeNull="false" />
      <Column Name="DateEnd" Type="System.DateTime" DbType="datetime" CanBeNull="true" />
      <Column Name="RowVersion" Type="System.Data.Linq.Binary" DbType="timestamp" CanBeNull="true" IsDbGenerated="true" />
      <Association Name="DIC_MyFirstDictionary_DIC_MySecondDictionary_refFirstDictionary" ThisKey="id" OtherKey="refFirstDictionary" Type="DIC_MySecondDictionary" Member="DIC_MySecondDictionaries_refFirstDictionary" />
    </Type>
  </Table>
  <Table Name="dbo.DIC_MySecondDictionary" Member="DIC_MySecondDictionaries">
    <Type Name="DIC_MySecondDictionary">
      <Column Name="id" Type="System.Int64" DbType="bigint" CanBeNull="false" IsDbGenerated="true" IsPrimaryKey="true" />
      <Column Name="Name" Type="System.String" DbType="nvarchar(255)" CanBeNull="false" />
      <Column Name="refFirstDictionary" Type="System.Int64" DbType="bigint" CanBeNull="false" />
      <Column Name="DecimalValue" Type="System.Decimal" DbType="decimal(10,2)" CanBeNull="true" />
      <Column Name="BoolValue" Type="System.Boolean" DbType="bit" CanBeNull="false" />
      <Association Name="DIC_MyFirstDictionary_DIC_MySecondDictionary_refFirstDictionary" ThisKey="refFirstDictionary" OtherKey="id" Type="DIC_MyFirstDictionary" IsForeignKey="true" Member="DIC_MyFirstDictionary_refFirstDictionary" />
      <Column Name="RowVersion" Type="System.Data.Linq.Binary" DbType="timestamp" CanBeNull="true" IsDbGenerated="true" />
    </Type>
  </Table>
  <Table Name="dbo.MyProducts" Member="MyProducts">
    <Type Name="MyProduct">
      <Column Name="id" Type="System.Int64" DbType="bigint" CanBeNull="false" IsDbGenerated="true" IsPrimaryKey="true" />
      <Column Name="Name" Type="System.String" DbType="nvarchar(200)" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="date" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="decimal(7,2)" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="decimal(7,2)" CanBeNull="false" />
      <Column Name="RowVersion" Type="System.Data.Linq.Binary" DbType="timestamp" CanBeNull="true" IsDbGenerated="true" />
      <Association Name="MyProducts_MyProductActions_refProduct" ThisKey="id" OtherKey="refProduct" Type="MyProductAction" Member="MyProductActions_refProduct" />
    </Type>
  </Table>
  <Table Name="dbo.MyProductActions" Member="MyProductActions">
    <Type Name="MyProductAction">
      <Column Name="id" Type="System.Int64" DbType="bigint" CanBeNull="false" IsPrimaryKey="true" />
      <Column Name="refProduct" Type="System.Int64" DbType="bigint" CanBeNull="false" />
      <Column Name="DateTimeAction" Type="System.DateTime" DbType="datetime" CanBeNull="false" />
      <Column Name="AmountChange" Type="System.Decimal" DbType="decimal(7,2)" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="nvarchar(500)" CanBeNull="true" />
      <Association Name="MyProducts_MyProductActions_refProduct" ThisKey="refProduct" OtherKey="id" Type="MyProduct" IsForeignKey="true" Member="MyProduct_refProduct" />
      <Column Name="RowVersion" Type="System.Data.Linq.Binary" DbType="timestamp" CanBeNull="true" IsDbGenerated="true" />
    </Type>
  </Table>
</Database>