<?xml version="1.0" encoding="utf-8"?>
<Database Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sqlexpress2014;Initial Catalog=Sample;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DefaultConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DIC_MyFirstDictionary" Member="DIC_MyFirstDictionaries">
    <Type Name="DIC_MyFirstDictionary">
      <Column Name="id" Type="System.Int64" DbType="bigint" CanBeNull="false" IsDbGenerated="true" IsPrimaryKey="true" />
      <Column Name="Code" Type="System.String" DbType="nvarchar(4)" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="nvarchar(255)" CanBeNull="false" />
      <Column Name="DateStart" Type="System.DateTime" DbType="datetime" CanBeNull="false" />
      <Column Name="DateEnd" Type="System.DateTime" DbType="datetime" CanBeNull="true" />
      <Column Name="RowVersion" Type="System.Data.Linq.Binary" DbType="timestamp" CanBeNull="true" IsDbGenerated="true" />
    </Type>
  </Table>
</Database>