/*
 * Generated by: Sergey.Shpakovskiy
 * Generated at: 1.0.0.2
 * Copyright © JSC NAT Kazakhstan 2011
 */

namespace SampleDictionaries.Security
{
    using System.Collections.Generic;

    using Nat.Web.Tools;

    public class SampleDictionariesRight
    {
        #region Константы ролей


        #endregion

        public static Dictionary<string, string> DicRoles = new Dictionary<string, string>(new CaseInsensitiveCultureComparer());

        static SampleDictionariesRight()
        {

        }

        public static void AddRolesToDictionary(Dictionary<string, string> roles)
        {
            foreach (KeyValuePair<string, string> pair in DicRoles)
                roles[pair.Key] = pair.Value;
        }
    }
}