/*
 * Generated by: Sergey.Shpakovskiy
 * Generated at: 1.0.0.3
 * Copyright © JSC NAT Kazakhstan 2011
 */
#pragma warning disable
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Linq;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Security.Principal;
using System.Text;
using System.Web;
using System.Web.Caching;
using System.Web.Compilation;
using System.Web.Script.Serialization;
using System.Web.UI;
using System.Web.UI.WebControls;
using JS.LinqToJavaScript;

using Nat.Tools.Specific;
using Nat.Web.Controls;
using Nat.Web.Controls.GenerationClasses;
using Nat.Web.Controls.GenerationClasses.Data;
using Nat.Web.Controls.GenerationClasses.Filter;
using Nat.Web.Controls.GenerationClasses.Navigator;
using Nat.Web.Controls.HistoryFilters;
using Nat.Web.Controls.Preview;
using Nat.Web.Tools;
using Nat.Web.Tools.Security;
using Nat.Web.Tools.WorkFlow;
using SampleDictionaries.UserControls;
using SampleDictionaries.Properties;
using SampleDictionaries.Security;
using AccessOptions = SampleDictionaries.DIC_MySecondDictionaryAccessOptions;
using SampleDictionaries;
using SampleDictionaries.UserControls;
using SampleDictionaries.Properties;

using Nat.Web.Tools.ExtNet.Data;
using Nat.Web.Tools.ExtNet.Extenders;
using Nat.Web.Tools.ExtNet.ExtNetConfig;

namespace SampleDictionaries
{
    #region DIC_MySecondDictionaryJournalDataSourceView

    public partial class DIC_MySecondDictionaryJournalDataSourceView : BaseDataSourceView<long, DIC_MySecondDictionary, DBDataContext, DIC_MySecondDictionaryJournalDataSourceView.Row>, IDataSourceView2, IDataSourceView3, IHeaderControl, IDataSourceViewExtNet
    {
        private readonly BaseDataSource<long> owner;
        private SelectModeDIC_MySecondDictionary? _select;
        private DIC_MySecondDictionaryFilter _filterSelect;
        private bool? _showHistory;
        private IEnumerable<Row> _cache;
        private MainPageUrlBuilder _url;

        public DIC_MySecondDictionaryJournalDataSourceView(BaseDataSource<long> owner, string viewName)
            : base(owner, viewName)
        {
            this.owner = owner;
            this.Lookup = new LookupExpressions { GetUrl = () => _url };
        }

        public DIC_MySecondDictionaryJournalDataSourceView()
            : base(new DIC_MySecondDictionaryJournalDataSource(), string.Empty)
        {
            this.Lookup = new LookupExpressions { GetUrl = () => _url };
        }
                
        public override bool LookupValuesHidden
        {
            set 
            {
                base.LookupValuesHidden = value;
                Lookup.DefaultHidden = value;
            }
        }
        
        public LookupExpressions Lookup { get; private set; }

        public SelectModeDIC_MySecondDictionary SelectMode
        {
            get 
            {
                try
                {
                    if (_url != null)
                        _select = (SelectModeDIC_MySecondDictionary?)Enum.Parse(typeof(SelectModeDIC_MySecondDictionary), _url.SelectMode, true);
                    if (owner == null && _select == null) _select = SelectModeDIC_MySecondDictionary.none;
                    if (_select == null) _select = (SelectModeDIC_MySecondDictionary?)Enum.Parse(typeof(SelectModeDIC_MySecondDictionary), MainPageUrlBuilder.GetSelectMode(owner.Page), true);
                }
                catch
                {
                    _select = SelectModeDIC_MySecondDictionary.none;
                }
                
                return _select.Value;
            }
            
            set
            {
                _select = value;
            }
        }

        public override string TableName
        {
            get { return "DIC_MySecondDictionary"; }
        }

        public override bool CanSort
        {
            get { return true; }
        }

        public override bool CanPage
        {
            get { return true; }
        }

        public override bool CanRetrieveTotalRowCount
        {
            get { return true; }
        }

        public string Header
        {
            get { return DIC_MySecondDictionaryResources.Header; }
        }

        public string HeaderRu
        {
            get { return DIC_MySecondDictionaryResources.ResourceManager.GetString("Header", new CultureInfo("ru-ru")); }
        }

        public string HeaderKz
        {
            get { return DIC_MySecondDictionaryResources.ResourceManager.GetString("Header", new CultureInfo("kk-kz")); }
        }

        partial void InitDefaultSort(ref string sortValue);
        
        protected override string DefaultSort
        {
            get
            {
                var sortValue = "Name,id";
                InitDefaultSort(ref sortValue);
                return sortValue;
            }
        }

        protected override string RequiredSort
        {
            get { return "id"; }
        }
        
        public override bool SupportGlobalCache { get { return false; } }

        public override bool SupportSelectICodeRow
        {
            get { return false; }
        }

        [Conditional("DEBUG")]
        private void WriteTrace(string value)
        {
            if (owner != null && owner.Page != null)
                owner.Page.Trace.Write(value);
        }

        protected override DBDataContext CreateDataContext()
        {
            var db = InitConnection == null ? new DBDataContext(SpecificInstances.DbFactory.CreateConnection()) : new DBDataContext(InitConnection);
            return db;
        }

        protected override IWorkFlow[] CreateWorkFlows()
        {
            return new IWorkFlow[] {};
        }

        private IEnumerable<Row> EnsureExistRow(IQueryable<Row> rows)
        {
            if (!AllowCreateSelectedRow || _selectedID == null) return rows;
            var list = rows.ToList();
            foreach (var item in list)
                if (item.id == _selectedID.Value)
                    return list;
            list.Add(new Row
            {
                id = _selectedID.Value,
                Value = _selectedID.Value.ToString(),
                nameRu = Nat.Web.Controls.Properties.Resources.SNotExistRow,
                nameKz = Nat.Web.Controls.Properties.Resources.SNotExistRow,
            });
            return list;
        }

        public override string GetStringID(DIC_MySecondDictionary row)
        {
            return GetID(row).ToString();
        }

        public override long? GetID(DIC_MySecondDictionary row)
        {
            return row.id;
        }

        public override long? GetIDByRefParent(DIC_MySecondDictionary row)
        {
            return null;
        }

        protected override bool UseTreeFilter { get { return false; } }

        public IQueryable<Row> GetSelect(long id)
        {
            return GetSelect(id, string.Empty);
        }

        public IQueryable<Row> GetSelect(long id, bool isKz)
        {
            return GetSelect(id, string.Empty, isKz);
        }

        public IQueryable<Row> GetSelect(long id, string selectColumnName)
        {
            return GetSelect(selectColumnName).Where(p => p.Item.id == id);
        }

        public IQueryable<Row> GetSelect(long id, string selectColumnName, bool isKz)
        {
            return GetSelect(selectColumnName, isKz).Where(p => p.Item.id == id);
        }

        public IQueryable<Row> GetSelect(long id, string selectColumnName, bool isKz, bool isTreeFilter)
        {
            return GetSelect(null, selectColumnName, isKz, isTreeFilter).Where(p => p.Item.id == id);
        }

        public override IQueryable<IRow> GetSelectIRow(long id)
        {
            return GetSelect(id).Cast<IRow>();
        }

        public override IQueryable<ICodeRow> GetSelectICodeRow(long id)
        {
            throw new NotImplementedException();
        }

        public override IQueryable<IRow> GetSelectIRow()
        {
            return GetSelect().Cast<IRow>();
        }

        public override IQueryable<ICodeRow> GetSelectICodeRow()
        {
            throw new NotImplementedException();
        }

        public IQueryable<Row> GetSelectWithoutFilters(long id)
        {
            return GetSelectWithoutFilters(id, string.Empty);
        }

        public IQueryable<Row> GetSelectWithoutFilters(long id, string selectColumnName)
        {
            return GetSelectWithoutFilters(selectColumnName).Where(p => p.Item.id == id);
        }

        public override Expression<Func<DIC_MySecondDictionary, long, bool>> GetWhereByKey()
        {
            return (p, id) => p.id == id;
        }

        public override object GetKey(string key)
        {
            return Convert.ToInt64(key);
        }

        public override string GetName(long id, string selectColumnName, bool isKz)
        {
            if (isKz)
                return GetSelectWithoutFilters(id, selectColumnName).Select(p => p.nameKz).FirstOrDefault();
            return GetSelectWithoutFilters(id, selectColumnName).Select(p => p.nameRu).FirstOrDefault();
        }

        public override IQueryable<BaseRow> GetSelectRow(long value, string selectColumnName)
        {
            return GetSelect(value, selectColumnName).Cast<BaseRow>();
        }

        public override IQueryable<IRow> GetSelectIRow(string queryParameters)
        {
            DB.ObjectTrackingEnabled = false;
            DB.DeferredLoadingEnabled = false;
            _filterSelect = new DIC_MySecondDictionaryFilter();
            var urlBuilder = new MainPageUrlBuilder("/MainPage.aspx/data/DIC_MySecondDictionaryJournal/Select?" + queryParameters);
            _filterSelect.SetUrl(urlBuilder);
            _filterSelect.SetDB(DB);
            _url = urlBuilder;
            SelectForAddType = urlBuilder.SelectForAddType;
            SelectParameters = urlBuilder.SelectParameters;
            AddSearchInFilter(urlBuilder, _filterSelect);
            if (!string.IsNullOrEmpty(urlBuilder.SelectNameColumn))
                return GetSelect(urlBuilder.SelectNameColumn).Cast<IRow>().Select(r => r);
            return GetSelect().Cast<IRow>().Select(r => r);
        }

        IQueryable<IDataRow> IDataSourceView2.GetSelectIRow(string queryParameters)
        {
            DB.ObjectTrackingEnabled = false;
            DB.DeferredLoadingEnabled = false;
            _filterSelect = new DIC_MySecondDictionaryFilter();
            var urlBuilder = new MainPageUrlBuilder("/MainPage.aspx/data/DIC_MySecondDictionaryJournal/Select?" + queryParameters);
            _filterSelect.SetUrl(urlBuilder);
            _filterSelect.SetDB(DB);
            _url = urlBuilder;
            SelectForAddType = urlBuilder.SelectForAddType;
            SelectParameters = urlBuilder.SelectParameters;
            AddSearchInFilter(urlBuilder, _filterSelect);
            if (!string.IsNullOrEmpty(urlBuilder.SelectNameColumn))
                return GetSelect(urlBuilder.SelectNameColumn).Cast<IDataRow>().Select(r => r);
            return GetSelect().Cast<IDataRow>().Select(r => r);
        }

        IQueryable<IDataRow> IDataSourceViewExtNet.GetFullModelData(string queryParameters)
        {
            DB.ObjectTrackingEnabled = false;
            DB.DeferredLoadingEnabled = false;
            _filterSelect = new DIC_MySecondDictionaryFilter();
            var url = "/MainPage.aspx/data/DIC_MySecondDictionaryJournal/Select"
                      + (!string.IsNullOrEmpty(queryParameters) && queryParameters[0] == '/'
                          ? queryParameters
                          : "?" + queryParameters);
            var urlBuilder = new MainPageUrlBuilder(url);
            _filterSelect.SetUrl(urlBuilder);
            _filterSelect.SetDB(DB);
            _filterSelect.ShowHistory = urlBuilder.ShowHistory;
            _url = urlBuilder;
            AddSearchInFilter(urlBuilder, _filterSelect);
            SelectForAddType = urlBuilder.SelectForAddType;
            SelectParameters = urlBuilder.SelectParameters;
            IQueryable<Row> data;
            if (!string.IsNullOrEmpty(urlBuilder.SelectNameColumn))
                data = GetSelect(urlBuilder.SelectNameColumn);
            else
                data = GetSelect();

            return data.Select(GetFullModelDataExpression).Cast<IDataRow>();
        }

        IQueryable<IDataRow> IDataSourceViewExtNet.GetFullModelData(string queryParameters, string refParent)
        {
            throw new NotSupportedException();
        }

        public Expression<Func<Row, IDataRow>> GetFullModelDataExpression
        {
            get
            {
                return row => new ModelData
                    {
                        CanEdit = row.CanEdit,
                        CanDelete = row.CanDelete,
                        id = row.Item.id,
                        Name = row.Item.Name,
                        refFirstDictionary = row.Item.refFirstDictionary,
                        refFirstDictionary_Name = row.Lookup.refFirstDictionary_Name,
                        DecimalValue = row.Item.DecimalValue,
                        BoolValue = row.Item.BoolValue,
                        RowVersion = row.Item.RowVersion,
                        nameRu = row.nameRu,
                        nameKz = row.nameKz,
                    };
            }
        }

        public override IQueryable<ICodeRow> GetSelectICodeRow(string queryParameters)
        {
            throw new NotImplementedException();
        }

        IQueryable<IDataCodeRow> IDataSourceView2.GetSelectICodeRow(string queryParameters)
        {
            throw new NotImplementedException();
        }

        public override BaseInformationValues Validate(long value, CancelEventArgs args)
        {
            var row = GetCacheSelect(value);
            if (row == null)
            {
                args.Cancel = true;
                return null;
            }
            if (row.Information != null)
                row.Information.Validate();
            return row.Information;
        }

        public override Row[] ValidateAll(long[] values, CancelEventArgs args)
        {
            var rememberShowHistory = _showHistory;
            var recArgs = args as RecordValidateArgs;
            if (recArgs != null && recArgs.IgnoreHistoryFilter)
                _showHistory = true;
            var rows = GetSelect().Where(r => values.Contains(r.id)).ToArray();
            _showHistory = rememberShowHistory;

            if (rows.Length == 0)
            {
                args.Cancel = true;
                return new Row[0];
            }
            foreach (var row in rows.Where(row => row.Information != null))
                row.Information.Validate();
            return rows;
        }

        public override BaseInformationValues Validate(long value, RecordValidateArgs args)
        {
            var rememberShowHistory = _showHistory;
            if (args.IgnoreHistoryFilter)
                _showHistory = true;
            var row = GetCacheSelect(value);
            _showHistory = rememberShowHistory;
            if (row == null || (!row.CanAddChild && args.SelectForAddChild))
            {
                args.Cancel = true;
                return null;
            }
            if (row.Information != null)
                row.Information.Validate();
            return row.Information;
        }

        public override bool CheckPermit()
        {
            return AccessOptions.CheckPermit();
        }

        public override BaseFilterControl<long> CreateDefaultFilter(MainPageUrlBuilder urlBuilder)
        {
            var control = new DIC_MySecondDictionaryFilter();
            urlBuilder.UserControl = DIC_MySecondDictionaryFilter.ConstOfColumnNames.JournalName;
            return control;
        }

        protected override Expression GetFilteredExpression(Expression query, QueryParameters qParams, out BaseFilterControl<long, DIC_MySecondDictionary, DBDataContext> outFilterControl)
        {
            DIC_MySecondDictionaryFilter filterControl = _filterSelect;
            if (_filterSelect == null)
            {
                var args = new DataSourceSelectingEventArgs { DB = DB };
                if (owner != null) owner.OnSelecting(args);
                filterControl = (DIC_MySecondDictionaryFilter)args.FilterControl;
            }
            if(filterControl == null)
            {
                var fc = new DIC_MySecondDictionaryFilter();
                filterControl = fc;
                fc.SetUrl(new MainPageUrlBuilder { SelectMode = "none", UserControl = DIC_MySecondDictionaryFilter.ConstOfColumnNames.JournalName, });
                fc.SetDB(DB);
            }
            if (_showHistory == null)
                _showHistory = filterControl.ShowHistory;
            else
                filterControl.ShowHistory = _showHistory.Value;
            _selectedID = filterControl.SelectedID;
            _url = filterControl.Url;
            outFilterControl = filterControl;
            return filterControl.GetFilteredExpression(query, qParams);
        }

        protected IQueryable<DIC_MySecondDictionary> SetFilter(IQueryable<DIC_MySecondDictionary> queryable)
        {
            DIC_MySecondDictionaryFilter filterControl = _filterSelect;
            if (_filterSelect == null)
            {
                var args = new DataSourceSelectingEventArgs { DB = DB };
                owner.OnSelecting(args);
                filterControl = (DIC_MySecondDictionaryFilter)args.FilterControl;
            }
            if (filterControl == null)
            {
                var fc = new DIC_MySecondDictionaryFilter();
                filterControl = fc;
                fc.SetUrl(new MainPageUrlBuilder { SelectMode = "none", UserControl = DIC_MySecondDictionaryFilter.ConstOfColumnNames.JournalName });
                fc.SetDB(DB);
                if (!string.IsNullOrEmpty(SelectedRowKey))
                    filterControl.SelectedID = Convert.ToInt64(SelectedRowKey);
            }
            if (_showHistory == null)
                _showHistory = filterControl.ShowHistory;
            else
                filterControl.ShowHistory = _showHistory.Value;
            _selectedID = filterControl.SelectedID;
            _url = filterControl.Url;
            return (IQueryable<DIC_MySecondDictionary>)filterControl.SetFilters(queryable);
        }

        public partial class TotalInfo
        {
        }

        partial void GetTotalInfo(DataSourceSelectArguments arguments, ref IEnumerable<TotalInfo> result);

        public IEnumerable<TotalInfo> GetTotalInfo(DataSourceSelectArguments arguments)
        {
            IEnumerable<TotalInfo> result = null;
            GetTotalInfo(arguments, ref result);
            return result;
        }

        partial void ChangeSelect(ref Expression<Func<DIC_MySecondDictionary, LookupValues, InformationValues>> informationExpression);
        partial void ChangeSelectDB(ref Expression<Func<DBDataContext, DIC_MySecondDictionary, LookupValues, InformationValues>> informationExpression);
        
        private static ConstructorInfo rowCtr = typeof(Row).GetConstructor(new [] { typeof(DIC_MySecondDictionary), typeof(LookupValues), typeof(InformationValues), typeof(string), typeof(string), typeof(bool), typeof(bool), typeof(bool), typeof(Int64) });
        private static ConstructorInfo lookupCtr = typeof(LookupValues).GetConstructor(new[] { typeof(string), typeof(object[]) });
        
        private IQueryable<Row> ChangeSelect(IQueryable<DIC_MySecondDictionary> query, string selectColumnName)
        {
            var isKz = System.Globalization.CultureInfo.CurrentUICulture.Name.Equals("kk-kz", StringComparison.OrdinalIgnoreCase);
            return ChangeSelect(query, selectColumnName, isKz);
        }
        
        private IQueryable<Row> ChangeSelect(IQueryable<DIC_MySecondDictionary> query, string selectColumnName, bool isKz)
        {
            Expression exp = GetSelectedRowExpression(query.Expression, selectColumnName, isKz, null);
            return query.Provider.CreateQuery<Row>(exp);
        }
        
        protected override Expression GetSelectedRowExpression(Expression query, string selectColumnName, bool isKz, QueryParameters qParams)
        {
            WriteTrace("DIC_MySecondDictionaryJournalDataSourceView.ChangeSelect.Begin");
            if (qParams != null)
                qParams.SelectColumnName = selectColumnName;
            var showHistory = _showHistory == null || _showHistory.Value;
            var time = DateTime.Now;
            IQueryable<Row> result;
        
            var param = Expression.Parameter(typeof(DIC_MySecondDictionary), "c");
            Lookup.IsKz = isKz;
            Lookup.DB = DB;
            Lookup.ShowHistory = showHistory;
            Lookup.QueryParameters = qParams;
            if (qParams != null)
            {
                qParams.AddUniqueParameter("IsKz=" + isKz);
                qParams.AddUniqueParameter("ShowHistory=" + showHistory);
            }
            var selectedAdditionalValuesExp = GetSelectedAdditionalValuesExpression(DB, param);
            Expression lookupExp = Expression.New(lookupCtr, 
                new Expression[] { Lookup.GetExpressionrefFirstDictionary(param),  selectedAdditionalValuesExp }, 
                new MemberInfo[] {typeof(LookupValues).GetMember("refFirstDictionary_Name")[0],  typeof(LookupValues).GetMember("SelectedAdditionalValues")[0]});
            Expression lookupPred = Expression.Lambda(lookupExp, param);
            Expression<Func<DIC_MySecondDictionary, LookupValues, InformationValues>> informationExpression = null;
            Expression<Func<DBDataContext, DIC_MySecondDictionary, LookupValues, InformationValues>> informationExpressionDB = null;
            ChangeSelect(ref informationExpression);
            ChangeSelectDB(ref informationExpressionDB);
            Expression informationExp;
            Type selectType = typeof(DIC_MySecondDictionary);
        
            if (informationExpressionDB != null)
                informationExp = Expression.Invoke(informationExpressionDB, qParams.GetDBExpression(DB), param, lookupExp);
            else if (informationExpression != null)
                informationExp = Expression.Invoke(informationExpression, param, lookupExp);
            else
                informationExp = Expression.Constant(null, typeof(InformationValues)); 
        
            Expression<Func<DIC_MySecondDictionary, string>> nameRuExp;
            Expression<Func<DIC_MySecondDictionary, string>> nameKzExp;
            GetNameExpressions(selectColumnName, out nameRuExp, out nameKzExp);
            Expression<Func<DIC_MySecondDictionary, Int64>> idKeyExp = p => p.id;
            Expression expItem = param;
        
            Expression canEditExp;
            Expression canDeleteExp;
            GetEditAndDeleteExpressions(expItem, informationExp, out canEditExp, out canDeleteExp);
            
            Expression canAddChildExp = null;
            Type selectForAddType = string.IsNullOrEmpty(SelectForAddType) ? null : BuildManager.GetType(SelectForAddType, true, true);
            if (selectForAddType != null)
                canAddChildExp = GetAddChildExpression(null, selectForAddType, expItem, param, new Expression[0]);
            if (canAddChildExp == null)
                canAddChildExp = Expression.Constant(true);
            
            var rowExp = Expression.New(rowCtr, 
                new Expression[] { expItem, lookupExp, informationExp, Expression.Invoke(nameRuExp, expItem), Expression.Invoke(nameKzExp, expItem), canEditExp, canDeleteExp, canAddChildExp, Expression.Invoke(idKeyExp, expItem) },
                new MemberInfo[] { typeof(Row).GetMember("Item")[0], typeof(Row).GetMember("Lookup")[0], typeof(Row).GetMember("Information")[0], typeof(Row).GetMember("nameRu")[0], typeof(Row).GetMember("nameKz")[0], typeof(Row).GetMember("CanEdit")[0], typeof(Row).GetMember("CanDelete")[0], typeof(Row).GetMember("CanAddChild")[0], typeof(Row).GetMember("id")[0] });
            Expression pred = Expression.Lambda(rowExp, param);
            Expression expr = Expression.Call(typeof(Queryable), "Select", new[] { selectType, typeof(Row) }, query, pred);
            WriteTrace("DIC_MySecondDictionaryJournalDataSourceView.ChangeSelect.End");
            return expr;
        }
        
        partial void GetNameExpressionPartial(string selectColumnName, ref Expression<Func<DIC_MySecondDictionary, string>> nameRuExp, ref Expression<Func<DIC_MySecondDictionary, string>> nameKzExp);
        
        private void GetNameExpressions(string selectColumnName, out Expression<Func<DIC_MySecondDictionary, string>> nameRuExp, out Expression<Func<DIC_MySecondDictionary, string>> nameKzExp)
        {
            nameRuExp = nameKzExp = null;
            GetNameExpressionPartial(selectColumnName, ref nameRuExp, ref nameKzExp);
            if (nameRuExp != null && nameKzExp != null)
                return;
        
            if (string.IsNullOrEmpty(selectColumnName))
            {
                nameKzExp = nameRuExp = p => p.Name;
            }
            else
            {
                switch(selectColumnName)
                {
                    case "Name":
                        nameKzExp = nameRuExp = r => r.Name.ToString();
                        break;
                    case "refFirstDictionary":
                        nameRuExp = r => r.DIC_MyFirstDictionary_refFirstDictionary.Name.ToString();
                        nameKzExp = r => r.DIC_MyFirstDictionary_refFirstDictionary.Name.ToString();
                        break;
                    case "DecimalValue":
                        nameKzExp = nameRuExp = r => r.DecimalValue.ToString();
                        break;
                    case "BoolValue":
                        nameKzExp = nameRuExp = r => r.BoolValue.ToString();
                        break;
                    default:
                        throw new ArgumentException("Ќе найдена соответствующа€ колонка", "selectColumnName");
                }
            }
        }
        
        private DIC_MyFirstDictionaryJournalDataSource _cachedDIC_MyFirstDictionaryDataSource;
        
        bool _canEditAndDeleteExpressionInitialized = false;
        Expression _canEditAndDeleteExpCache;
        Expression _canEditExpCache;
        Expression _canDeleteExpCache;
        partial void SetCanEditAndDeleteExpression(BaseFilterEventArgs<DIC_MySecondDictionary> filterArgs);
        partial void SetCanEditExpression(BaseFilterEventArgs<DIC_MySecondDictionary> filterArgs);
        partial void SetCanDeleteExpression(BaseFilterEventArgs<DIC_MySecondDictionary> filterArgs);
        partial void SetCanEditAndDeleteExpression(BaseFilterEventArgs<DIC_MySecondDictionary, DBDataContext> filterArgs);
        partial void SetCanEditExpression(BaseFilterEventArgs<DIC_MySecondDictionary, DBDataContext> filterArgs);
        partial void SetCanDeleteExpression(BaseFilterEventArgs<DIC_MySecondDictionary, DBDataContext> filterArgs);
        
        private void GetEditAndDeleteExpressions(Expression expItem, Expression informationExp, out Expression canEditExp, out Expression canDeleteExp)
        {
            if (AllowSelectOnlyNames)
            {
                canEditExp = Expression.Constant(false);
                canDeleteExp = Expression.Constant(false);
                return;
            }
            Expression canEditExpression = null;
            Expression canDeleteExpression = null;
            Expression canEditAndDeleteExpression = null;
        
            if (_canEditAndDeleteExpressionInitialized)
            {
                canEditAndDeleteExpression = _canEditAndDeleteExpCache;
                canEditExpression = _canEditExpCache;
                canDeleteExpression = _canDeleteExpCache;
            }
            else
            {
                _canEditAndDeleteExpCache = canEditAndDeleteExpression = GetEditAndDeleteExpression(canEditAndDeleteExpression);
                _canEditExpCache = canEditExpression = GetEditExpression(canEditExpression);
                _canDeleteExpCache = canDeleteExpression = GetDeleteExpression(canDeleteExpression);
            }
            canEditExp = canEditExpression == null ? (Expression)Expression.Constant(true) : Expression.Invoke(canEditExpression, expItem);
            canDeleteExp = canDeleteExpression == null ? (Expression)Expression.Constant(true) : Expression.Invoke(canDeleteExpression, expItem);
            if (canEditAndDeleteExpression != null)
            {
                Expression canEditAndDeleteExp = Expression.Invoke(canEditAndDeleteExpression, expItem);
                canEditExp = Expression.And(canEditAndDeleteExp, canEditExp);
                canDeleteExp = Expression.And(canEditAndDeleteExp, canDeleteExp);
            }
        }
        
        public override BaseFilterEventArgs<DIC_MySecondDictionary> GetEditAndDeleteFilter(Type typeOfData)
        {
            var filterArgs = base.GetEditAndDeleteFilter(typeOfData);
        
            SetCanEditAndDeleteExpression(filterArgs);
            SetCanEditAndDeleteExpression((BaseFilterEventArgs<DIC_MySecondDictionary, DBDataContext>)filterArgs);
            return filterArgs;
        }
        /*
        public override Expression GetEditAndDeleteByParents<T>(Expression source, ParameterExpression param, Expression upToTable, IEnumerable<Expression> fieldsToCheckReference)
        {
            var refFirstDictionaryControl = _cachedDIC_MyFirstDictionaryDataSource;
            if (refFirstDictionaryControl == null)
            {
                refFirstDictionaryControl = _cachedDIC_MyFirstDictionaryDataSource = new DIC_MyFirstDictionaryJournalDataSource();
                refFirstDictionaryControl.View.DB = DB;
            }
            var refFirstDictionaryToTable = Expression.Property(upToTable, "DIC_MyFirstDictionary_refFirstDictionary");
            var refFirstDictionaryToCheckReference = new List<Expression>(fieldsToCheckReference);
            source = refFirstDictionaryControl.View.GetEditAndDeleteExpression<T>(source, refFirstDictionaryToTable, param, refFirstDictionaryToCheckReference);
            return source;
        }*/
        
        public override BaseFilterEventArgs<DIC_MySecondDictionary> GetEditFilter(Type typeOfData)
        {
            var filterArgs = base.GetEditFilter(typeOfData);
        
            SetCanEditExpression(filterArgs);
            SetCanEditExpression((BaseFilterEventArgs<DIC_MySecondDictionary, DBDataContext>)filterArgs);
            return filterArgs;
        }
        /*
        public override Expression GetEditByParents<T>(Expression source, ParameterExpression param, Expression upToTable, IEnumerable<Expression> fieldsToCheckReference)
        {
            var refFirstDictionaryControl = _cachedDIC_MyFirstDictionaryDataSource;
            if (refFirstDictionaryControl == null)
            {
                refFirstDictionaryControl = _cachedDIC_MyFirstDictionaryDataSource = new DIC_MyFirstDictionaryJournalDataSource();
                refFirstDictionaryControl.View.DB = DB;
            }
            var refFirstDictionaryToTable = Expression.Property(upToTable, "DIC_MyFirstDictionary_refFirstDictionary");
            var refFirstDictionaryToCheckReference = new List<Expression>(fieldsToCheckReference);
            source = refFirstDictionaryControl.View.GetEditExpression<T>(source, refFirstDictionaryToTable, param, refFirstDictionaryToCheckReference);
            return source;
        }*/
        
        public override BaseFilterEventArgs<DIC_MySecondDictionary> GetDeleteFilter(Type typeOfData)
        {
            var filterArgs = base.GetDeleteFilter(typeOfData);
        
            SetCanDeleteExpression(filterArgs);
            SetCanDeleteExpression((BaseFilterEventArgs<DIC_MySecondDictionary, DBDataContext>)filterArgs);
            return filterArgs;
        }
        /*
        public override Expression GetDeleteByParents<T>(Expression source, ParameterExpression param, Expression upToTable, IEnumerable<Expression> fieldsToCheckReference)
        {
            var refFirstDictionaryControl = _cachedDIC_MyFirstDictionaryDataSource;
            if (refFirstDictionaryControl == null)
            {
                refFirstDictionaryControl = _cachedDIC_MyFirstDictionaryDataSource = new DIC_MyFirstDictionaryJournalDataSource();
                refFirstDictionaryControl.View.DB = DB;
            }
            var refFirstDictionaryToTable = Expression.Property(upToTable, "DIC_MyFirstDictionary_refFirstDictionary");
            var refFirstDictionaryToCheckReference = new List<Expression>(fieldsToCheckReference);
            source = refFirstDictionaryControl.View.GetDeleteExpression<T>(source, refFirstDictionaryToTable, param, refFirstDictionaryToCheckReference);
            return source;
        }*/
        
        private List<ParentDataSourceViewInfo> _parentDataSources = null;
        partial void InitializeParentCollection(ICollection<ParentDataSourceViewInfo> parentDataSources);
        
        public override IEnumerable<ParentDataSourceViewInfo> GetParentCollection()
        {
            if (_parentDataSources != null) return _parentDataSources;
             _parentDataSources = new List<ParentDataSourceViewInfo>();
            var refFirstDictionaryControl = new DIC_MyFirstDictionaryJournalDataSource();
            refFirstDictionaryControl.View.DB = DB;
            _parentDataSources.Add(new ParentDataSourceViewInfo
                {
                    DataSource = refFirstDictionaryControl.View,
                    ReferenceName = "DIC_MyFirstDictionary_refFirstDictionary",
                    Mandatory = true,
                    FieldName = "refFirstDictionary",
                    TableType = typeof(DIC_MyFirstDictionary),
                });
            InitializeParentCollection(_parentDataSources);
            return _parentDataSources;
        }
        
        Expression _canAddExpCache;
        
        partial void SetCanAddChildsExpression(BaseFilterEventArgs<DIC_MySecondDictionary> filterArgs);
        
        protected override BaseFilterEventArgs<DIC_MySecondDictionary> GetAddRule(Type typeOfData)
        {
            var filterArgs = base.GetAddRule(typeOfData);
        
            SetCanAddChildsExpression(filterArgs);
            return filterArgs;
        }
        
        public override IEnumerable<IQueryable> AllowAddRowGetSources(BaseNavigatorValues valuesT)
        {
            if (InitConnection != null) DB.Transaction = InitTransaction;
            var values = (DIC_MySecondDictionaryNavigatorValues)valuesT;
            var sources = new List<IQueryable>();
            if (values.DIC_MyFirstDictionary.HasValue)
            {
                var id = values.DIC_MyFirstDictionary.Value;
                sources.Add(DB.DIC_MyFirstDictionaries.Where(r => r.id == id));
            }
            return sources;
        }
        
        public override IQueryable<DIC_MySecondDictionary> GetSelectItems(long id)
        {
            if (InitConnection != null) DB.Transaction = InitTransaction;
            return DB.DIC_MySecondDictionaries.Where(row => row.id == id);
        }
        
        public override IQueryable<DIC_MySecondDictionary> GetSelectItems()
        {
            if (InitConnection != null) DB.Transaction = InitTransaction;
            return DB.DIC_MySecondDictionaries;
        }
        
        /*
        private IQueryable<Row> ChangeSelect(IQueryable<DIC_MySecondDictionary> query, string selectColumnName)
        {
            WriteTrace("DIC_MySecondDictionaryJournalDataSourceView.ChangeSelect.Begin");
            var isKz = System.Globalization.CultureInfo.CurrentUICulture.Name.Equals("kk-kz", StringComparison.OrdinalIgnoreCase);
            var time = DateTime.Now;
            IQueryable<Row> result;
            if (_showHistory == null || _showHistory.Value)
                result = from p in query
                    select new Row
                               {
                                   id = p.id,
                                   Value = p.id.ToString(),
                                   Item = p,
                                   Lookup = new LookupValues
                                                {
                                                    refFirstDictionary_Name = (isKz ? p.DIC_MyFirstDictionary_refFirstDictionary.Name : p.DIC_MyFirstDictionary_refFirstDictionary.Name).ToString(),
                                                 },
                                   nameRu = p.Name.ToString(),
                                   nameKz = p.Name.ToString(),
                               };
            else
                result = from p in query
                    select new Row
                               {
                                   id = p.id,
                                   Value = p.id.ToString(),
                                   Item = p,
                                   Lookup = new LookupValues
                                                {
                                                    refFirstDictionary_Name = (isKz ? p.DIC_MyFirstDictionary_refFirstDictionary.Name : p.DIC_MyFirstDictionary_refFirstDictionary.Name).ToString(),
                                                 },
                                   nameRu = p.Name.ToString(),
                                   nameKz = p.Name.ToString(),
                               };
            if (!string.IsNullOrEmpty(selectColumnName))
            {
                switch(selectColumnName)
                {
                    case "id":
                        result = result.Select(r => 
                           new Row 
                           {
                               id = r.id,
                               Value = r.Value,
                               Item = r.Item,
                               Lookup = r.Lookup,
                               Information = r.Information,
                               nameRu = r.Item.id.ToString(),
                               nameKz = r.Item.id.ToString(),
                           });
                        break;
                    case "Name":
                        result = result.Select(r => 
                           new Row 
                           {
                               id = r.id,
                               Value = r.Value,
                               Item = r.Item,
                               Lookup = r.Lookup,
                               Information = r.Information,
                               nameRu = r.Item.Name.ToString(),
                               nameKz = r.Item.Name.ToString(),
                           });
                        break;
                    case "refFirstDictionary":
                        result = result.Select(r => 
                           new Row 
                           {
                               id = r.id,
                               Value = r.Value,
                               Item = r.Item,
                               Lookup = r.Lookup,
                               Information = r.Information,
                               nameRu = r.Item.DIC_MyFirstDictionary_refFirstDictionary.Name.ToString(),
                               nameKz = r.Item.DIC_MyFirstDictionary_refFirstDictionary.Name.ToString(),
                           });
                        break;
                    case "DecimalValue":
                        result = result.Select(r => 
                           new Row 
                           {
                               id = r.id,
                               Value = r.Value,
                               Item = r.Item,
                               Lookup = r.Lookup,
                               Information = r.Information,
                               nameRu = r.Item.DecimalValue.ToString(),
                               nameKz = r.Item.DecimalValue.ToString(),
                           });
                        break;
                    case "BoolValue":
                        result = result.Select(r => 
                           new Row 
                           {
                               id = r.id,
                               Value = r.Value,
                               Item = r.Item,
                               Lookup = r.Lookup,
                               Information = r.Information,
                               nameRu = r.Item.BoolValue.ToString(),
                               nameKz = r.Item.BoolValue.ToString(),
                           });
                        break;
                    case "RowVersion":
                        result = result.Select(r => 
                           new Row 
                           {
                               id = r.id,
                               Value = r.Value,
                               Item = r.Item,
                               Lookup = r.Lookup,
                               Information = r.Information,
                               nameRu = r.Item.RowVersion.ToString(),
                               nameKz = r.Item.RowVersion.ToString(),
                           });
                        break;
                    default:
                        throw new ArgumentException("Ќе найдена соответствующа€ колонка", "selectColumnName");
                }
            }
            WriteTrace("DIC_MySecondDictionaryJournalDataSourceView.ChangeSelect.End");
            return result;
        }*/

        public Row GetRecord(long id)
        {
            WriteTrace("DIC_MySecondDictionaryJournalDataSourceView.ChangeSelect.Begin");
            var query = DB.DIC_MySecondDictionaries.AsQueryable();
            var resQuery = ChangeSelect(query, string.Empty);
            IQueryable<Row> result = null;
            //ChangeSelect(resQuery, ref result, DB);
            Row returnValue;
            if (result != null)
                returnValue = result.FirstOrDefault(p => p.Item.id == id);
            else
                returnValue = resQuery.FirstOrDefault(p => p.Item.id == id);
            WriteTrace("DIC_MySecondDictionaryJournalDataSourceView.ChangeSelect.End");
            return returnValue;
        }

        partial void InitializeStoreModelPartial(Ext.Net.Model model);

        public virtual void InitializeStoreModel(Ext.Net.Model model)
        {
            // todo: Add full store model scheme
            InitializeStoreModelPartial(model);
        }

        public virtual void InitializeStoreModelAdditional(Ext.Net.Model model)
        {
            InitializeStoreModelPartial(model);
        }



        public class Row : BaseRow
        {
            public Row()
            {
            }
        
            public Row(DIC_MySecondDictionary item, LookupValues lookup, InformationValues information, string nameRu, string nameKz, bool canEdit, bool canDelete, bool canAddChild, Int64 id)
            {
                Item = item;
                Lookup = lookup;
                Information = information;
                this.id = id;
                Value = id.ToString();
                this.nameRu = nameRu;
                this.nameKz = nameKz;
                CanEdit = canEdit;
                CanDelete = canDelete;
                CanAddChild = canAddChild;
            }
        
            public override string nameRu 
            { 
                get { return base.nameRu; }
                set { base.nameRu = value; } 
            }
        
            public override string nameKz
            {
                get { return base.nameKz; }
                set { base.nameKz = value; }
            }
        
            public override bool CanEdit
            {
                get { return base.CanEdit; }
                set { base.CanEdit = value; }
            }
        
            public override bool CanDelete
            {
                get { return base.CanDelete; }
                set { base.CanDelete = value; }
            }
        
            public override bool CanAddChild
            {
                get { return base.CanAddChild; }
                set { base.CanAddChild = value; }
            }
        
            public override long id
            {
                get { return base.id; }
                set { base.id = value; }
            }
        
            private LookupValues _lookup;
            public LookupValues Lookup
            {
                get { return _lookup; }
                set 
                { 
                    _lookup = value;
                    if (Item != null)
                    {
                        // ≈сли нет полей с заполнением из Ѕƒ, то избавл€емс€ от дублировани€ объекта у строк
                        // “.е. LinqToSql передает один объект всем строкам, а тут мы мен€ем поведение.
                        if (_lookup.Item != null)
                            _lookup = new LookupValues { SelectedAdditionalValues = new object[0] };
                        _lookup.Item = Item;
                    }
                    if (Information != null)
                        Information.Lookup = _lookup;
                    _lookup.Row = this;
                }
            }
        
            private InformationValues _information;
            public InformationValues Information
            {
                get { return _information; }
                set 
                { 
                    _information = value;
                    if (Item != null && _information != null)
                        _information.Item = Item;
                    if (Lookup != null && _information != null)
                        _information.Lookup = Lookup;
                }
            }
        
            [NonSerialized]
            DIC_MySecondDictionary _item;
            public DIC_MySecondDictionary Item 
            {
                get { return _item; }
                set 
                { 
                    _item = value;
                    if (Lookup != null)
                        Lookup.Item = value;
                    if (Information != null)
                        Information.Item = value;
                }
            }
        
            public string AdditionalValues
            {
                get { return Lookup == null ? null : Ext.Net.JSON.Serialize(Lookup.SelectedAdditionalValues); }
            }
        
            public override string[] GetAdditionalValues(SelectParameters selectParameters)
            {
                return Lookup == null ? null : Lookup.SelectedAdditionalValues.Select((r, i) => string.Format(selectParameters.SelectValues[i].Format, r)).ToArray();
            }
        
            public override object[] GetAdditionalValues()
            {
                return Lookup == null ? null : Lookup.SelectedAdditionalValues;
            }
        
            public virtual void SetValue(string strValue)
            {
                Value = strValue;
        
            }
        }

        [Serializable]
        public partial class LookupValues
        {
            public LookupValues()
            {
            }
        
            public LookupValues(string refFirstDictionary_Name, 
        object[] selectedAdditionalValues)
            {
                this.refFirstDictionary_Name = refFirstDictionary_Name;
                
                this.SelectedAdditionalValues = selectedAdditionalValues;
            }
        
            public string refFirstDictionary_Name { get; set; }
            
        
            [NonSerialized]
            DIC_MySecondDictionary _item;
        
            [ScriptIgnore]
            public DIC_MySecondDictionary Item 
            {
                get { return _item; }
                set { _item = value; }
            }
        
            [NonSerialized]
            Row _row;
        
            [ScriptIgnore]
            public Row Row
            {
                get { return _row; }
                set { _row = value; }
            }
        
            public object [] SelectedAdditionalValues { get; set; }
        }
        
        public partial class InformationValues : BaseInformationValues
        {
            public InformationValues()
            {
            }
        
            [NonSerialized]
            private LookupValues _lookup;
        
            [ScriptIgnore]
            public LookupValues Lookup
            {
                get { return _lookup; }
                set 
                { 
                    _lookup = value;
                    if (Item != null)
                        _lookup.Item = Item;
                }
            }
        
            [NonSerialized]
            private DIC_MySecondDictionary _item;
        
            [ScriptIgnore]
            public DIC_MySecondDictionary Item
            {
                get { return _item; }
                set 
                { 
                    _item = value;
                    if (Lookup != null)
                        Lookup.Item = value;
                }
            }
        }
        
        public partial class ModelData : BaseRow
        {
            public ModelData()
            {
            }
        
            public System.Int64 id { get; set; }
        
            public System.String Name { get; set; }
        
            public System.Int64 refFirstDictionary { get; set; }
        
            public string refFirstDictionary_Name { get; set; }
        
            public System.Decimal? DecimalValue { get; set; }
        
            public System.Boolean BoolValue { get; set; }
        
            public System.Data.Linq.Binary RowVersion { get; set; }
        }
        
        
        
        public class LookupExpressions
        {
            private static readonly Expression NullExpression = Expression.Constant(null, typeof(string));
            private static readonly Expression NullIntExpression = Expression.Constant(0, typeof(int));
        
            private bool isKz { get; set; }
        
            public bool IsKz
            {
                get { return isKz; } 
                set { isKz = value; }
            }
        
            private bool showHistory { get; set; }
        
            public bool ShowHistory
            {
                get { return showHistory; } 
                set { showHistory = value; }
            }
        
            private QueryParameters qParams { get; set; }
        
            public QueryParameters QueryParameters
            {
                get { return qParams; } 
                set { qParams = value; }
            }
            
            public Func<MainPageUrlBuilder> GetUrl { get; set; }
        
            public DBDataContext DB { get; set; }
            public bool DefaultHidden { get; set; }
            private bool? _refFirstDictionaryHidden;
        
            public bool refFirstDictionaryHidden
            {
                get { return _refFirstDictionaryHidden ?? DefaultHidden; }
                set { _refFirstDictionaryHidden = value; }
            }
        
            private static readonly Expression<Func<DIC_MySecondDictionary, string>> ruExpressionrefFirstDictionary = r =>r.DIC_MyFirstDictionary_refFirstDictionary.Name;
            private static Expression<Func<DIC_MySecondDictionary, string>> kzExpressionrefFirstDictionary = r =>r.DIC_MyFirstDictionary_refFirstDictionary.Name;
        
            public Expression GetExpressionrefFirstDictionary(ParameterExpression param)
            {
                if (refFirstDictionaryHidden)
                    return NullExpression;
                return Expression.Invoke(isKz ? kzExpressionrefFirstDictionary : ruExpressionrefFirstDictionary, param);
            }  
        }

        protected static IQueryable<DIC_MySecondDictionary> SetSortExpression(string sortExpression, IQueryable source)
        {
            Expression expression = source.Expression;
            string str = "OrderBy";
            string str2 = "OrderByDescending";
            foreach (string orderBy in sortExpression.Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries))
            {
                var split = orderBy.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
                bool ascending = true;
                if (split.Length == 2)
                    ascending = split[1].Equals("Asc", StringComparison.OrdinalIgnoreCase);

                string orderByColumn = split[0];
                ParameterExpression param = Expression.Parameter(typeof(DIC_MySecondDictionary), "c");
                Type fieldType;
                var property = LinqFilterGenerator.GetProperty(typeof(DIC_MySecondDictionary), orderByColumn, param, out fieldType);
                expression = Expression.Call(typeof(Queryable), ascending ? str : str2,
                                             new[] { typeof(DIC_MySecondDictionary), fieldType },
                                             expression,
                                             Expression.Lambda(property, param));
                str = "ThenBy";
                str2 = "ThenByDescending";
            }
            return (IQueryable<DIC_MySecondDictionary>)source.Provider.CreateQuery(expression);
        }
    }

    #endregion

    #region DIC_MySecondDictionaryJournalDataSource

    public class DIC_MySecondDictionaryJournalDataSource : BaseDataSource<long, DIC_MySecondDictionary, DBDataContext, DIC_MySecondDictionaryJournalDataSourceView.Row>, IDataSource
    {
        private DIC_MySecondDictionaryJournalDataSourceView view;

        public DIC_MySecondDictionaryJournalDataSourceView View
        {
            get
            {
                if(view == null)
                    view = new DIC_MySecondDictionaryJournalDataSourceView(this, "default");
                return view;
            }
        }

        public override BaseDataSourceView<long, DIC_MySecondDictionary, DBDataContext, DIC_MySecondDictionaryJournalDataSourceView.Row> BaseView2
        {
            get { return View; }
        }

        public DIC_MySecondDictionaryJournalDataSourceView.Row GetRecord(long id)
        {
            return View.GetRecord(id);
        }
    }

    #endregion

    #region FileManager

    

    #endregion

    #region AccessOptions

    public static partial class DIC_MySecondDictionaryAccessOptions
    {
        /// <summary>
        /// »зменение проверки прав, 
        /// если replace = true, то праверка прав возвращает isPermit, 
        /// иначе стандартна€ проверка прав и isPermit
        /// </summary>
        static partial void ChangeCheckPermit(ref bool replace, ref bool isPermit);
        
        public static bool CheckPermit()
        {
            bool replace = false;
            bool isPermit = true;
            ChangeCheckPermit(ref replace, ref isPermit);
            return isPermit;
        }
    
        /// <summary>
        /// »зменение проверки прав, 
        /// если replace = true, то праверка прав возвращает isPermit, 
        /// иначе стандартна€ проверка прав и isPermit
        /// </summary>
        static partial void ChangeCheckPermitAdd(ref bool replace, ref bool isPermit);
        
        public static bool CheckPermitAdd()
        {
            bool replace = false;
            bool isPermit = true;
            ChangeCheckPermitAdd(ref replace, ref isPermit);
            return isPermit;
        }
    
        /// <summary>
        /// »зменение проверки прав, 
        /// если replace = true, то праверка прав возвращает isPermit, 
        /// иначе стандартна€ проверка прав и isPermit
        /// </summary>
        static partial void ChangeCheckPermitEdit(ref bool replace, ref bool isPermit);
        
        public static bool CheckPermitEdit()
        {
            bool replace = false;
            bool isPermit = true;
            ChangeCheckPermitEdit(ref replace, ref isPermit);
            return isPermit;
        }
    
        /// <summary>
        /// »зменение проверки прав, 
        /// если replace = true, то праверка прав возвращает isPermit, 
        /// иначе стандартна€ проверка прав и isPermit
        /// </summary>
        static partial void ChangeCheckPermitDelete(ref bool replace, ref bool isPermit);
        
        public static bool CheckPermitDelete()
        {
            bool replace = false;
            bool isPermit = true;
            ChangeCheckPermitDelete(ref replace, ref isPermit);
            return isPermit;
        }
    }

    #endregion

    #region DIC_MySecondDictionaryItemNavigatorsInitializer

    public partial class DIC_MySecondDictionaryItemNavigatorsInitializer
    {
        protected MainPageUrlBuilder Url { get; set; }

        private DBDataContext _db;
        public DBDataContext DB
        {
            get
            {
                if (_db == null)
                {
                    _db = new DBDataContext(SpecificInstances.DbFactory.CreateConnection()) {ObjectTrackingEnabled = false};
                }

                return _db;
            }
            set { _db = value; }
        }

        partial void Initialize(IDictionary<Type, SelectedParameterNavigator.ItemNavigator> itemNavigators);

        public static void InitializeDic(IDictionary<Type, SelectedParameterNavigator.ItemNavigator> itemNavigators, MainPageUrlBuilder url)
        {
            var item = new DIC_MySecondDictionaryItemNavigatorsInitializer();
            item.Url = url;
            item.Initialize(itemNavigators);
            var i = item as IItemNavigatorsInitializer;
            if (i != null) i.Initialize(itemNavigators);
        }
    }

    #endregion
   
    #region MultipleKeyClass
    
    

    #endregion

    #region ActivityController

    namespace UserControls
    {
        using JS.LinqToJavaScript.Attributes;
    
        [SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1121:UseBuiltInTypeAlias", Justification = "Reviewed. Suppression is OK here.")]
        [JavaScriptClass(ClassName = "DIC_MySecondDictionaryActivityController", Namespace = "SampleDictionaries", BaseClassName = "JS.Web.ActivityController")]
        internal partial class DIC_MySecondDictionaryActivityController : ActivityController
        {
            List<string> _activityControls;
            
            DIC_MySecondDictionaryEdit.ControlInfo Info { get; set; }
            
            /// <summary>
            /// Name.
            /// </summary>
            [JavaScriptProperty]
            public ActivityControlName NameControl { get; set; }
            
            /// <summary>
            /// First Dictionary Value.
            /// </summary>
            [JavaScriptProperty]
            public ActivityControlrefFirstDictionary refFirstDictionaryControl { get; set; }
            
            /// <summary>
            /// Decimal Value.
            /// </summary>
            [JavaScriptProperty]
            public ActivityControlDecimalValue DecimalValueControl { get; set; }
            
            /// <summary>
            /// Boolean Value.
            /// </summary>
            [JavaScriptProperty]
            public ActivityControlBoolValue BoolValueControl { get; set; }
            
            
            
            public override IEnumerable<string> ActivityControls
            {
                get 
                {
                    InitializeActivityControls();
                    return _activityControls;
                }
            }
    
            partial void InitializeActivity();
            partial void InitializeActivityControls(List<string> activityControls);
    
            public void Initialize(Control form, Dictionary<string, object> values, DIC_MySecondDictionaryEdit.ControlInfo info)
            {
                Info = info;
                ReadOnly = info.IsRead;
                IsNew = info.IsNew;
                Control control;
                string controlID;
                string clientID;
                control = info.NameControl;
                controlID = control == null ? null : control.ID;
                clientID = control == null ? null : control.ClientID;
                NameControl = new ActivityControlName(this, "Name", controlID);
                NameControl.ClientID = clientID;
                NameControl.Control = info.NameControl;
                NameControl.ReadOnlyChanged += (sender, args) =>
                    {
                        if (info.NameControl != null)
                            info.NameControl.ReadOnly = args.Value;
                    };
                NameControl.DefaultAllowRequiredValidate = true;
                NameControl.AllowRequiredValidateChanged += Nat.Web.Controls.ExtNet.Generation.ActivityControlExtensions.AllowRequiredValidateChanged(info.NameControl);
                NameControl.DefaultReadOnly = false;
                NameControl.VisibleChanged += (sender, args) =>
                    {
                        if (info.NameControl != null)
                        {
                            info.NameControl.Hidden = !args.Value;
                            AbstractContainerExtender.SetHiddenControlContainer(info.NameControl);
                        }
                    };
                NameControl.EnabledChanged += (sender, args) =>
                    {
                        if (info.NameControl != null)
                            info.NameControl.Disabled = !args.Value;
                    };
                NameControl.AllowValidateChanged += delegate(object sender, ActivityChangedEventArgs args)
                    {
                        if (info.NameControl != null)
                            SetEnabledToValidators(form.Page, ValidationGroup, info.NameControl.ID, args.Value);
                    };
                NameControl.GetControlValueHandler = () => info.Name;
            
                control = info.refFirstDictionaryControl;
                controlID = control == null ? null : control.ID;
                clientID = control == null ? null : control.ClientID;
                refFirstDictionaryControl = new ActivityControlrefFirstDictionary(this, "refFirstDictionary", controlID);
                refFirstDictionaryControl.ClientID = clientID;
                refFirstDictionaryControl.Control = info.refFirstDictionaryControl;
                refFirstDictionaryControl.ReadOnlyChanged += (sender, args) =>
                    {
                        if (info.refFirstDictionaryControl != null)
                            info.refFirstDictionaryControl.ReadOnly = args.Value;
                    };
                refFirstDictionaryControl.DefaultAllowRequiredValidate = true;
                refFirstDictionaryControl.AllowRequiredValidateChanged += Nat.Web.Controls.ExtNet.Generation.ActivityControlExtensions.AllowRequiredValidateChanged(info.refFirstDictionaryControl);
                refFirstDictionaryControl.DefaultReadOnly = false;
                refFirstDictionaryControl.VisibleChanged += (sender, args) =>
                    {
                        if (info.refFirstDictionaryControl != null)
                        {
                            info.refFirstDictionaryControl.Hidden = !args.Value;
                            AbstractContainerExtender.SetHiddenControlContainer(info.refFirstDictionaryControl);
                        }
                    };
                refFirstDictionaryControl.EnabledChanged += (sender, args) =>
                    {
                        if (info.refFirstDictionaryControl != null)
                            info.refFirstDictionaryControl.Disabled = !args.Value;
                    };
                refFirstDictionaryControl.AllowValidateChanged += delegate(object sender, ActivityChangedEventArgs args)
                    {
                        if (info.refFirstDictionaryControl != null)
                            SetEnabledToValidators(form.Page, ValidationGroup, info.refFirstDictionaryControl.ID, args.Value);
                    };
                refFirstDictionaryControl.GetControlValueHandler = () => info.refFirstDictionary;
            
                control = info.DecimalValueControl;
                controlID = control == null ? null : control.ID;
                clientID = control == null ? null : control.ClientID;
                DecimalValueControl = new ActivityControlDecimalValue(this, "DecimalValue", controlID);
                DecimalValueControl.ClientID = clientID;
                DecimalValueControl.Control = info.DecimalValueControl;
                DecimalValueControl.ReadOnlyChanged += (sender, args) =>
                    {
                        if (info.DecimalValueControl != null)
                            info.DecimalValueControl.ReadOnly = args.Value;
                    };
                DecimalValueControl.DefaultAllowRequiredValidate = false;
                DecimalValueControl.AllowRequiredValidateChanged += Nat.Web.Controls.ExtNet.Generation.ActivityControlExtensions.AllowRequiredValidateChanged(info.DecimalValueControl);
                DecimalValueControl.DefaultReadOnly = false;
                DecimalValueControl.VisibleChanged += (sender, args) =>
                    {
                        if (info.DecimalValueControl != null)
                        {
                            info.DecimalValueControl.Hidden = !args.Value;
                            AbstractContainerExtender.SetHiddenControlContainer(info.DecimalValueControl);
                        }
                    };
                DecimalValueControl.EnabledChanged += (sender, args) =>
                    {
                        if (info.DecimalValueControl != null)
                            info.DecimalValueControl.Disabled = !args.Value;
                    };
                DecimalValueControl.AllowValidateChanged += delegate(object sender, ActivityChangedEventArgs args)
                    {
                        if (info.DecimalValueControl != null)
                            SetEnabledToValidators(form.Page, ValidationGroup, info.DecimalValueControl.ID, args.Value);
                    };
                DecimalValueControl.GetControlValueHandler = () => info.DecimalValue;
            
                control = info.BoolValueControl;
                controlID = control == null ? null : control.ID;
                clientID = control == null ? null : control.ClientID;
                BoolValueControl = new ActivityControlBoolValue(this, "BoolValue", controlID);
                BoolValueControl.ClientID = clientID;
                BoolValueControl.Control = info.BoolValueControl;
                BoolValueControl.ReadOnlyChanged += (sender, args) =>
                    {
                        if (info.BoolValueControl != null)
                            info.BoolValueControl.ReadOnly = args.Value;
                    };
                BoolValueControl.DefaultAllowRequiredValidate = true;
                BoolValueControl.AllowRequiredValidateChanged += Nat.Web.Controls.ExtNet.Generation.ActivityControlExtensions.AllowRequiredValidateChanged(info.BoolValueControl);
                BoolValueControl.DefaultReadOnly = false;
                BoolValueControl.VisibleChanged += (sender, args) =>
                    {
                        if (info.BoolValueControl != null)
                        {
                            info.BoolValueControl.Hidden = !args.Value;
                            AbstractContainerExtender.SetHiddenControlContainer(info.BoolValueControl);
                        }
                    };
                BoolValueControl.EnabledChanged += (sender, args) =>
                    {
                        if (info.BoolValueControl != null)
                            info.BoolValueControl.Disabled = !args.Value;
                    };
                BoolValueControl.AllowValidateChanged += delegate(object sender, ActivityChangedEventArgs args)
                    {
                        if (info.BoolValueControl != null)
                            SetEnabledToValidators(form.Page, ValidationGroup, info.BoolValueControl.ID, args.Value);
                    };
                BoolValueControl.GetControlValueHandler = () => info.BoolValue;
            
                InitializeControls(
                    NameControl,
                    refFirstDictionaryControl,
                    DecimalValueControl,
                    BoolValueControl);
            
                Initialize(form, values);
                FormID = Info.FormControl.ClientID;
            
                InitializeActivity();
            }
            
            public override void Initialize(Control form, Dictionary<string, object> values)
            {
                if (form == null)
                {
                    NameControl = new ActivityControlName(this, "Name", null);
                    refFirstDictionaryControl = new ActivityControlrefFirstDictionary(this, "refFirstDictionary", null);
                    DecimalValueControl = new ActivityControlDecimalValue(this, "DecimalValue", null);
                    BoolValueControl = new ActivityControlBoolValue(this, "BoolValue", null);
            
                    InitializeActivity();
                }
            
                base.Initialize(form, values);
            }
            
            protected void InitializeActivityControls()
            {
                if (_activityControls != null) return;
            
                _activityControls = new List<string>
                    {
                        "nameControl",
                        "refFirstDictionaryControl",
                        "decimalValueControl",
                        "boolValueControl",
                    };
                InitializeActivityControls(_activityControls);
            }
            
            
            
            /// <summary>
            /// Name.
            /// </summary>
            [JavaScriptClass(ClassName = "DIC_MySecondDictionaryActivityController_ActivityControlName", Namespace = "SampleDictionaries", BaseClassName = "JS.Web.ActivityController")]
            public class ActivityControlName : ActivityControlClassValue<DIC_MySecondDictionaryActivityController, String>
            {
                public ActivityControlName(DIC_MySecondDictionaryActivityController activityController, string controlID, string controlName)
                    : base(activityController, controlID, controlName)
                {
                }
            }
            
            /// <summary>
            /// First Dictionary Value.
            /// </summary>
            [JavaScriptClass(ClassName = "DIC_MySecondDictionaryActivityController_ActivityControlrefFirstDictionary", Namespace = "SampleDictionaries", BaseClassName = "JS.Web.ActivityController")]
            public class ActivityControlrefFirstDictionary : ActivityControl<DIC_MySecondDictionaryActivityController, Int64>
            {
                public ActivityControlrefFirstDictionary(DIC_MySecondDictionaryActivityController activityController, string controlID, string controlName)
                    : base(activityController, controlID, controlName)
                {
                }
            }
            
            /// <summary>
            /// Decimal Value.
            /// </summary>
            [JavaScriptClass(ClassName = "DIC_MySecondDictionaryActivityController_ActivityControlDecimalValue", Namespace = "SampleDictionaries", BaseClassName = "JS.Web.ActivityController")]
            public class ActivityControlDecimalValue : ActivityControl<DIC_MySecondDictionaryActivityController, Decimal>
            {
                public ActivityControlDecimalValue(DIC_MySecondDictionaryActivityController activityController, string controlID, string controlName)
                    : base(activityController, controlID, controlName)
                {
                }
            }
            
            /// <summary>
            /// Boolean Value.
            /// </summary>
            [JavaScriptClass(ClassName = "DIC_MySecondDictionaryActivityController_ActivityControlBoolValue", Namespace = "SampleDictionaries", BaseClassName = "JS.Web.ActivityController")]
            public class ActivityControlBoolValue : ActivityControl<DIC_MySecondDictionaryActivityController, Boolean>
            {
                public ActivityControlBoolValue(DIC_MySecondDictionaryActivityController activityController, string controlID, string controlName)
                    : base(activityController, controlID, controlName)
                {
                }
            }
        }
    }

    #endregion

    #region ValidateInformationForm

    namespace UserControls
    {
        [SuppressMessage("StyleCop.CSharp.NamingRules", "SA1306:FieldNamesMustBeginWithLowerCaseLetter", Justification = "Reviewed. Suppression is OK here.")]
        internal class DIC_MySecondDictionaryValidateInformationForm : Nat.Web.Controls.ExtNet.Validators.ValidateInformationForm
        {
            private ValidateInformation _Name;
            private ValidateInformation _refFirstDictionary;
            private ValidateInformation _DecimalValue;
            private ValidateInformation _BoolValue;
    
            public DIC_MySecondDictionaryValidateInformationForm(Control form)
                : base(form)
            {
            }
    
            public ValidateInformation Name
            {
                get
                {
                    if (_Name == null)
                    {
                        _Name = new ValidateInformation();
                        Validators["Name"] = _Name;
                    }
            
                    return _Name;
                }
            }
            
            public ValidateInformation refFirstDictionary
            {
                get
                {
                    if (_refFirstDictionary == null)
                    {
                        _refFirstDictionary = new ValidateInformation();
                        Validators["refFirstDictionary"] = _refFirstDictionary;
                    }
            
                    return _refFirstDictionary;
                }
            }
            
            public ValidateInformation DecimalValue
            {
                get
                {
                    if (_DecimalValue == null)
                    {
                        _DecimalValue = new ValidateInformation();
                        Validators["DecimalValue"] = _DecimalValue;
                    }
            
                    return _DecimalValue;
                }
            }
            
            public ValidateInformation BoolValue
            {
                get
                {
                    if (_BoolValue == null)
                    {
                        _BoolValue = new ValidateInformation();
                        Validators["BoolValue"] = _BoolValue;
                    }
            
                    return _BoolValue;
                }
            }
    
            public void AddDefaultValidatorsForName(DIC_MySecondDictionaryEdit.ControlInfo info)
            {
                Name.RequiredValidatorPropertieses.Add(new RequiredValidatorProperties { InitialValue = "" });
                if (Validators.ContainsKey("Name"))
                {
                    var validator = Name.RequiredValidatorPropertieses.FirstOrDefault();
                    if (validator != null && string.IsNullOrEmpty(validator.ErrorMessageInSummary))
                        validator.ErrorMessageInSummary = DIC_MySecondDictionaryEdit.GetRequiredMessage_Name();
                    if (validator != null && validator.InitialValue == null)
                        validator.InitialValue = "";
                }
            }
            
            public void AddDefaultValidatorsForrefFirstDictionary(DIC_MySecondDictionaryEdit.ControlInfo info)
            {
                refFirstDictionary.RequiredValidatorPropertieses.Add(new RequiredValidatorProperties { InitialValue = "" });
                if (Validators.ContainsKey("refFirstDictionary"))
                {
                    var validator = refFirstDictionary.RequiredValidatorPropertieses.FirstOrDefault();
                    if (validator != null && string.IsNullOrEmpty(validator.ErrorMessageInSummary))
                        validator.ErrorMessageInSummary = DIC_MySecondDictionaryEdit.GetRequiredMessage_refFirstDictionary();
                    if (validator != null && validator.InitialValue == null)
                        validator.InitialValue = "";
                }
            }
            
            public void AddDefaultValidatorsForDecimalValue(DIC_MySecondDictionaryEdit.ControlInfo info)
            {
                DecimalValue.RegexValidatorPropertieses.Add(
                    new RegexValidatorProperties 
                        {
                            ErrorMessage = Nat.Web.Controls.Properties.Resources.SNotCorrectNumber,
                            ErrorMessageInSummary = DIC_MySecondDictionaryEdit.GetNotCorrectNumberMessage_DecimalValue(),
                            RegularExpression = @"\-?\d{0,8}((\.|,)\d{0,2})?",
                        });
                if (Validators.ContainsKey("DecimalValue"))
                {
                    var validator = DecimalValue.RequiredValidatorPropertieses.FirstOrDefault();
                    if (validator != null && string.IsNullOrEmpty(validator.ErrorMessageInSummary))
                        validator.ErrorMessageInSummary = DIC_MySecondDictionaryEdit.GetRequiredMessage_DecimalValue();
                    if (validator != null && validator.InitialValue == null)
                        validator.InitialValue = "";
                }
            }
            
            public void AddDefaultValidatorsForBoolValue(DIC_MySecondDictionaryEdit.ControlInfo info)
            {
                if (Validators.ContainsKey("BoolValue"))
                {
                    var validator = BoolValue.RequiredValidatorPropertieses.FirstOrDefault();
                    if (validator != null && string.IsNullOrEmpty(validator.ErrorMessageInSummary))
                        validator.ErrorMessageInSummary = DIC_MySecondDictionaryEdit.GetRequiredMessage_BoolValue();
                    if (validator != null && validator.InitialValue == null)
                        validator.InitialValue = "";
                }
            }
        }
    }

    #endregion

    #region TableRowsConsts

    public static class DIC_MySecondDictionaryRowsConsts
    {
    
    }

    #endregion

    #region NavigatorControl

    public partial class DIC_MySecondDictionaryNavigatorControl : BaseNavigatorControl<DIC_MySecondDictionaryNavigatorValues>
    {
        public override Type NavigatorType { get { return typeof(DIC_MySecondDictionaryNavigatorInfo); } }
    }

    #endregion

    #region NavigatorValues

    public partial class DIC_MySecondDictionaryNavigatorValues : BaseNavigatorValues
    {
        public long? DIC_MySecondDictionary
        {
            get
            {
                if (!Values.ContainsKey(typeof(DIC_MySecondDictionary))) return null;
                return (long?)Values[typeof(DIC_MySecondDictionary)];
            }
            set
            {
                Values[typeof(DIC_MySecondDictionary)] = value;
            }
        }
        
        public long? DIC_MyFirstDictionary
        {
            get
            {
                if (!Values.ContainsKey(typeof(DIC_MyFirstDictionary))) return null;
                return (long?)Values[typeof(DIC_MyFirstDictionary)];
            }
            set
            {
                Values[typeof(DIC_MyFirstDictionary)] = value;
            }
        }
    
        protected override string TableName { get { return "DIC_MySecondDictionary"; } }
    }

    #endregion

    #region NavigatorInfoAllClasses

    public partial class DIC_MySecondDictionaryNavigatorInfo : BaseNavigatorInfo
    {
        public override Type TableType { get { return typeof(DIC_MySecondDictionary); } }
        public override Type DataSourceViewType { get { return typeof(DIC_MySecondDictionaryJournalDataSourceView); } }
        public override string TableName { get { return "DIC_MySecondDictionary"; } }
        public override string Header { get { return DIC_MySecondDictionaryResources.Header; } }
        public override string HeaderToChilds { get { return ""; } }
        public override string HeaderToParent { get { return ""; } }
        public override string ReferenceName { get { return ""; } }
        
        public override void Initialize()
        {
            BaseInitialize();
            
            ParentNavigators.Add(GetNavigator(typeof(FK_DIC_MySecondDictionary_DIC_MyFirstDictionary_refFirstDictionaryNavigatorInfo)));
        }
        
        
    }
    
    public partial class FK_DIC_MySecondDictionary_DIC_MyFirstDictionary_refFirstDictionaryNavigatorInfo : DIC_MyFirstDictionaryNavigatorInfo
    {
        public override string HeaderToChilds { get { return DIC_MyFirstDictionaryResources.FK_DIC_MySecondDictionary_DIC_MyFirstDictionary_refFirstDictionary_ToChildsHeader; } }
        public override string HeaderToParent { get { return DIC_MyFirstDictionaryResources.FK_DIC_MySecondDictionary_DIC_MyFirstDictionary_refFirstDictionary_ToParentHeader; } }
        public override string ReferenceName { get { return "DIC_MyFirstDictionary_refFirstDictionary"; } }
    }

    #endregion

    #region ViewModeClass

    public enum ViewModeDIC_MySecondDictionary
    {
        none,
    }

    #endregion

    #region AdditionalRowInfoClasses

    

    #endregion

    #region TableParametersClasses

    

    #endregion

    #region TableInterface

    

    #endregion

    #region GetCacheNamesClass

    public static class DIC_MySecondDictionaryCacheNames
    {
        public static string Get_refFirstDictionary(DataContext db, long? rowValue)
        {
            return CacheQueries.GetNameCached<DIC_MyFirstDictionary, long?, string>(
                       db, rowValue, (r, id) => r.id == id,
                       r => r.Name,
                       new ExpressionCulture<Func<DIC_MyFirstDictionary, string>>("kk-kz", r => r.Name));
        }
    
        public static string Get_refFirstDictionary(DataContext db, DIC_MySecondDictionary row)
        {
            long? rowValue;
            rowValue = row.refFirstDictionary;
    
            return Get_refFirstDictionary(db, rowValue);
        }
    
        public static string GetByTime_refFirstDictionary(DataContext db, long? rowValue)
        {
            return CacheQueries.GetNameCached<DIC_MyFirstDictionary, long?, string>(
                       DateTime.Now.AddSeconds(20), Cache.NoSlidingExpiration, CacheItemPriority.BelowNormal,
                       db, rowValue, (r, id) => r.id == id,
                       r => r.Name,
                       new ExpressionCulture<Func<DIC_MyFirstDictionary, string>>("kk-kz", r => r.Name));
        }
    
        public static string GetByTime_refFirstDictionary(DataContext db, DIC_MySecondDictionary row)
        {
            long? rowValue;
            rowValue = row.refFirstDictionary;
    
            return GetByTime_refFirstDictionary(db, rowValue);
        }
    
        public static string GetRu_refFirstDictionary(DataContext db, long? rowValue)
        {
            return CacheQueries.GetNameCached<DIC_MyFirstDictionary, long?, string>(db, rowValue, (r, id) => r.id == id, r => r.Name);
        }
    
        public static string GetNameRu(DataContext db, long? rowValue)
        {
            return CacheQueries.GetNameCached<DIC_MySecondDictionary, long?, string>(
                        db, rowValue, (r, id) => r.id == id, r => r.Name);
        }
    
        public static string GetName(DataContext db, long? rowValue)
        {
            return CacheQueries.GetNameCached<DIC_MySecondDictionary, long?, string>(
                        db, 
                        rowValue, 
                        (r, id) => r.id == id, 
                        r => r.Name, 
                        new ExpressionCulture<Func<DIC_MySecondDictionary, string>>("kk-kz", r => r.Name));
        }
        
        public static void ClearCache(DataContext db, long? rowValue)
        {
            if (rowValue == null)
                return;
            CacheQueries.ClearCache<DIC_MySecondDictionary, long?, string>(
                db,
                rowValue.Value, 
                (r, id) => r.id == id, 
                r => r.Name, 
                new ExpressionCulture<Func<DIC_MySecondDictionary, string>>("kk-kz", r => r.Name));
        }
    }

    #endregion

    #region ComboBoxViews

    

    #endregion
}
#pragma warning restore