/*
 * Generated by: Sergey.Shpakovskiy
 * Generated at: 1.0.0.2
 * Copyright © JSC NAT Kazakhstan 2011
 */
#pragma warning disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Data.SqlClient;
using System.Drawing.Design;
using System.Globalization;
using System.Linq;
using System.Security.Principal;
using System.Text;
using System.Xml.Linq;
using System.Web;
using System.Web.Compilation;
using System.Web.Script.Serialization;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.IO;
using System.Net.Mail;
using System.Net;
using System.Collections.Specialized;
using System.Web.Configuration;
using SampleDictionaries.Properties;


using Nat.Tools.Specific;
using Nat.Web.Controls;
using Nat.Web.Controls.BaseLogic;
using Nat.Web.Controls.Data;
using Nat.Web.Controls.DateTimeControls;
using Nat.Web.Controls.GenerationClasses;
using Nat.Web.Controls.GenerationClasses.Data;
using Nat.Web.Controls.GenerationClasses.Navigator;
using Nat.Web.Controls.HistoryFilters;
using Nat.Web.Controls.Preview;
using Nat.Web.Controls.SelectValues;
using Nat.Web.Tools;
using Nat.Web.Tools.Security;
using Nat.Web.Tools.WorkFlow;
using AccessOptions = SampleDictionaries.DIC_MySecondDictionaryAccessOptions;
using TableResources = SampleDictionaries.Properties.TableResources;
using SampleDictionaries;
using SampleDictionaries.UserControls;
using SampleDictionaries.Properties;
using Nat.Web.Tools.MailMessageContent;
using SampleDictionaries.Security;
using Nat.Web.Tools.ExtNet;
using Nat.Web.Tools.ExtNet.Extenders;
using Nat.Web.Tools.ExtNet.ExtNetConfig;
using Ext.Net;
using NullableTextBox = Ext.Net.NumberField;
using TextBox = Ext.Net.TextField;
using Label = Ext.Net.Label;
using DropDownListExt = Ext.Net.ComboBox;
using CheckBox = Ext.Net.Checkbox;
using RadioButton = Ext.Net.Radio;
using RadioButtonList = Ext.Net.RadioGroup;
using ImageButton = Ext.Net.ImageButton;
using HyperLink = Ext.Net.HyperLink;
using LinkButton = Ext.Net.LinkButton;
using DatePicker = Ext.Net.DateField;
using Panel = Ext.Net.Panel;
using Container = Ext.Net.Container;
using Newtonsoft.Json.Linq;
using AdditionalButtons = Nat.Web.Controls.ExtNet.AdditionalButtons;
using BrowseFilterParameters = Nat.Web.Tools.ExtNet.ExtNetBrowseFilterParameters;
using DBDataContext = SampleDictionaries.DBDataContext;

namespace SampleDictionaries.UserControls
{
    /// <summary>
    /// Контрол для просмотра, редактирования и добавления записей таблицы "My Second Dictionary" (DIC_MySecondDictionary)
    /// </summary>
    [DefaultEvent("SelectedIndexChanged")]
    [ControlValueProperty("SelectedValue")]
    public partial class DIC_MySecondDictionaryEdit : Nat.Web.Controls.ExtNet.Generation.AbstractUserControl, IAccessControl, IScriptControl
    {
        #region Fields

        private DBDataContext _db;
        private long? refDIC_MySecondDictionary;
        private IEnumerable<ILogic> logics = new ILogic[] {  };
        private bool _isStartAction;
        private List<string> _addErrorMessages;
        private ControlInfo _info;
        private bool editlogicExecuted;
        private bool readlogicExecuted;
        private bool insertlogicExecuted;
        private bool _setDefaultValues;
        private bool _isNoPermit;
        private bool _selectedRowInited;
        private DIC_MySecondDictionaryJournalDataSourceView.Row _selectedRow;
        private DIC_MySecondDictionary _currentRow;
        private long? refLogMessage;
        private bool selectedValueInitialized;

        #endregion

        #region Partials

        partial void ReadLogic();
        partial void EditLogic();
        partial void InsertLogic();
        partial void EditInsertLogic();
        partial void Logic();
        partial void OnUpdating(DIC_MySecondDictionary newItem, DIC_MySecondDictionary originalItem);
        partial void OnInserting(DIC_MySecondDictionary newItem);
        partial void OnContextCreating(LinqDataSourceContextEventArgs e);
        partial void OnUpdated(LinqDataSourceStatusEventArgs e);
        partial void OnInserted(LinqDataSourceStatusEventArgs e);
        partial void OnDispose();
        partial void UpdateRefDIC_MySecondDictionary(DIC_MySecondDictionary row);
        partial void GetDefaultProperties(Dictionary<Type, List<string>> typeProperies);
        partial void GenerateAdditionalButtons(AdditionalButtons buttons);
        partial void GetBrowseFilterParameters(string fieldName, BrowseFilterParameters parameters);
        partial void CustomValidate_refFirstDictionary(long? value, BaseInformationValues information, CancelEventArgs args);
        partial void GetBrowseFilterParameters_refFirstDictionary(BrowseFilterParameters parameters);
        partial void GetValidators_Name(ValidateInformation validateInformation);
        partial void GetValidators_refFirstDictionary(ValidateInformation validateInformation);
        partial void GetValidators_DecimalValue(ValidateInformation validateInformation);
        partial void GetValidators_BoolValue(ValidateInformation validateInformation);
        partial void ChangeLogTypeAdd(ref LogMessageType logType);
        partial void ChangeLogTypeLook(ref LogMessageType logType);
        partial void ChangeLogTypeEdit(ref LogMessageType logType);
        partial void ChangeLogTypeAdd(ref long logType);
        partial void ChangeLogTypeLook(ref long logType);
        partial void ChangeLogTypeEdit(ref long logType);
        partial void ChangeLogContent(ref string content, DIC_MySecondDictionary newItem, DIC_MySecondDictionary oldItem);
        partial void ChangeLogContentAdd(ref string content, DIC_MySecondDictionary newItem);
        partial void ChangeLogContentLook(ref string content, DIC_MySecondDictionary item);
        partial void ChangeLogContentEdit(ref string content, DIC_MySecondDictionary newItem, DIC_MySecondDictionary oldItem);
        partial void InitControlPanels();
        partial void OnPreRender();
        partial void OnInsertedPartial(DIC_MySecondDictionary newRow, bool inserted);
        partial void OnUpdatedPartial(DIC_MySecondDictionary newRow, DIC_MySecondDictionary originalItem, bool updated);
        partial void RemoteValidation_Name(JValue value, RemoteValidationEventArgs e);
        partial void RemoteValidation_refFirstDictionary(JValue value, RemoteValidationEventArgs e);
        partial void RemoteValidation_DecimalValue(JValue value, RemoteValidationEventArgs e);
        partial void RemoteValidation_BoolValue(JValue value, RemoteValidationEventArgs e);

        #endregion

        #region Properties

        public DBDataContext DB
        {
            get
            {
                if (_db == null)
                {
                    _db = new DBDataContext(SpecificInstances.DbFactory.CreateConnection());
                }
        
                return _db;
            }
        }
        
        private List<string> AddErrorMessages
        {
            get
            {
                if (_addErrorMessages == null)
                    _addErrorMessages = source.View.AllowAddRowForTableTypes(NavigatorControl.Values, DIC_MySecondDictionaryResources.Header);
        
                return _addErrorMessages;
            }
        }
        
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        [Browsable(false)]
        public ControlInfo Info
        {
            get
            {
                if (_info == null) 
                    _info = new ControlInfo(this){ DB = DB };
        
                return _info;
            }
        }
        
        protected bool RecordIsNew
        {
            get { return IsNew; }
        }
        
        protected bool RecordIsEditing
        {
            get { return SelectedValueKey != null && !IsNew && !IsRead; }
        }
        
        /// <summary>
        /// Действие логики выполняеться на начало редактирования или добавления записи, 
        /// true только однажды, при начале действий (открытии на редактирования или добавление).
        /// </summary>
        protected bool IsStartAction
        {
            get { return _isStartAction; }
        }
        
        public DIC_MySecondDictionaryJournalDataSourceView.Row SelectedRow
        {
            get
            {
                if (_selectedRow == null && !_selectedRowInited)
                {
                    if (string.IsNullOrEmpty(hfid.Text))
                        return null;
        
                    var key = Convert.ToInt64(hfid.Value);
                    _selectedRow = source.View.GetSelect(key).FirstOrDefault();
                    _selectedRowInited = true;
                }
        
                return _selectedRow;
            }
        }
        
        public DIC_MySecondDictionaryJournalDataSourceView.LookupValues SelectedLookup
        {
            get
            {
                if (ViewState["SelectedLookup"] != null)
                    return (DIC_MySecondDictionaryJournalDataSourceView.LookupValues)ViewState["SelectedLookup"];
        
                var row = SelectedRow;
                if (row == null || row.Lookup == null)
                    return null;
        
                ViewState["SelectedLookup"] = row.Lookup;
                return row.Lookup;
            }
        }
        
        private DIC_MySecondDictionary currentRow
        {
            get 
            {
                if (_currentRow == null && SelectedRow != null)
                    _currentRow = SelectedRow.Item;
        
                return _currentRow;
            }
            set { _currentRow = value; }
        }
        
        private bool HasErrors { get; set; }
        
        private string SessionKey
        { 
            get { return string.IsNullOrEmpty(hfSessionKey.Text) ? (hfSessionKey.Text = Request.Form[hfSessionKey.UniqueID] ?? Guid.NewGuid().ToString("N")) : hfSessionKey.Text; }
            set { hfSessionKey.Text = value; }
        }
        
        public override bool IsNew
        {
            get { return SelectedValueKey == null && base.IsNew; }
        }
        
        private DIC_MySecondDictionaryActivityController ActivityController { get; set; }
        
        private bool ActivityControllerInitialized { get; set; }
        
        private bool ValidateInformationFormInitialized { get; set; }
        
        private DIC_MySecondDictionaryValidateInformationForm ValidateInformationForm { get; set; }

        [Browsable(false)]
        public long? SelectedValueKey
        {
            get 
            {
                if (!IsPostBack && !selectedValueInitialized && Url.QueryParameters.ContainsKey("refDIC_MySecondDictionary"))
                {
                    selectedValueInitialized = true;
                    string value = Url.QueryParameters["refDIC_MySecondDictionary"];
                    if (!string.IsNullOrEmpty(value))
                        SelectedValueKey = Convert.ToInt64(value);
                }

                if (string.IsNullOrEmpty(hfid.Text))
                    return null;

                var key = Convert.ToInt64(hfid.Value);
                return key;
            }

            private set
            {
                hfid.Value = value == null 
                    ? string.Empty
                    : value.ToString();
            }
        }

        #region ISelectedValue Members
        
        [Browsable(false)]
        public override long SelectedValueLong
        {
            get 
            { 
                throw new NotImplementedException();
            }
        }
        
        public long? ParentID { get; set; }
        public bool IsSelectParentRows { get; set; }
        
        [Browsable(false)]
        public long? SelectedValueOrParentValue
        {
            get 
            {
                return SelectedValueKey;
            }
        }
        
        [Browsable(false)]
        public override object SelectedValue
        {
            get { return SelectedValueKey; }
        }
        
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden), Browsable(false)]
        public override DataKey SelectedDataKey
        {
            get 
            {
                throw new NotImplementedException();
            }
        }
        
        [DefaultValue("ID")]
        [Editor(
            "System.Web.UI.Design.WebControls.DataFieldEditor, System.Design, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
            , typeof(UITypeEditor))]
        [TypeConverter(typeof(StringArrayConverter))]
        [Category("Data")]
        public override string[] DataKeyNames
        {
            get 
            { 
                throw new NotImplementedException();
            }
        
            set
            { 
                throw new NotImplementedException();
            }
        }
        
        public override Type TableType
        {
            get { return typeof(DIC_MySecondDictionary); }
        }
        
        #endregion
        
        #endregion
        
        #region Methods
        
        public override void Dispose()
        {
            if (DB.Transaction != null)
                RollbackDBTransaction();
        
            DB.Dispose();
            OnDispose();
            base.Dispose();
        }
        
        protected DbTransaction BeginTransaction()
        {
            if (DB.Connection.State == ConnectionState.Closed)
                DB.Connection.Open();
            var transaction = DB.Transaction = DB.Connection.BeginTransaction();
            InitTransaction();
            return transaction;
        }
        
        protected void CommitDBTransaction()
        {
            if (DB.Transaction.Connection != null)
                DB.Transaction.Commit();
            EndTransaction();  
        }
        
        protected void RollbackDBTransaction()
        {
            if (DB.Transaction.Connection != null)
                DB.Transaction.Rollback();
            EndTransaction();  
        }
        
        protected void EndTransaction()
        {
            DB.Transaction?.Dispose();
            DB.Transaction = null;
            InitTransaction();
            
            if (DB.Connection.State == ConnectionState.Open)
                DB.Connection.Close();
        }
        
        protected void InitTransaction()
        {
            source.View.InitTransaction = DB.Transaction;
            jdsrefFirstDictionary.BaseView.InitTransaction = DB.Transaction;
        }
        
        protected void InitConnection()
        {
            source.View.InitConnection = DB.Connection;
            jdsrefFirstDictionary.BaseView.InitConnection = DB.Connection;
        }
        
        protected bool AddErrorMessage(IEnumerable<string> errors)
        {
            if (errors != null && errors.Any())
            {
                foreach (var message in errors)
                    AddErrorMessage(message);
                return true;
            }
        
            return false;
        }
        
        
        private Dictionary<Type, List<string>> GetDefaultProperties()
        {
            var properties = (Dictionary<Type, List<string>>)Cache["DIC_MySecondDictionary_DefaultProperties"];
            if (properties == null)
            {
                properties = new Dictionary<Type, List<string>>();
        
                foreach (var property in typeof(DIC_MySecondDictionary).GetProperties())
                {
                    var attributes = (AssociationAttribute[])property.GetCustomAttributes(typeof(AssociationAttribute), false);
                    if(attributes != null && attributes.Length == 1 && attributes[0].IsForeignKey && !"refHistory".Equals(attributes[0].ThisKey))
                    {
                        if(!properties.ContainsKey(property.PropertyType))
                            properties.Add(property.PropertyType, new List<string>());
                        properties[property.PropertyType].Add(attributes[0].ThisKey);
                    }
                }
        
                GetDefaultProperties(properties);
                Cache["DIC_MySecondDictionary_DefaultProperties"] = properties;
            }
        
            return properties;
        }
        
        protected string GetBrowseUrl(string fieldName, object value, long? id)
        {
            var parameters = new BrowseFilterParameters();
            string selectColumnName = null;
            switch (fieldName)
            {
                case "refFirstDictionary":
                    GetBrowseFilterParameters_refFirstDictionary(parameters);
                    GetBrowseFilterParameters("refFirstDictionary", parameters);
                    break;
        
            }
        
            var jss = new JavaScriptSerializer();
            return jss.Serialize(new Triplet(parameters.ClientControlParameters, parameters.ClientValueParameters, selectColumnName));
        }
        
        protected virtual void EnsureLogicExecute()
        {
            if (SelectedValueKey == null && !IsNew)
                return;
            var executing = false;
            Trace.Write("DIC_MySecondDictionary", "DIC_MySecondDictionaryEdit.EnsureLogicExecute.Begin");
            if (SelectedValueKey != null && IsRead && !readlogicExecuted)
            {
                readlogicExecuted = true;
                Info.IsRead = true;
                Info.ComputeReadOnlyFields(true);
                ReadLogic();
                Logic();
                executing = true;
            }
        
            if (SelectedValueKey != null && !IsNew && !IsRead && !editlogicExecuted)
            {
                editlogicExecuted = true;
                Info.IsEdit = true;
                Info.ComputeReadOnlyFields(true);
                UploadFiles();
                ExecuteEditLogic();
                EditInsertLogic();
                Logic();
                InitializeFilterParameters();
                executing = true;
            }
        
            if (IsNew && !insertlogicExecuted)
            {
                insertlogicExecuted = true;
                Info.IsInsert = true;
                if (IsStartAction)
                    SetDefaultValues();
                Info.ComputeReadOnlyFields(true);
                UploadFiles();
                ExecuteInsertLogic();
                EditInsertLogic();
                Logic();
                InitializeFilterParameters();
                executing = true;
            }
        
            if (executing)
            {
                foreach (var logic in logics)
                {
                    logic.IsEdit = SelectedValueKey != null && !IsNew && !IsRead;
                    logic.IsNew = IsNew;
                    logic.IsStartAction = IsStartAction;
                    logic.ControlInfo = Info;
                    logic.NavigatorValues = NavigatorControl.Values;
                    logic.Url = Url;
                    logic.Logic();
                }
        
                Info.ComputeReadOnlyFields(false);
                if (IsStartAction && IsNew)
                    ValidateReferences(true);
            }
        
            Trace.Write("DIC_MySecondDictionary", "DIC_MySecondDictionaryEdit.EnsureLogicExecute.End");
        }
        
        protected virtual void ExecuteInsertLogic()
        {
            InsertLogic();
        }
        
        protected virtual void ExecuteEditLogic()
        {
            EditLogic();
        }
        
        private void InitializeFilterParameters()
        {
            BrowseFilterParameters parameters;
        }
        
        /// <summary>
        /// Проверка ссылок на валидность.
        /// </summary>
        /// <param name="isDefault">Флаг о том что заполнены поля по умолчанию.</param>
        private bool ValidateReferences(bool isDefault)
        {
            var isValid = true;
            Trace.Write("DIC_MySecondDictionary", "DIC_MySecondDictionaryEdit.ValidateReferences.Begin");
        
            if (Info.refFirstDictionary != null)
            {
                var value = Info.refFirstDictionary.Value;
                CancelEventArgs args = new RecordValidateArgs(false, IsNew || SelectedRow.Item.refFirstDictionary != Info.refFirstDictionary);
                var info = jdsrefFirstDictionary.BaseView.Validate(value, (RecordValidateArgs)args);
                if (args.Cancel)
                {
                    AddErrorMessage(string.Format(
                                        isDefault
                                            ? Nat.Web.Controls.Properties.Resources.ENotCorrectDefaultValue
                                            : Nat.Web.Controls.Properties.Resources.ENotCorrectValue,
                                        GenerationHelper.GetHeaderName(DIC_MySecondDictionaryResources.refFirstDictionary__Group, DIC_MySecondDictionaryResources.refFirstDictionary__Header)));
                    isValid = false;
                }
        
                if (info != null)
                {
                    if (!info.IsValid)
                    {
                        AddErrorMessage(string.Format(Nat.Web.Controls.Properties.Resources.SFieldHasError,
                                                      GenerationHelper.GetHeaderName(DIC_MySecondDictionaryResources.refFirstDictionary__Group, DIC_MySecondDictionaryResources.refFirstDictionary__Header))
                                        + info.IconHtml + info.MessageHtml);
                        isValid = false;
                    }
                    else
                    {
                        args = new CancelEventArgs();
                        CustomValidate_refFirstDictionary(value, info, args);
                        if (args.Cancel) isValid = false;
                    }
                }
            }
        
            Trace.Write("DIC_MySecondDictionary", "DIC_MySecondDictionaryEdit.ValidateReferences.End");
            return isValid;
        }

        protected IFilterControl GetFilterControl(DBDataContext db)
        {
            var filterControlInternal = new DIC_MySecondDictionaryFilter { Page = Page };
            filterControlInternal.SetUrl(Url);
            filterControlInternal.SetDB(db);
            filterControlInternal.SelectedID = SelectedValueKey;
            filterControlInternal.ShowHistory = true;
            return filterControlInternal;
        }

        
        
        /// <summary>
        /// Сохранение формы.
        /// </summary>
        /// <param name="sender">Объект вызвавший событие.</param>
        /// <param name="e">Параметры события.</param>
        protected void SaveData(object sender, DirectEventArgs e)
        {
            DIC_MySecondDictionary originalItem = null;
        
            using (var db = new DBDataContext(DB.Connection ?? SpecificInstances.DbFactory.CreateConnection()))
            {
                // Если запись редактируется, то получаем строку из базы и проверяем версии записи
                if (!IsNew)
                {
                    source.View.DB.Dispose();
                    source.View.DB = db;
                    var row = source.View.GetSelect(SelectedValueKey.Value)
                        .Select(r => new { r.Item, r.CanEdit })
                        .FirstOrDefault();
                    if (row == null)
                    {
                        AddErrorMessage(Nat.Web.Controls.Properties.Resources.ERowIsDeletedOrNotHavePermissions);
                        source.View.DB = null;
                        return;
                    }
                    else if (!row.CanEdit)
                    {
                        AddErrorMessage(Nat.Web.Controls.Properties.Resources.EDoesNotHavePermitForEdit);
                        source.View.DB = null;
                        return;
                    }
        
                    originalItem = row.Item;
                    source.View.DB = new DBDataContext(DB.Connection ?? SpecificInstances.DbFactory.CreateConnection());
                    if (originalItem == null)
                    {
                        AddErrorMessage(Nat.Web.Controls.Properties.Resources.ERowIsDeletedOrNotHavePermissions);
                        return;
                    }
                    
                    var rowVersion = Convert.ToBase64String(originalItem.RowVersion.ToArray());
                    if (rowVersion != rowVersionHiddenField.Text)
                    {
                        // todo: подумать о реализации конкурентных изменений
                        AddErrorMessage(Nat.Web.Controls.Properties.Resources.ERecordModifiedByOther);
                        return;
                    }
                }
        
                if (SaveData(originalItem))
                {
                    if (!IsNew && Url.QueryParameters.ContainsKey("MultipleEdit"))
                    {
                        var keys = Url.QueryParameters["MultipleEdit"].Split(new[] {','}, StringSplitOptions.RemoveEmptyEntries).Select(r => Convert.ToInt64(r)).ToArray();
                        var data = source.View.GetSelect().Where(r => keys.Contains(r.id)).Where(r => r.CanEdit);
                        foreach(var otherRow in data)
                            SaveData(otherRow.Item);
                    }
        
                    IsNew = false;
                    IsRead = false;
                    Info.IsEdit = true;
                    editlogicExecuted = false;
                    insertlogicExecuted = false;
                    readlogicExecuted = false;
                    source.View.DB.Dispose();
                    source.View.DB = new DBDataContext(DB.Connection ?? SpecificInstances.DbFactory.CreateConnection());
                    UpdateForm(true);
        
                    ResourceManager.AddInstanceScript(
                        string.Format(
                            "if (window.frameElement != null && window.frameElement.CloseOnSaveSuccessfull != null)\r\n" +
                            "    window.frameElement.CloseOnSaveSuccessfull({0});",
                            SelectedValueKey));
                }
            }
        }
        
        protected bool SaveData(DIC_MySecondDictionary originalItem)
        {
            // Выполняем логику формы
            EnsureLogicExecute();
        
            // Валидируем
            var valid = ValidateInfo();
            var newItem = GetNewItem(originalItem);
            valid = valid & ValidateReferences(false);
            if (!valid) return false;
        
            // Добавляем запись в модель на обновление или добавление
            if (IsNew)
            {
                if (!AccessOptions.CheckPermitAdd())
                {
                    AddErrorMessage(Nat.Web.Controls.Properties.Resources.EDoesNotHavePermitForAdd);
                    return false;
                }
        
                DB.DIC_MySecondDictionaries.InsertOnSubmit(newItem);
                OnInserting(newItem);
                Inserting(newItem);
            }
            else
            {
                DB.DIC_MySecondDictionaries.Attach(newItem, originalItem);
                OnUpdating(newItem, originalItem);
                Updating(originalItem, newItem);
            }
        
            // todo: разрулить Exception на базе
            // Обновляем в БД
            try
            {
                DB.SubmitChanges();
        
                // Вызываем события о том что обновленно
                if (IsNew)
                {
                    OnInserted(true, newItem);
                    OnInsertedPartial(newItem, true);
                }
                else
                {
                    OnUpdated(true, newItem);
                    OnUpdatedPartial(newItem, originalItem, true);
                }
        
                SelectedValueKey = refDIC_MySecondDictionary;
                return true;
            }
            catch (SqlException ex)
            {
                if (ex.Errors[0].Number > 50000)
                    AddErrorMessage(ex.Errors[0].Message);
                else
                    X.Msg.Alert("Exception", ex.ToString()).Show();
                return false;
            }
            catch(Exception ex)
            {
                X.Msg.Alert("Exception", ex.ToString()).Show();
                return false;
            }
        }
        
        /// <summary>
        /// Получение новой строки для вставки или обновления.
        /// </summary>
        /// <param name="originalValues">Строка с оригинальными значениями.</param>
        protected DIC_MySecondDictionary GetNewItem(DIC_MySecondDictionary originalValues)
        {
            DIC_MySecondDictionary newItem;
        
            // Создание нового элемента
            if (originalValues == null)
                newItem = new DIC_MySecondDictionary();
            else
            {
                // Создание нового элемента и копирование из оригинала значений полей
                newItem = new DIC_MySecondDictionary
                    {
                        id = originalValues.id,
                        RowVersion = originalValues.RowVersion,
                    };
            }
        
            // Получение значений полей из Info
            if (!string.IsNullOrEmpty(Info.Name))
                newItem.Name = Info.Name;
            else
                newItem.Name = null;
            if (Info.refFirstDictionary != null)
                newItem.refFirstDictionary = (Int64)Info.refFirstDictionary;
            else
                newItem.refFirstDictionary = default(Int64);
            if (Info.DecimalValue != null)
                newItem.DecimalValue = Info.DecimalValue;
            else
                newItem.DecimalValue = null;
            if (Info.BoolValue != null)
                newItem.BoolValue = (Boolean)Info.BoolValue;
            else
                newItem.BoolValue = default(Boolean);
        
            return newItem;
        }
        
        /// <summary>
        /// Проверка данных на валидность.
        /// </summary>
        protected bool ValidateInfo()
        {
            EnsureActivityControllerInitialized();
            ActivityController.ComputeActivities();
            EnsureValidateInformationFormInitialized();
        
            var valid = ValidateInformationForm.Validate();
            valid = valid & ValidateField_Name();
            valid = valid & ValidateField_refFirstDictionary();
            valid = valid & ValidateField_DecimalValue();
            valid = valid & ValidateField_BoolValue();
        
            return valid;
        }
        
        partial void ValidateField_Name(ref bool valid);
        
        private bool ValidateField_Name()
        {
            var valid = true;
            if (ActivityController.NameControl.AllowRequiredValidate || ValidateInformationForm.IsRequired("Name"))
                valid = !string.IsNullOrEmpty(Info.Name);
        
            if (!valid)
            {
                AddErrorMessage(GetRequiredMessage_Name());
                return false;
            }
        
            if (ActivityController.NameControl.AllowValidate)
                ValidateField_Name(ref valid);
        
            return valid;
        }
        
        partial void ValidateField_refFirstDictionary(ref bool valid);
        
        private bool ValidateField_refFirstDictionary()
        {
            var valid = true;
            if (ActivityController.refFirstDictionaryControl.AllowRequiredValidate || ValidateInformationForm.IsRequired("refFirstDictionary"))
                valid = Info.refFirstDictionary != null;
        
            if (!valid)
            {
                AddErrorMessage(GetRequiredMessage_refFirstDictionary());
                return false;
            }
        
            if (ActivityController.refFirstDictionaryControl.AllowValidate)
                ValidateField_refFirstDictionary(ref valid);
        
            return valid;
        }
        
        partial void ValidateField_DecimalValue(ref bool valid);
        
        private bool ValidateField_DecimalValue()
        {
            var valid = true;
            if (ActivityController.DecimalValueControl.AllowRequiredValidate || ValidateInformationForm.IsRequired("DecimalValue"))
                valid = Info.DecimalValue != null;
        
            if (!valid)
            {
                AddErrorMessage(GetRequiredMessage_DecimalValue());
                return false;
            }
        
            if (ActivityController.DecimalValueControl.AllowValidate)
                ValidateField_DecimalValue(ref valid);
        
            return valid;
        }
        
        partial void ValidateField_BoolValue(ref bool valid);
        
        private bool ValidateField_BoolValue()
        {
            var valid = true;
            if (ActivityController.BoolValueControl.AllowRequiredValidate || ValidateInformationForm.IsRequired("BoolValue"))
                valid = Info.BoolValue != null;
        
            if (!valid)
            {
                AddErrorMessage(GetRequiredMessage_BoolValue());
                return false;
            }
        
            if (ActivityController.BoolValueControl.AllowValidate)
                ValidateField_BoolValue(ref valid);
        
            return valid;
        }
        
        private void UpdateForm(bool loadRow)
        {
            if (!IsPostBack)
                loadRow = true;
        
            if (IsRead)
                Info.IsRead = true;
        
            if (!IsNew && loadRow)
            {
                var row = SelectedValueKey == null ? null : source.View.GetSelect(SelectedValueKey.Value).FirstOrDefault();
                if (row == null)
                {
                    if (SelectedValueKey != null)
                        AddErrorMessage(Nat.Web.Controls.Properties.Resources.ERowIsDeletedOrNotHavePermissions);
                    SelectedValueKey = null;
                    IsRead = true;
                    Info.IsRead = true;
                    FormPanelDIC_MySecondDictionary.Hidden = true;
                    return;
                }
        
                if (!AccessOptions.CheckPermitEdit())
                {
                    if (!IsRead)
                        AddErrorMessage(Nat.Web.Controls.Properties.Resources.EDoesNotHavePermitForEdit);
                    IsRead = true;
                    Info.IsRead = true;
                }
                else if (!row.CanEdit)
                {
                    if (!IsRead)
                    {
                        var messages = source.View.GetEditErrors(SelectedValueKey.Value, DIC_MySecondDictionaryResources.Header);
                        if (messages.All(string.IsNullOrEmpty))
                            AddErrorMessage(Nat.Web.Controls.Properties.Resources.EDoesNotHavePermitForEdit);
                        else
                            AddErrorMessage(messages.Where(r => !string.IsNullOrEmpty(r)));
                    }
        
                    IsRead = true;
                    Info.IsRead = true;
                }
        
                rowVersionHiddenField.Text = Convert.ToBase64String(row.Item.RowVersion.ToArray());
                object data;
                data = 
                    new[]
                        {
                            new
                                {
                                    id = row.Item.refFirstDictionary,
                                    RowName = DIC_MySecondDictionaryCacheNames.GetByTime_refFirstDictionary(DB, row.Item),
                                    //AdditionalValues = row.AdditionalValues,
                                },
                        };
                if (Page.IsPostBack)
                    Store_refFirstDictionary.LoadData(data, true);
                else
                    Store_refFirstDictionary.Data = data;
        
                FormPanelDIC_MySecondDictionary.SetValues(
                    new 
                        {
                            row.Item.Name,
                            row.Item.refFirstDictionary,
                            row.Item.DecimalValue,
                            row.Item.BoolValue,
                        });
                UpdateForm(row.Item);
                FormPanelDIC_MySecondDictionary.DataBind();
            }
            else if (IsNew && !AccessOptions.CheckPermitAdd())
            {
                AddErrorMessage(Nat.Web.Controls.Properties.Resources.EDoesNotHavePermitForAdd);
                IsNew = false;
                IsRead = true;
                Info.IsRead = true;
                UpdateFormToNull();
            }
            else if (IsNew && loadRow)
            {
                var messages = source.View.AllowAddRowForTableTypes(NavigatorControl.Values, DIC_MySecondDictionaryResources.Header).ToList();
                if (messages.Any(r => !string.IsNullOrEmpty(r)))
                {
                    foreach(var message in messages.Where(r => !string.IsNullOrEmpty(r)))
                        AddErrorMessage(message);
                    IsNew = false;
                    IsRead = true;
                    Info.IsRead = true;
                    UpdateFormToNull();
                }
                else if (messages.Any(string.IsNullOrEmpty))
                {
                    AddErrorMessage(Nat.Web.Controls.Properties.Resources.EDoesNotHavePermitForAdd);
                    IsNew = false;
                    IsRead = true;
                    Info.IsRead = true;
                    UpdateFormToNull();
                }
                else
                {
                    rowVersionHiddenField.Text = string.Empty;
                    FormPanelDIC_MySecondDictionary.SetValues(null);
                    UpdateFormToNull();
                    FormPanelDIC_MySecondDictionary.DataBind();
                }
            }
        }
        
        private void UpdateForm(DIC_MySecondDictionary row)
        {
            Info.Name = row.Name;
            Info.refFirstDictionary = row.refFirstDictionary;
            Info.DecimalValue = row.DecimalValue;
            Info.BoolValue = row.BoolValue;
        }
        
        private void UpdateFormToNull()
        {
            Info.Name = null;
            Info.refFirstDictionary = null;
            Info.DecimalValue = null;
            Info.BoolValue = null;
        }
        
        private void GenerateHtmlAdditionalButtonsInternal()
        {
            var toolbar = FormPanelDIC_MySecondDictionary.BottomBar.First();
            Action<AbstractComponent> addButton = commponent => toolbar.Items.Add(commponent);
            Action<AbstractComponent, AbstractComponent> insertAfterButton = (commponent, after) => toolbar.Items.Insert(toolbar.Items.IndexOf(after) + 1, commponent);
            var buttons = new AdditionalButtons(addButton, insertAfterButton);
            GenerateAdditionalButtons(buttons);
        }
        
        private void InitComboBoxViews()
        {
        }
        
        protected override IWorkFlow[] CreateWorkFlows()
        {
            return new IWorkFlow[] {};
        }
        
        public bool EditRowFromGrid(DIC_MySecondDictionary row)
        {
            InitConnection();
            SelectedValueKey = row.id;
            Info.IsEdit = true;
            IsRead = false;
            IsNew = false;
            UpdateForm(true);
            SetValuesFromGrid(row);
            SaveData(this, null);
            var id = row.id;
            EndTransaction();
            return id != refDIC_MySecondDictionary;
        }
        
        public void InsertRowFromGrid(DIC_MySecondDictionary row)
        {
            InitConnection();
            SelectedValueKey = null;
            Info.IsInsert = true;
            IsRead = false;
            IsNew = true;
            UpdateForm(true);
            if (IsNew)
            {
                SetValuesFromGrid(row);
                SaveData(this, null);
            }
            EndTransaction();
        }
        
        partial void SetValuesFromGridPartial(DIC_MySecondDictionary row);
        
        private void SetValuesFromGrid(DIC_MySecondDictionary row)
        {
            Info.Name = row.Name;
            Info.refFirstDictionary = row.refFirstDictionary == 0 ? null : (long?)row.refFirstDictionary;
            Info.DecimalValue = row.DecimalValue;
            Info.BoolValue = row.BoolValue;
            SetValuesFromGridPartial(row);
        }
        
        protected override void OnInit(EventArgs e)
        {
            base.OnInit(e);
            InitConnection();
            GenerateHtmlAdditionalButtonsInternal();
            InitControlPanels();
            InitComboBoxViews();
        }
        
        protected override void OnLoad(EventArgs e)
        {
            base.OnLoad(e);
        
            if (!IsPostBack || IsFirstCreation)
                _isStartAction = true;
        
            Store_BoolValue.Data = new[]
                {
                    new KeyValuePair<bool, string>(true, DIC_MySecondDictionaryResources.BoolValue__TrueText),
                    new KeyValuePair<bool, string>(false, DIC_MySecondDictionaryResources.BoolValue__FalseText),
                };
        
            UpdateForm(false);
        }
        
        protected override void OnPreRender(EventArgs e)
        {
            base.OnPreRender(e);
        
            EnsureLogicExecute();
            EnsureActivityControllerInitialized();
            ActivityController.ComputeActivities();
            EnsureValidateInformationFormInitialized();
        
            if (!DesignMode)
                ScriptManager.GetCurrent(Page).RegisterScriptControl(this);
        
            if ((IsNew && AccessOptions.CheckPermitAdd()) || (!IsRead && AccessOptions.CheckPermitEdit()))
            {
                SaveButton.Show();
                SaveButton.Hidden = false;
            }
            else
            {
                SaveButton.Hide();
                SaveButton.Hidden = true;
            }
            OnPreRender();
        }
        
        protected override void Render(HtmlTextWriter writer)
        {
            base.Render(writer);
            if (!DesignMode)
                ScriptManager.GetCurrent(Page).RegisterScriptDescriptors(this);
        }
        
        IEnumerable<ScriptDescriptor> IScriptControl.GetScriptDescriptors()
        {
            if (FormPanelDIC_MySecondDictionary.Hidden)
                return new ScriptDescriptor[0];
            return ((IScriptControl)ActivityController).GetScriptDescriptors();
        }
        
        IEnumerable<ScriptReference> IScriptControl.GetScriptReferences()
        {
            return ((IScriptControl)ActivityController).GetScriptReferences();
        }
        
        
        private void SetDefaultValues()
        {
            _setDefaultValues = true;
            Info.refFirstDictionary = NavigatorControl.Values.DIC_MyFirstDictionary;
        }
        
        
        private bool _refFirstDictionaryInitedFeild;
        
        
        public void EnsureInitedDefaultValue(Type type)
        {
            if (!IsStartAction || _setDefaultValues || _isNoPermit || !IsNew) return;
            if (type == typeof(DIC_MyFirstDictionary))
            {
                if (_refFirstDictionaryInitedFeild) return;
                _refFirstDictionaryInitedFeild = true;
                Info.refFirstDictionary = NavigatorControl.Values.DIC_MyFirstDictionary;
                return;
            }
        }
        
        private void SetDefaultValues(DIC_MySecondDictionary item)
        {
            var properties = GetDefaultProperties();
        }
        
        protected void EnsureActivityControllerInitialized()
        {
            if (ActivityControllerInitialized)
                return;
            ActivityControllerInitialized = true;
            ActivityController = new DIC_MySecondDictionaryActivityController();
            var dic = GetValuesForActivityController();
            ActivityController.Initialize(this, dic, Info);
        }
        
        private Dictionary<string, object> GetValuesForActivityController()
        {
            var dic = new Dictionary<string, object>();
            dic["Name"] = Info.Name;
            dic["refFirstDictionary"] = Info.refFirstDictionary;
            dic["DecimalValue"] = Info.DecimalValue;
            dic["BoolValue"] = Info.BoolValue;
        
            return dic;
        }
        
        protected void EnsureValidateInformationFormInitialized()
        {
            if (ValidateInformationFormInitialized)
                return;
        
            ValidateInformationFormInitialized = true;
            ValidateInformationForm = 
                new DIC_MySecondDictionaryValidateInformationForm(FormPanelDIC_MySecondDictionary)
                    {
                        ValidationGroup = "DIC_MySecondDictionary",
                    };
        
        
            GetValidators_Name(ValidateInformationForm.Name);
            ValidateInformationForm.AddDefaultValidatorsForName(Info);
            ValidateInformationForm.ApplyValidators(
                new ValidateInformationFormApplyArgsInfo
                    {
                        ValidatorCode = "Name",
                        Control = Info.NameControl,
                        ReadOnly = ActivityController.NameControl.ReadOnly,
                        ValidationContainer = "phName",
                    });
        
            GetValidators_refFirstDictionary(ValidateInformationForm.refFirstDictionary);
            ValidateInformationForm.AddDefaultValidatorsForrefFirstDictionary(Info);
            ValidateInformationForm.ApplyValidators(
                new ValidateInformationFormApplyArgsInfo
                    {
                        ValidatorCode = "refFirstDictionary",
                        Control = Info.refFirstDictionaryControl,
                        ReadOnly = ActivityController.refFirstDictionaryControl.ReadOnly,
                        ValidationContainer = "phrefFirstDictionary",
                    });
        
            GetValidators_DecimalValue(ValidateInformationForm.DecimalValue);
            ValidateInformationForm.AddDefaultValidatorsForDecimalValue(Info);
            ValidateInformationForm.ApplyValidators(
                new ValidateInformationFormApplyArgsInfo
                    {
                        ValidatorCode = "DecimalValue",
                        Control = Info.DecimalValueControl,
                        ReadOnly = ActivityController.DecimalValueControl.ReadOnly,
                        ValidationContainer = "phDecimalValue",
                    });
        
            GetValidators_BoolValue(ValidateInformationForm.BoolValue);
            ValidateInformationForm.AddDefaultValidatorsForBoolValue(Info);
            ValidateInformationForm.ApplyValidators(
                new ValidateInformationFormApplyArgsInfo
                    {
                        ValidatorCode = "BoolValue",
                        Control = Info.BoolValueControl,
                        ReadOnly = ActivityController.BoolValueControl.ReadOnly,
                        ValidationContainer = "phBoolValue",
                    });
        }
        
        private void SetReadOnlyValues(DIC_MySecondDictionary item)
        {
        }
        
        private void SetOtherValues(DIC_MySecondDictionary item)
        {
        }
        
        private void SetMultipleKeyValues(DIC_MySecondDictionary item)
        {
        }
        
        private void UploadFilesUpdateItem(DIC_MySecondDictionary item)
        {
        }
        
        private void UploadFiles()
        {
        }

        public void RemoteValidationFields(object sender, RemoteValidationEventArgs e)
        {
            var value = (JValue)e.Value;
            e.Success = true;
            switch (e.Name)
            {
                case "Name":
                    RemoteValidation_Name(value, e);
                    break;
                case "refFirstDictionary":
                    RemoteValidation_refFirstDictionary(value, e);
                    break;
                case "DecimalValue":
                    RemoteValidation_DecimalValue(value, e);
                    break;
                case "BoolValue":
                    RemoteValidation_BoolValue(value, e);
                    break;
            }
        }

        #endregion
        
        #region Events
        
        protected void lds_Inserted(object sender, LinqDataSourceStatusEventArgs e)
        {
            var row = e.Result as DIC_MySecondDictionary;
            OnInserted(row != null, row);
            OnInserted(e);
        
            if (row != null && !HasErrors)
            {
                if (DB.Transaction != null)
                    CommitDBTransaction();
            }
        }
        
        protected void lds_Updated(object sender, LinqDataSourceStatusEventArgs e)
        {
            var row = e.Result as DIC_MySecondDictionary;
            var hasRow = row != null;
            OnUpdated(hasRow, row);
            OnUpdated(e);
        
            if (row != null && !HasErrors)
            {
                if (DB.Transaction != null)
                    CommitDBTransaction();
            }
        }
        
        protected void OnInserted(bool inserted, DIC_MySecondDictionary row)
        {
            if (inserted)
            {
               refDIC_MySecondDictionary = row.id;
            }
        
            foreach (var logic in logics)
            {
                var errors = logic.AfterSave(inserted, row);
                if (errors != null && errors.Count > 0)
                {
                    foreach(var message in errors)
                        AddErrorMessage(message);
                    break;
                }
            }
        
                #region InsertChildCollections
            if (row != null)
            {
                
            }
            #endregion
        
            if (row != null)
            {
                foreach (var wf in WorkFlows)
                {
                    wf.DataContext = DB;
                    wf.BaseControlInfo = Info;
                    wf.JournalControl = this;
                    wf.OnInserted(row);
                }
            }
        }
        
        protected void OnUpdated(bool updated, DIC_MySecondDictionary row)
        {
            if (updated)
            {
                refDIC_MySecondDictionary = row.id;
                UpdateRefDIC_MySecondDictionary(row);
            }
        
            foreach (var logic in logics)
            {
                var errors = logic.AfterSave(updated, row);
                if (errors != null && errors.Count > 0)
                {
                    foreach(var message in errors)
                        AddErrorMessage(message);
                    break;
                }
            }
        
            #region UpdateChildCollections
            if (row != null)
            {
                
            }
            #endregion
        
            if (row != null)
            {
                foreach (var wf in WorkFlows)
                {
                    wf.DataContext = DB;
                    wf.BaseControlInfo = Info;
                    wf.JournalControl = this;
                    wf.OnUpdated(row, refDIC_MySecondDictionary.ToString());
                }
            }
        }
        
        protected void ldsChanges_Selecting(object sender, LinqDataSourceSelectEventArgs e)
        {
        }
        
        protected void lds_Selecting(object sender, LinqDataSourceSelectEventArgs e)
        {
        }
        
        protected void lds_Updating(object sender, LinqDataSourceUpdateEventArgs e)
        {
            if (e.Exception != null)
            {
                AddErrorMessage(e.Exception.Message);
                LogMonitor.LogException(e.Exception);
                e.ExceptionHandled = true;
                return;
            }
        
            SetReadOnlyValues((DIC_MySecondDictionary)e.NewObject);
            SetMultipleKeyValues((DIC_MySecondDictionary)e.NewObject);
            SetOtherValues((DIC_MySecondDictionary)e.NewObject);
            e.Cancel = !Updating((DIC_MySecondDictionary)e.OriginalObject, (DIC_MySecondDictionary)e.NewObject);
        }
        
        protected void ldsChanges_Updating(object sender, LinqDataSourceUpdateEventArgs e)
        {
            if (e.Exception != null)
            {
                AddErrorMessage(e.Exception.Message);
                LogMonitor.LogException(e.Exception);
                e.ExceptionHandled = true;
                return;
            }
        
            SetReadOnlyValues((DIC_MySecondDictionary)e.NewObject);
            SetMultipleKeyValues((DIC_MySecondDictionary)e.NewObject);
            SetOtherValues((DIC_MySecondDictionary)e.NewObject);
            e.Cancel = !Updating((DIC_MySecondDictionary)e.OriginalObject, (DIC_MySecondDictionary)e.NewObject);
        }
        
        protected void lds_Inserting(object sender, LinqDataSourceInsertEventArgs e)
        {
            if (e.Exception != null)
            {
                AddErrorMessage(e.Exception.Message);
                LogMonitor.LogException(e.Exception);
                e.ExceptionHandled = true;
                return;
            }
        
            SetReadOnlyValues((DIC_MySecondDictionary)e.NewObject);
            SetMultipleKeyValues((DIC_MySecondDictionary)e.NewObject);
            SetOtherValues((DIC_MySecondDictionary)e.NewObject);
            e.Cancel = !Inserting((DIC_MySecondDictionary) e.NewObject);
        }
        
        protected void ldsChanges_Inserting(object sender, LinqDataSourceInsertEventArgs e)
        {
            if (e.Exception != null)
            {
                AddErrorMessage(e.Exception.Message);
                LogMonitor.LogException(e.Exception);
                e.ExceptionHandled = true;
                return;
            }
        
            SetReadOnlyValues((DIC_MySecondDictionary)e.NewObject);
            SetMultipleKeyValues((DIC_MySecondDictionary)e.NewObject);
            SetOtherValues((DIC_MySecondDictionary)e.NewObject);
            e.Cancel = !Inserting((DIC_MySecondDictionary) e.NewObject);
        }
        
        protected void Source_Selecting(object sender, DataSourceSelectingEventArgs e)
        {
            e.FilterControl = GetFilterControl((DBDataContext)e.DB);
        }
        
        protected void lds_ContextCreating(object sender, LinqDataSourceContextEventArgs e)
        {
            OnContextCreating(e);
            e.ObjectInstance = DB;
        }
        
        protected void lds_ContextDisposing(object sender, LinqDataSourceDisposeEventArgs e)
        {
            if (_db != null && _db.Transaction != null)
                RollbackDBTransaction();
            _db = null;
            var d = (IDisposable)e.ObjectInstance;
            d.Dispose();
        }
        
        
           protected void jdsrefFirstDictionary_Selecting(object sender, DataSourceSelectingEventArgs e)
           {
               long? value;
               long? newValue = null;
               if (currentRow != null)
               {
                   long? initNewValue;
                   initNewValue = currentRow.refFirstDictionary;
                   newValue = initNewValue;
               }
               var parameters = new BrowseFilterParameters();
               GetBrowseFilterParameters_refFirstDictionary(parameters);
               GetBrowseFilterParameters("refFirstDictionary", parameters);
               jdsrefFirstDictionary.BaseView.SelectParameters = Info.Get_refFirstDictionarySelectParameters();
               var control = 
                   jdsrefFirstDictionary.BaseView.CreateDefaultFilter(
                       "SampleDictionaries.UserControls.DIC_MyFirstDictionaryFilter",
                       "DIC_MyFirstDictionary",
                       "none",
                       newValue,
                       parameters,
                       e.DB);
               e.FilterControl = control;
           }
        
        #endregion

        #region Permission
        
        bool IAccessControl.CheckPermit(Page page)
        {
            return AccessOptions.CheckPermit();
        }
        
        #endregion

        #region Log
        
        private LogMonitor _logMonitor;
        protected LogMonitor LogMonitor
        {
            get
            {
                if(_logMonitor == null)
                {
                    _logMonitor = new LogMonitor();
                    _logMonitor.Init();
                }
                return _logMonitor;
            }
        }

        protected bool Inserting(DIC_MySecondDictionary newRow)
        {
        
            return true;
        }

        protected bool Updating(DIC_MySecondDictionary originalRow, DIC_MySecondDictionary newRow)
        {
        
            return true;
        }
        
        #endregion

        #region EMailMessages

            

        #endregion
        
        #region Methods for help to show messages

        public static string GetRequiredMessage(string group, string header)
        {
            return string.Format(Nat.Web.Controls.Properties.Resources.SRequiredFieldMessage, GenerationHelper.GetHeaderName(group, header));
        }
        /// <summary>
        /// Сообщение об обязательности поля 'Name'.
        /// </summary>
        public static string GetRequiredMessage_Name()
        {
            return string.Format(Nat.Web.Controls.Properties.Resources.SRequiredFieldMessage, GenerationHelper.GetHeaderName(DIC_MySecondDictionaryResources.Name__Group, DIC_MySecondDictionaryResources.Name__Header));
        }
        
        /// <summary>
        /// Сообщение об обязательности поля 'First Dictionary Value'.
        /// </summary>
        public static string GetRequiredMessage_refFirstDictionary()
        {
            return string.Format(Nat.Web.Controls.Properties.Resources.SRequiredFieldMessage, GenerationHelper.GetHeaderName(DIC_MySecondDictionaryResources.refFirstDictionary__Group, DIC_MySecondDictionaryResources.refFirstDictionary__Header));
        }
        
        /// <summary>
        /// Сообщение об обязательности поля 'Decimal Value'.
        /// </summary>
        public static string GetRequiredMessage_DecimalValue()
        {
            return string.Format(Nat.Web.Controls.Properties.Resources.SRequiredFieldMessage, GenerationHelper.GetHeaderName(DIC_MySecondDictionaryResources.DecimalValue__Group, DIC_MySecondDictionaryResources.DecimalValue__Header));
        }
        
        /// <summary>
        /// Сообщение об обязательности поля 'Boolean Value'.
        /// </summary>
        public static string GetRequiredMessage_BoolValue()
        {
            return string.Format(Nat.Web.Controls.Properties.Resources.SRequiredFieldMessage, GenerationHelper.GetHeaderName(DIC_MySecondDictionaryResources.BoolValue__Group, DIC_MySecondDictionaryResources.BoolValue__Header));
        }
        
        public static string GetMaxLengthMessage(int length)
        {
            return string.Format(Nat.Web.Controls.Properties.Resources.SMaxLength, length);
        }
        /// <summary>
        /// Сообщение о максимальной длине 255 поля 'Name'.
        /// </summary>
        public static string GetMaxLengthOfField_Name()
        {
            return string.Format(Nat.Web.Controls.Properties.Resources.SMaxLengthOfField, GenerationHelper.GetHeaderName(DIC_MySecondDictionaryResources.Name__Group, DIC_MySecondDictionaryResources.Name__Header), 255);
        }
        
        /// <summary>
        /// Сообщение о максимальной длине 10 поля 'Decimal Value'.
        /// </summary>
        public static string GetMaxLengthOfField_DecimalValue()
        {
            return string.Format(Nat.Web.Controls.Properties.Resources.SMaxLengthOfField, GenerationHelper.GetHeaderName(DIC_MySecondDictionaryResources.DecimalValue__Group, DIC_MySecondDictionaryResources.DecimalValue__Header), 10);
        }
        
        /// <summary>
        /// Сообщение о не корректном вводе числового значения в поле 'Decimal Value'.
        /// </summary>
        public static string GetNotCorrectNumberMessage_DecimalValue()
        {
            return string.Format(Nat.Web.Controls.Properties.Resources.SNotCorrectNumberOfField, GenerationHelper.GetHeaderName(DIC_MySecondDictionaryResources.DecimalValue__Group, DIC_MySecondDictionaryResources.DecimalValue__Header));
        }
        
        /// <summary>
        /// Заголовок колнки 'Name'. Берется из ресурсов с учетов группы.
        /// </summary>
        public static string GetHeaderOfColumn_Name()
        {
            return GenerationHelper.GetHeaderName(DIC_MySecondDictionaryResources.Name__Group, DIC_MySecondDictionaryResources.Name__Header);
        }
        
        /// <summary>
        /// Заголовок колнки 'First Dictionary Value'. Берется из ресурсов с учетов группы.
        /// </summary>
        public static string GetHeaderOfColumn_refFirstDictionary()
        {
            return GenerationHelper.GetHeaderName(DIC_MySecondDictionaryResources.refFirstDictionary__Group, DIC_MySecondDictionaryResources.refFirstDictionary__Header);
        }
        
        /// <summary>
        /// Заголовок колнки 'Decimal Value'. Берется из ресурсов с учетов группы.
        /// </summary>
        public static string GetHeaderOfColumn_DecimalValue()
        {
            return GenerationHelper.GetHeaderName(DIC_MySecondDictionaryResources.DecimalValue__Group, DIC_MySecondDictionaryResources.DecimalValue__Header);
        }
        
        /// <summary>
        /// Заголовок колнки 'Boolean Value'. Берется из ресурсов с учетов группы.
        /// </summary>
        public static string GetHeaderOfColumn_BoolValue()
        {
            return GenerationHelper.GetHeaderName(DIC_MySecondDictionaryResources.BoolValue__Group, DIC_MySecondDictionaryResources.BoolValue__Header);
        }
        
        #endregion

        #region Nested type: ControlInfo

        public partial class ControlInfo : BaseControlInfo
        {
            private Dictionary<string, object> savedValues;
            private DIC_MySecondDictionaryEdit edit;
            private TextBox _NameControl;
            public const int NameLength = 255;
            
            private ComboBox _refFirstDictionaryControl;
            
            SelectParameters _refFirstDictionarySelectParameters;
            
            public string Get_refFirstDictionaryAdditionalInfo()
            {
                var info = new SelectColumnParameters();
                info.SelectParameters = Get_refFirstDictionarySelectParameters();
                info.FieldName = "refFirstDictionary";
                info.FieldInfoItems = new ExtNetSelectColumnParameters.ExtNetFieldInfo[] {};
                return new JavaScriptSerializer().Serialize(info);
            }
            
            public SelectParameters Get_refFirstDictionarySelectParameters()
            {
                if (_refFirstDictionarySelectParameters == null)
                    Init_refFirstDictionarySelectParameters();
                return _refFirstDictionarySelectParameters;
            }
            
            private void Init_refFirstDictionarySelectParameters()
            {
                var parameters = new SelectParameters();
                parameters.SessionKey = edit.SessionKey;
                parameters.FieldName = "refFirstDictionary";
                if (!parameters.LoadFromSession())
                {
                    bool isKz = LocalizationHelper.IsCultureKZ;
                     parameters.SaveToSession();
                }
                _refFirstDictionarySelectParameters = parameters;
            }
            private NullableTextBox _DecimalValueControl;
            public const int DecimalValueLength = 10;
            public const int DecimalValuePrecision = 2;
            
            private CheckBox _BoolValueControl;
            
            
            private bool isWireToChangesEvents;
            private bool isWireToEditFieldEvents;
            private DBDataContext _db;

            public DBDataContext DB
            {
                get
                {
                    if (_db == null)
                    {
                        _db = new DBDataContext(SpecificInstances.DbFactory.CreateConnection());
                    }

                    return _db;
                }
                set
                {
                    _db = value;
                }
            }

            public ControlInfo(DIC_MySecondDictionaryEdit edit)
                : base (edit.FormPanelDIC_MySecondDictionary)
            {
                this.edit = edit;
                GetSelectedValue = () => edit.SelectedValueKey.ToString();
            }


            /// <summary>
            /// Name.
            /// </summary>
            public String Name
            {
                get
                {
                    if (NameControl.IsEmpty)
                        return null;
                    var value = NameControl.Text;
            
                    return Convert.ToString(value);
                }
                set
                {
                    NameControl.SetValue(value);
                }
            }

            /// <summary>
            /// Контрол поля "Name".
            /// </summary>
            public TextBox NameControl
            {
                get
                {
                    if (_NameControl == null)
                        _NameControl = (TextBox)FindControl("tbName");
                    return _NameControl;
                }
            }

            /// <summary>
            /// Флаг об изменении пользователем значения поля "Name", за последний раз.
            /// </summary>
            public bool IsNameChanged { get; set; }

            /// <summary>
            /// First Dictionary Value.
            /// </summary>
            public long? refFirstDictionary
            {
                get 
                {
                    edit.EnsureInitedDefaultValue(typeof(DIC_MyFirstDictionary));
                    var value = refFirstDictionaryControl != null ? (refFirstDictionaryControl.SelectedItem == null ? null : refFirstDictionaryControl.SelectedItem.Value) : null;
                    if (string.IsNullOrEmpty(value))
                        return null;
                    return Convert.ToInt64(value);
                }
                set
                {
                    if (value == refFirstDictionary)
                        return;
                    string text;
                    if (value == null)
                        text = string.Empty;
                    else
                        text = DIC_MySecondDictionaryCacheNames.GetByTime_refFirstDictionary(DB, value.Value);
                    object[] additionalValues = null;
            
                    if (value != null)
                    {
                        var data = 
                            new[]
                                {
                                    new
                                        {
                                            id = value.Value,
                                            RowName = text,
                                            AdditionalValues = additionalValues == null ? null : JSON.Serialize(additionalValues),
                                        },
                                };
                        if (edit.Page.IsPostBack)
                            edit.Store_refFirstDictionary.LoadData(data, true);
                        else
                            edit.Store_refFirstDictionary.Data = data;
                        refFirstDictionaryControl.SelectedItem.Value = value.ToString();
                        refFirstDictionaryControl.SelectedItem.Text = text;
                        refFirstDictionaryControl.SelectedItem.Mode = ParameterMode.Raw;
                    }
                    else
                    {
                        refFirstDictionaryControl.SelectedItem.Value = string.Empty;
                        refFirstDictionaryControl.SelectedItem.Text = string.Empty;
                        refFirstDictionaryControl.SelectedItem.Mode = ParameterMode.Raw;
                    }
            
                    refFirstDictionaryControl.SetValueAndFireSelect(value);
                }
            }

            /// <summary>
            /// Контрол поля "First Dictionary Value".
            /// </summary>
            public ComboBox refFirstDictionaryControl
            {
                get
                {
                    if (_refFirstDictionaryControl == null)
                        _refFirstDictionaryControl = (ComboBox)FindControl("lookuprefFirstDictionary");
                    return _refFirstDictionaryControl;
                }
            }

            /// <summary>
            /// Флаг об изменении пользователем значения поля "First Dictionary Value", за последний раз.
            /// </summary>
            public bool IsrefFirstDictionaryChanged { get; set; }

            /// <summary>
            /// Decimal Value.
            /// </summary>
            public Decimal? DecimalValue
            {
                get
                {
                    if (DecimalValueControl.IsEmpty)
                        return null;
                    var value = DecimalValueControl.Number;
            
                    return Convert.ToDecimal(value);
                }
                set
                {
                    DecimalValueControl.SetValue(value);
                }
            }

            /// <summary>
            /// Контрол поля "Decimal Value".
            /// </summary>
            public NullableTextBox DecimalValueControl
            {
                get
                {
                    if (_DecimalValueControl == null)
                        _DecimalValueControl = (NullableTextBox)FindControl("tbDecimalValue");
                    return _DecimalValueControl;
                }
            }

            /// <summary>
            /// Флаг об изменении пользователем значения поля "Decimal Value", за последний раз.
            /// </summary>
            public bool IsDecimalValueChanged { get; set; }

            /// <summary>
            /// Boolean Value.
            /// </summary>
            public Boolean? BoolValue
            {
                get
                {
                    if (BoolValueControl.IsEmpty)
                        return null;
                    var value = BoolValueControl.Checked;
            
                    return Convert.ToBoolean(value);
                }
                set
                {
                    BoolValueControl.SetValue(value);
                }
            }

            
            /// <summary>
            /// Контрол поля "Boolean Value".
            /// </summary>
            public CheckBox BoolValueControl
            {
                get
                {
                    if (_BoolValueControl == null)
                        _BoolValueControl = (CheckBox) FindControl("cbBoolValue");
                    return _BoolValueControl;
                }
            }

            /// <summary>
            /// Флаг об изменении пользователем значения поля "Boolean Value", за последний раз.
            /// </summary>
            public bool IsBoolValueChanged { get; set; }

            public override void WireToChangesEvent()
            {
                if (edit.SelectedValueKey != null && edit.IsRead || isWireToChangesEvents || (edit.SelectedValueKey != null && !edit.IsNew && !edit.IsRead && string.IsNullOrEmpty(SelectedValue)))
                    return;

                isWireToChangesEvents = true;
                NameControl.TextChanged += delegate { IsNameChanged = true; };
                refFirstDictionaryControl.ValueChanged += delegate { IsrefFirstDictionaryChanged = true; };
                DecimalValueControl.TextChanged += delegate { IsDecimalValueChanged = true; };
                BoolValueControl.CheckedChanged += delegate { IsBoolValueChanged = true; };
            }

            public override void WireToEditFieldEvents()
            {
                if (isWireToEditFieldEvents || (!(edit.IsNew) && string.IsNullOrEmpty(SelectedValue))) 
                    return;

                isWireToEditFieldEvents = true;
            }

            public override void ClearRefToControls()
            {
                _NameControl = null;
                _refFirstDictionaryControl = null;
                _DecimalValueControl = null;
                _BoolValueControl = null;
                isWireToChangesEvents = false;
                isWireToEditFieldEvents = false;
            }

            public override bool HasSavedValues
            {
                get { return savedValues != null; }
            }

            public override void SaveValues()
            {
                if (savedValues == null)
                    savedValues = new Dictionary<string, object>();
                else
                    savedValues.Clear();

                savedValues.Add("Name", NameControl.Text);
                savedValues.Add("refFirstDictionary", refFirstDictionaryControl.Text);
                savedValues.Add("DecimalValue", DecimalValueControl.Text);
                savedValues.Add("BoolValue", BoolValueControl.Checked);
            }

            public override void LoadValues()
            {
                if (savedValues == null)
                    throw new NullReferenceException("Before execute LoadValues need execute SaveValues");

                NameControl.Text = (string)savedValues["Name"];
                refFirstDictionaryControl.Text = (string)savedValues["refFirstDictionary"];
                DecimalValueControl.Text = (string)savedValues["DecimalValue"];
                BoolValueControl.Checked = (bool)savedValues["BoolValue"];
            }

            public override void SetValue(string property, object value, string text, string alternativeText)
            {
                switch (property)
                {
                    case "refFirstDictionary":
                        refFirstDictionary = (Int64)value;
                        break;
                    default:
                        throw new Exception(string.Format("property '{0}' not exist in table 'DIC_MySecondDictionary'", property));
                }
            }

/*
            private IList<WebControl> _controls;
            public IList<WebControl> Controls
            {
                get
                {
                    if (_controls == null)
                    {
                        _controls = new List<WebControl>
                                        {
                                            NameControl,
                                            refFirstDictionaryControl,
                                            DecimalValueControl,
                                            BoolValueControl,
                                        };
                    }
                    return _controls;
                }
            }*/
        }

        public partial class RecordEvents : BaseRecordEvents<long, DIC_MySecondDictionary>
        {
            private DBDataContext _db;
        
            protected DBDataContext DB
            {
                get
                {
                    if (_db == null)
                    {
                        _db = new DBDataContext(SpecificInstances.DbFactory.CreateConnection());
                    }
        
                    return _db;
                }
            }
        
            public long? DIC_MySecondDictionary
            {
                get
                {
                    if (!Values.ContainsKey(typeof(DIC_MySecondDictionary))) return null;
                    return (long?)Values[typeof(DIC_MySecondDictionary)];
                }
                set
                {
                    Values[typeof(DIC_MySecondDictionary)] = value;
                }
            }
            
            public long? DIC_MyFirstDictionary
            {
                get
                {
                    if (!Values.ContainsKey(typeof(DIC_MyFirstDictionary))) return null;
                    return (long?)Values[typeof(DIC_MyFirstDictionary)];
                }
                set
                {
                    Values[typeof(DIC_MyFirstDictionary)] = value;
                }
            }
        
            /// <summary>
            /// Не трогать!!! :)
            /// </summary>
            public DIC_MySecondDictionaryJournalDataSourceView.Row SelectedRow { get; set; }
        }

        #endregion
    }
}